apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-gin-by-contract
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: cdm-vlb-cae-harbor-pull