bases:
- ../base

resources:
- ingress.yaml

nameSuffix: -prd  

namespace: repind-prd
  
commonLabels:
  app.kubernetes.io/instance: search-individual-prd
  app.kubernetes.io/name: search-individual

images:
- name: harbor-vlb.af-klm.com/cdm/search-individual

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- replica-extra-options.yaml
- deploy-profile.yaml