apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-individual
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: cdm-vlb-prd-harbor-pull