apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-gin-by-lastname-firstname
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate