
package com.afklm.repind.ws.w000842;

import com.afklm.repind.ws.w000842.data.schema572954.CreateAProspectRequest;
import com.afklm.repind.ws.w000842.data.schema572954.CreateAProspectResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.net.SocketException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CreateAProspectService-v1", targetNamespace = "http://www.af-klm.com/services/passenger/CreateAProspectService-v1/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.repind.ws.w000842.data.schema572954.ObjectFactory.class,
    com.afklm.repind.ws.w000842.data.schema864.ObjectFactory.class,
    com.afklm.repind.ws.w000842.data.schema569983.ObjectFactory.class,
    com.afklm.repind.ws.w000842.data.schema571954.ObjectFactory.class,
    com.afklm.repind.ws.w000842.data.schema572955.ObjectFactory.class
})
public interface CreateAProspectServiceV1 {


    /**
     * 
     * @param request
     * @return
     *     returns com.afklm.repind.ws.w000842.data.schema572954.CreateAProspectResponse
     * @throws SystemFault
     * @throws MsgBusinessFault
     * @throws SocketException
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/CreateAProspectService-v1/createAProspect")
    @WebResult(name = "CreateAProspectResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/createAProspectDataType-v1/xsd", partName = "Response")
    public CreateAProspectResponse createAProspect(
        @WebParam(name = "CreateAProspectRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/createAProspectDataType-v1/xsd", partName = "Request")
        CreateAProspectRequest request)
        throws MsgBusinessFault, SystemFault, SocketException
    ;

}
