

CREATE  TABLE "SIC2"."TEMP_LAST_ACTIVITY" 
   (
    "LAST_ACTIVITY_ID"  NUMBER(12,0) GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
       "SGIN" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
    "DDATE_MODIFICATION" DATE NOT NULL ENABLE, 
    "SSIGNATURE_MODIFICATION" VARCHAR2(16 BYTE), 
    "SSITE_MODIFICATION" VARCHAR2(10 BYTE), 
    "SSOURCE_MODIFICATION" VARCHAR2(50 BYTE),
    CONSTRAINT LAST_ACTIVITY_PK PRIMARY KEY (LAST_ACTIVITY_ID)
   )
   
   
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."LAST_ACTIVITY_ID" IS 'Last activity identifier';
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."SGIN" IS 'Individual GIN number';
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."DDATE_MODIFICATION" IS 'Last modification date';
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."SSIGNATURE_MODIFICATION" IS 'Signature for individual modification';
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."SSITE_MODIFICATION" IS 'Site where modification originated';
  COMMENT ON COLUMN "SIC2"."TEMP_LAST_ACTIVITY"."SSOURCE_MODIFICATION" IS 'Table modification';
  
  
   ALTER TABLE "SIC2"."TEMP_LAST_ACTIVITY"
   ADD CONSTRAINT TEMP_CONSTRAINT_GIN_UNIQUE UNIQUE (SGIN);
   
   
   CREATE INDEX "SIC2"."TEMP_DDATE_MODIFICATION" ON "SIC2"."TEMP_LAST_ACTIVITY" ("DDATE_MODIFICATION" DESC)
	PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SIC_TBL" ;
	
=====================================================================================================================================
INSERT INTO SIC2.TEMP_LAST_ACTIVITY (SGIN, DDATE_MODIFICATION, SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, SSOURCE_MODIFICATION)  
SELECT SGIN, DDATE_MODIFICATION, SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'INDIVIDUS' AS SSOURCE_MODIFICATION
FROM INDIVIDUS_ALL WHERE DDATE_MODIFICATION IS NOT NULL AND SGIN IS NOT NULL;


=======================================================CURSOR ON INDIVIDU ALL===========================================================================




DECLARE
V_SGIN INDIVIDUS_ALL.SGIN%TYPE;
V_DDATE_MODIFICATION INDIVIDUS_ALL.DDATE_MODIFICATION%TYPE;
V_SSIGNATURE_MODIFICATION INDIVIDUS_ALL.SSIGNATURE_MODIFICATION%TYPE;
V_SSITE_MODIFICATION INDIVIDUS_ALL.SSITE_MODIFICATION%TYPE;
V_SSOURCE_MODIFICATION VARCHAR2(50 BYTE) := 'INDIVIDUS';
CURSOR curseur_individu IS
SELECT SGIN, DDATE_MODIFICATION, SSIGNATURE_MODIFICATION, SSITE_MODIFICATION FROM INDIVIDUS_ALL WHERE DDATE_MODIFICATION IS NOT NULL AND SGIN IS NOT NULL;

BEGIN
OPEN curseur_individu ;

LOOP
FETCH curseur_individu INTO V_SGIN ,V_DDATE_MODIFICATION,V_SSIGNATURE_MODIFICATION,V_SSITE_MODIFICATION ;

INSERT INTO SIC2.TEMP_LAST_ACTIVITY
                 (
                        SGIN,
                        DDATE_MODIFICATION,
                        SSIGNATURE_MODIFICATION,
                        SSITE_MODIFICATION,
                        SSOURCE_MODIFICATION
 
                )VALUES
                (
                V_SGIN,
                V_DDATE_MODIFICATION,
                V_SSIGNATURE_MODIFICATION,
                V_SSITE_MODIFICATION,
                V_SSOURCE_MODIFICATION
                );
                
                commit;

EXIT WHEN NOT curseur_individu%FOUND;
END LOOP;
CLOSE curseur_individu ;
END;



=================================================================================================================================================
DECLARE
V_SGIN EMAILS.SGIN%TYPE;
V_DDATE_MODIFICATION EMAILS.DDATE_MODIFICATION%TYPE;
V_SSIGNATURE_MODIFICATION EMAILS.SSIGNATURE_MODIFICATION%TYPE;
V_SSITE_MODIFICATION EMAILS.SSITE_MODIFICATION%TYPE;
V_SSOURCE_MODIFICATION VARCHAR2(50 BYTE) := 'EMAILS';
CURSOR curseur_email_individu IS
SELECT E.SGIN, E.DDATE_MODIFICATION, E.SSIGNATURE_MODIFICATION, E.SSITE_MODIFICATION
FROM TEMP_LAST_ACTIVITY T, EMAILS E 
WHERE T.SGIN = E.SGIN AND E.DDATE_MODIFICATION > T.DDATE_MODIFICATION AND E.DDATE_MODIFICATION IS NOT NULL AND E.SGIN IS NOT NULL;

BEGIN
OPEN curseur_email_individu ;

LOOP
FETCH curseur_email_individu INTO V_SGIN ,V_DDATE_MODIFICATION,V_SSIGNATURE_MODIFICATION,V_SSITE_MODIFICATION ;

	UPDATE TEMP_LAST_ACTIVITY
					SET DDATE_MODIFICATION = V_DDATE_MODIFICATION,
					SSITE_MODIFICATION = V_SSITE_MODIFICATION,
					SSIGNATURE_MODIFICATION = V_SSIGNATURE_MODIFICATION,
					SSOURCE_MODIFICATION = V_SSOURCE_MODIFICATION
					WHERE SGIN = V_SGIN;

                
                commit;

EXIT WHEN NOT curseur_email_individu%FOUND;
END LOOP;
CLOSE curseur_email_individu ;
END;

=================================================================================================================================================
Rapport d'erreur -
ORA-30036: impossible d'etendre le segment par 8 dans le tablespace d'annulation 'UNDOTBS'
ORA-06512: a ligne 16
30036. 00000 -  "unable to extend segment by %s in undo tablespace '%s'"
*Cause:    the specified undo tablespace has no more space available.
*Action:   Add more space to the undo tablespace before retrying
           the operation. An alternative is to wait until active
           transactions to commit.
	