WITH BATCH_CHECK  AS (

SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION , 'ADR_POST' AS SSOURCE_MODIFICATION

FROM ADR_POST 
UNION ALL

SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'EMAILS' AS SSOURCE_MODIFICATION

FROM EMAILS 
UNION ALL

SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'TELECOMS' AS SSOURCE_MODIFICATION

FROM TELECOMS

UNION ALL
SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'HANDICAP' AS SSOURCE_MODIFICATION

FROM HANDICAP

UNION ALL
SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'PREFERENCE' AS SSOURCE_MODIFICATION

FROM PREFERENCE
UNION ALL

SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'ROLE_CONTRATS' AS SSOURCE_MODIFICATION

FROM ROLE_CONTRATS

UNION ALL

SELECT SGIN, max(DDATE_MODIFICATION), SSIGNATURE_MODIFICATION, SSITE_MODIFICATION, 'ROLE_UCCR' AS SSOURCE_MODIFICATION

FROM ROLE_UCCR


UNION ALL

SELECT SGIN, max(MODIFICATION_DATE) AS DDATE_MODIFICATION,  MODIFICATION_SIGNATURE AS SSIGNATURE_MODIFICATION, MODIFICATION_SITE AS SSITE_MODIFICATION, 'COMMUNICATION_PREFERENCES' AS SSOURCE_MODIFICATION

FROM COMMUNICATION_PREFERENCES

UNION ALL

SELECT SGIN_DELEGATOR AS SGIN, max(MODIFICATION_DATE) AS DDATE_MODIFICATION,  MODIFICATION_SIGNATURE AS SSIGNATURE_MODIFICATION, MODIFICATION_SITE AS SSITE_MODIFICATION, 'DELEGATION_DATA' AS SSOURCE_MODIFICATION

FROM DELEGATION_DATA
UNION ALL

SELECT SGIN, max(MODIFICATION_DATE) AS DDATE_MODIFICATION,  MODIFICATION_SIGNATURE AS SSIGNATURE_MODIFICATION, MODIFICATION_SITE AS SSITE_MODIFICATION, 'EXTERNAL_IDENTIFIER' AS SSOURCE_MODIFICATION

FROM EXTERNAL_IDENTIFIER
)
SELECT SGIN, max(DDATE_MODIFICATION) AS DDATE_MODIFICATION, SSIGNATURE_MODIFICATION, SSITE_MODIFICATION,SSOURCE_MODIFICATION
FROM BATCH_CHECK
WHERE  SGIN="110000025401"

GROUP BY SGIN, SSIGNATURE_MODIFICATION, SSITE_MODIFICATION,SOURCE_MODIFICATION;

===================================================================================================================================================

SELECT E.SGIN, MAX(E.DDATE_MODIFICATION) AS DDATE_MODIFICATION , E.SSIGNATURE_MODIFICATION, E.SSITE_MODIFICATION, 'EMAILS' AS SOURCE_MODIFICATION"
FROM EMAILS E JOIN INDIVIDUS_ALL A ON E.SGIN = A.SGIN




















































































