  /*CREATE TABLE*/
 
  CREATE  TABLE "SIC2"."LAST_ACTIVITY" 
   (
    "LAST_ACTIVITY_ID"  NUMBER(12,0) GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
    "SGIN" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
    "DDATE_MODIFICATION" DATE NOT NULL ENABLE, 
    "SSIGNATURE_MODIFICATION" VARCHAR2(16 BYTE), 
    "SSITE_MODIFICATION" VARCHAR2(10 BYTE), 
    "SSOURCE_MODIFICATION" VARCHAR2(50 BYTE),
    CONSTRAINT LAST_ACTIVITY_PK PRIMARY KEY (LAST_ACTIVITY_ID)
   )
   /*ADD COMMENT*/
      
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."LAST_ACTIVITY_ID" IS 'Last activity identifier';
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."SGIN" IS 'Individual GIN number';
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."DDATE_MODIFICATION" IS 'Last modification date';
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."SSIGNATURE_MODIFICATION" IS 'Signature for individual modification';
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."SSITE_MODIFICATION" IS 'Site where modification originated';
  COMMENT ON COLUMN "SIC2"."LAST_ACTIVITY"."SSOURCE_MODIFICATION" IS 'Table modification';
 
  /*CREATE CONSTRAINT UNIQUE ON GIN*/

   ALTER TABLE "SIC2"."LAST_ACTIVITY"
   ADD CONSTRAINT CONSTRAINT_GIN_UNIQUE UNIQUE (SGIN);
   
   
   /*CREATE INDEX ON DATE MODIFICATION*/
   
	CREATE INDEX "SIC2"."DDATE_MODIFICATION" ON "SIC2"."LAST_ACTIVITY" ("DDATE_MODIFICATION" DESC)
	PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
	STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	TABLESPACE "SIC_TBL" ;