
package com.afklm.repind.ws.createorupdateindividualdata.v08;

import com.afklm.repind.ws.createorupdateindividualdata.v08.data.response.BusinessErrorBloc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BusinessErrorBlocElement", targetNamespace = "http://www.af-klm.com/services/passenger/response-v8/xsd")
public class BusinessErrorBlocBusinessException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessErrorBloc faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessErrorBlocBusinessException(String message, BusinessErrorBloc faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessErrorBlocBusinessException(String message, BusinessErrorBloc faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.afklm.sic.ws.createorupdateindividualdata.v08.data.response.BusinessErrorBloc
     */
    public BusinessErrorBloc getFaultInfo() {
        return faultInfo;
    }

}
