
package com.afklm.repind.ws.createorupdateindividualdata.v08;

import com.afklm.repind.ws.createorupdateindividualdata.v08.data.CreateUpdateIndividualRequest;
import com.afklm.repind.ws.createorupdateindividualdata.v08.data.CreateUpdateIndividualResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CreateUpdateIndividualService-v8", targetNamespace = "http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.repind.ws.createorupdateindividualdata.siccommontype.siccommontype.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.v08.data.response.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.v08.data.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.sicindividutype.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.v08.data.request.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.siccommontype.siccommonenum.ObjectFactory.class,
    com.afklm.soa.common.faults.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.prospecttype.prospectdatatype.ObjectFactory.class,
    com.afklm.repind.ws.createorupdateindividualdata.softcomputingtype.ObjectFactory.class
})
public interface CreateUpdateIndividualServiceV8 {


    /**
     * 
     * @param request
     * @return
     *     returns com.afklm.sic.ws.createorupdateindividualdata.v08.data.CreateUpdateIndividualResponse
     * @throws SystemException
     * @throws BusinessErrorBlocBusinessException
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/createIndividual")
    @WebResult(name = "CreateUpdateIndividualResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/data-v8/xsd", partName = "response")
    public CreateUpdateIndividualResponse createIndividual(
        @WebParam(name = "CreateUpdateIndividualRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/data-v8/xsd", partName = "request")
        CreateUpdateIndividualRequest request)
        throws BusinessErrorBlocBusinessException, SystemException
    ;

}
