
package com.afklm.repind.ws.createorupdateindividualdata.v08;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CreateUpdateIndividualServiceService-v8", targetNamespace = "http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_CreateUpdateIndividualService-v8.wsdl")
public class CreateUpdateIndividualServiceServiceV8
    extends Service
{

    private final static URL CREATEUPDATEINDIVIDUALSERVICESERVICEV8_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.afklm.repind.ws.createorupdateindividualdata.v08.CreateUpdateIndividualServiceServiceV8 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.afklm.repind.ws.createorupdateindividualdata.v08.CreateUpdateIndividualServiceServiceV8 .class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_CreateUpdateIndividualService-v8.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_CreateUpdateIndividualService-v8.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CREATEUPDATEINDIVIDUALSERVICESERVICEV8_WSDL_LOCATION = url;
    }

    public CreateUpdateIndividualServiceServiceV8(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateUpdateIndividualServiceServiceV8() {
        super(CREATEUPDATEINDIVIDUALSERVICESERVICEV8_WSDL_LOCATION, new QName("http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/wsdl", "CreateUpdateIndividualServiceService-v8"));
    }

    /**
     * 
     * @return
     *     returns CreateUpdateIndividualServiceV8
     */
    @WebEndpoint(name = "CreateUpdateIndividualService-v8-soap11http")
    public CreateUpdateIndividualServiceV8 getCreateUpdateIndividualServiceV8Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/wsdl", "CreateUpdateIndividualService-v8-soap11http"), CreateUpdateIndividualServiceV8.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateUpdateIndividualServiceV8
     */
    @WebEndpoint(name = "CreateUpdateIndividualService-v8-soap11http")
    public CreateUpdateIndividualServiceV8 getCreateUpdateIndividualServiceV8Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/CreateUpdateIndividualService-v8/wsdl", "CreateUpdateIndividualService-v8-soap11http"), CreateUpdateIndividualServiceV8.class, features);
    }

}
