apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-gin-by-social-media
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: cdm-vlb-prd-harbor-pull