spring:
  datasource:
    tns_admin_env: PROD
    url: jdbc:oracle:thin:@SIC_PLE.WORLD
    maxPoolSize: 10

vault:
  uri: https://vault-tls.airfranceklm.com
  namespace: repind
  env: prod
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
