logging:
  level:
    root: INFO
    org.springframework.boot.web: DEBUG

server:
  port: 0

spring:
  application:
    name: "service-B"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
