spring:
  config:
    activate:
      on-profile: LE,prd
  datasource:
    tns_admin_env: PROD
    url: jdbc:oracle:thin:@REPIND_PRD.WORLD

vault:
  uri: https://vault-tls.airfranceklm.com
  namespace: repind
  env: prod
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO

ri-search-gin-by-email:
  url: http://search-gin-by-email-prd:8080/
ri-search-gin-by-phone:
  url: http://search-gin-by-phone-prd:8080/
ri-search-gin-by-contract:
  url: http://search-gin-by-contract-prd:8080/
ri-search-gin-by-social-media:
  url: http://search-gin-by-social-media-prd:8080/
ri-search-gin-by-lastname-firstname:
  url: http://search-gin-by-lastname-firstname-prd:8080/

server:
  servlet:
    context-path: /api-mgr


springdoc:
  enable-hateoas: false