apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage-doctor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: manage-doctor
          readinessProbe:
            httpGet:
              path: /infra/healthcheck