
package com.afklm.bdm.ws.w000413;

import com.afklm.bdm.ws.w000413.data.schema7312.DeleteMDRequest;
import com.afklm.bdm.ws.w000413.data.schema7312.DeleteMDResponse;
import com.afklm.bdm.ws.w000413.data.schema7312.StoreMDRequest;
import com.afklm.bdm.ws.w000413.data.schema7312.StoreMDResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * Create and store, update or delete Marketing data in the BDM.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StoreMarketingPreferencesCustomer-v1", targetNamespace = "http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.bdm.ws.w000413.data.schema7312.ObjectFactory.class,
    com.afklm.bdm.ws.w000413.data.schema864.ObjectFactory.class,
    com.afklm.bdm.ws.w000413.data.schema7309.ObjectFactory.class
})
public interface StoreMarketingPreferencesCustomerV1 {


    /**
     * update the marketing data of an individual in the BDM. for an individual you can update 5 types of components: - Personal information - TravelCompanions - TravelDocument - APIS data - TravelPreference. Any modifcation component will follow the rule cancel/replace. A null component will remain unchanged.
     * 
     * @param updateMDRequest
     * @return
     *     returns com.afklm.bdm.ws.w000413.data.schema7312.StoreMDResponse
     * @throws SystemFault
     * @throws MsgMarketingDataBusinessFault
     */
    @WebMethod(action = "http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/storeMarketingData")
    @WebResult(name = "StoreMDResponseElement", targetNamespace = "http://www.af-klm.com/services/marketingdata/store-v1/xsd", partName = "updateMDResponse")
    public StoreMDResponse storeMarketingData(
        @WebParam(name = "StoreMDRequestElement", targetNamespace = "http://www.af-klm.com/services/marketingdata/store-v1/xsd", partName = "updateMDRequest")
        StoreMDRequest updateMDRequest)
        throws MsgMarketingDataBusinessFault, SystemFault
    ;

    /**
     * delete all the marketing data of an individual in the BDM.
     * 
     * @param deleteMDRequest
     * @return
     *     returns com.afklm.bdm.ws.w000413.data.schema7312.DeleteMDResponse
     * @throws SystemFault
     * @throws MsgMarketingDataBusinessFault
     */
    @WebMethod(action = "http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/deleteMarketingData")
    @WebResult(name = "DeleteMDResponseElement", targetNamespace = "http://www.af-klm.com/services/marketingdata/store-v1/xsd", partName = "deleteMDResponse")
    public DeleteMDResponse deleteMarketingData(
        @WebParam(name = "DeleteMDRequestElement", targetNamespace = "http://www.af-klm.com/services/marketingdata/store-v1/xsd", partName = "deleteMDRequest")
        DeleteMDRequest deleteMDRequest)
        throws MsgMarketingDataBusinessFault, SystemFault
    ;

}
