
package com.afklm.bdm.ws.w000413;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * Create and store, update or delete Marketing data in the BDM.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StoreMarketingPreferencesCustomerService-v1", targetNamespace = "http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_StoreMarketingPreferencesCustomer-v01.wsdl")
public class StoreMarketingPreferencesCustomerServiceV1
    extends Service
{

    private final static URL STOREMARKETINGPREFERENCESCUSTOMERSERVICEV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.afklm.bdm.ws.w000413.StoreMarketingPreferencesCustomerServiceV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.afklm.bdm.ws.w000413.StoreMarketingPreferencesCustomerServiceV1 .class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_StoreMarketingPreferencesCustomer-v01.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_StoreMarketingPreferencesCustomer-v01.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        STOREMARKETINGPREFERENCESCUSTOMERSERVICEV1_WSDL_LOCATION = url;
    }

    public StoreMarketingPreferencesCustomerServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreMarketingPreferencesCustomerServiceV1() {
        super(STOREMARKETINGPREFERENCESCUSTOMERSERVICEV1_WSDL_LOCATION, new QName("http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/wsdl", "StoreMarketingPreferencesCustomerService-v1"));
    }

    /**
     * 
     * @return
     *     returns StoreMarketingPreferencesCustomerV1
     */
    @WebEndpoint(name = "StoreMarketingPreferencesCustomer-v1-soap11http")
    public StoreMarketingPreferencesCustomerV1 getStoreMarketingPreferencesCustomerV1Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/wsdl", "StoreMarketingPreferencesCustomer-v1-soap11http"), StoreMarketingPreferencesCustomerV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreMarketingPreferencesCustomerV1
     */
    @WebEndpoint(name = "StoreMarketingPreferencesCustomer-v1-soap11http")
    public StoreMarketingPreferencesCustomerV1 getStoreMarketingPreferencesCustomerV1Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/marketingdata/StoreMarketingPreferencesCustomer-v1/wsdl", "StoreMarketingPreferencesCustomer-v1-soap11http"), StoreMarketingPreferencesCustomerV1.class, features);
    }

}
