DROP TABLE CI_BAMBOO_DOCKER_IMAGES;
DROP SEQUENCE SEQ_CI_BAMBOO_DOCKER_IMAGES;

CREATE SEQUENCE SEQ_CI_BAMBOO_DOCKER_IMAGES START WITH 1 INCREMENT BY 1;

CREATE TABLE CI_BAMBOO_DOCKER_IMAGES
(
  ID        NUMBER(19) not null,
  REPOSITORY VARCHAR2(255) not null,
  TAG VARCHAR2(255) not null,
  INSERT_AT   TIMESTAMP not null,
  DELETE_AT   TIMESTAMP,
  CONSTRAINT CI_BAMBOO_DOCKER_IMAGES_PK PRIMARY KEY (ID),
  CONSTRAINT UNIQ_TAG_REPOSITORY UNIQUE (TAG, REPOSITORY)
) ;