
package com.afklm.repindpp.paymentpreference.delete;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DeletePaymentPreferencesService-v1", targetNamespace = "http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_DeletePaymentPreferences-v1.wsdl")
public class DeletePaymentPreferencesServiceV1
    extends Service
{

    private final static URL DELETEPAYMENTPREFERENCESSERVICEV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(DeletePaymentPreferencesServiceV1.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = DeletePaymentPreferencesServiceV1.class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_DeletePaymentPreferences-v1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_DeletePaymentPreferences-v1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DELETEPAYMENTPREFERENCESSERVICEV1_WSDL_LOCATION = url;
    }

    public DeletePaymentPreferencesServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeletePaymentPreferencesServiceV1() {
        super(DELETEPAYMENTPREFERENCESSERVICEV1_WSDL_LOCATION, new QName("http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/wsdl", "DeletePaymentPreferencesService-v1"));
    }

    /**
     * 
     * @return
     *     returns DeletePaymentPreferencesV1
     */
    @WebEndpoint(name = "DeletePaymentPreferences-v1-soap11http")
    public DeletePaymentPreferencesV1 getDeletePaymentPreferencesV1Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/wsdl", "DeletePaymentPreferences-v1-soap11http"), DeletePaymentPreferencesV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeletePaymentPreferencesV1
     */
    @WebEndpoint(name = "DeletePaymentPreferences-v1-soap11http")
    public DeletePaymentPreferencesV1 getDeletePaymentPreferencesV1Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/wsdl", "DeletePaymentPreferences-v1-soap11http"), DeletePaymentPreferencesV1.class, features);
    }

}
