
package com.afklm.repindpp.paymentpreference.delete;

import com.afklm.soa.common.faults.SystemFault;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SystemFault", targetNamespace = "http://www.af-klm.com/services/common/SystemFault-v1/xsd")
public class SystemException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SystemException(String message, SystemFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public SystemException(String message, SystemFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.afklm.soa.common.faults.SystemFault
     */
    public SystemFault getFaultInfo() {
        return faultInfo;
    }

}
