package com.afklm.repindmsv.tribe.model.error;

import com.afklm.repind.common.model.error.IErrorMessage;
import lombok.Getter;

public enum ErrorMessage implements IErrorMessage {

    ERROR_MESSAGE_400_000("business.400.000" , "Missing Request Parameter"),
    ERROR_MESSAGE_400_001("business.400.001" , "Gin is mandatory"),
    ERROR_MESSAGE_400_002("business.400.002" , "Name is mandatory"),
    ERROR_MESSAGE_400_003("business.400.003" , "Type is mandatory"),
    ERROR_MESSAGE_400_004("business.400.004" , "Manager is mandatory"),
    ERROR_MESSAGE_400_005("business.400.005" , "Application is mandatory"),
    ERROR_MESSAGE_400_006("business.400.006", "tribeId is mandatory"),
    ERROR_MESSAGE_400_007("business.400.007", "status is mandatory"),

    ERROR_MESSAGE_404_002("business.404.002", "Tribe not found"),
    ERROR_MESSAGE_404_003("business.404.003", "Member not found"),

    ERROR_MESSAGE_412_001("business.412.001", "Mismatch type parameter"),
    ERROR_MESSAGE_412_002("business.412.002", "Invalid value for the 'gin' parameter, length must be equal to 12"),
    ERROR_MESSAGE_412_008("business.412.008", "Invalid value for the 'status'"),
    ERROR_MESSAGE_412_018("business.412.018", "Invalid id"),
    ERROR_MESSAGE_412_000("business.412", "Business constraint violation"),

    API_BUSINESS_ERROR("business.1000","Business error generated by backend"),


    ERROR_MESSAGE_SYSTEM_001("api.error.system.001" , "Internal server error"),
    ERROR_MESSAGE_SYSTEM_002("api.error.system.002" , "No exposed resource for this URI"),
    ERROR_MESSAGE_SYSTEM_003("api.error.system.003" , "Handle No Such Request Handling Method"),
    ERROR_MESSAGE_SYSTEM_004("api.error.system.004" , "Unsupported content type"),
    ERROR_MESSAGE_SYSTEM_005("api.error.system.005" , "Message not readable"),
    ERROR_MESSAGE_SYSTEM_006("api.error.system.006" , "System fault from webservice"),
    ERROR_MESSAGE_SYSTEM_007("api.error.system.007" , "System unknown error"),
    ERROR_MESSAGE_SYSTEM_008("api.error.system.008" , "Unexpected error");


    @Getter private String description;
    @Getter private String code;

    ErrorMessage(String code , String description) {
        this.code = code;
        this.description = description;
    }
}
