
package com.afklm.repind.ws.provideindividualdata.v07;

import com.afklm.repind.ws.provideindividualdata.v07.data.ProvideIndividualInformationRequest;
import com.afklm.repind.ws.provideindividualdata.v07.data.ProvideIndividualInformationResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProvideIndividualDataService-v7", targetNamespace = "http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.repind.ws.provideindividualdata.v07.data.response.ObjectFactory.class,
    com.afklm.soa.common.faults.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.siccommontype.siccommontype.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.prospecttype.prospectdatatype.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.v07.data.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.softcomputingtype.softcomputingtype.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.siccommontype.siccommonenum.ObjectFactory.class,
    com.afklm.repind.ws.provideindividualdata.individutype.sicindividutype.ObjectFactory.class
})
public interface ProvideIndividualDataServiceV7 {


    /**
     * Get all datas.
     * 
     * @param provideIndividualInformationRequest
     * @return
     *     returns com.afklm.sic.ws.provideindividualdata.v07.data.ProvideIndividualInformationResponse
     * @throws BusinessErrorBlocBusinessException
     * @throws SystemException
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/provideIndividualDataByIdentifier")
    @WebResult(name = "ProvideIndividualInformationResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/data-v7/xsd", partName = "provideIndividualInformationResponse")
    public ProvideIndividualInformationResponse provideIndividualDataByIdentifier(
        @WebParam(name = "ProvideIndividualInformationRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/data-v7/xsd", partName = "provideIndividualInformationRequest")
        ProvideIndividualInformationRequest provideIndividualInformationRequest)
        throws BusinessErrorBlocBusinessException, SystemException
    ;

}
