
package com.afklm.repind.ws.provideindividualdata.v07;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProvideIndividualDataServiceService-v7", targetNamespace = "http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_ProvideIndividualDataService-v7.wsdl")
public class ProvideIndividualDataServiceServiceV7
    extends Service
{

    private final static URL PROVIDEINDIVIDUALDATASERVICESERVICEV7_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.afklm.repind.ws.provideindividualdata.v07.ProvideIndividualDataServiceServiceV7 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.afklm.repind.ws.provideindividualdata.v07.ProvideIndividualDataServiceServiceV7 .class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_ProvideIndividualDataService-v7.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_ProvideIndividualDataService-v7.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROVIDEINDIVIDUALDATASERVICESERVICEV7_WSDL_LOCATION = url;
    }

    public ProvideIndividualDataServiceServiceV7(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvideIndividualDataServiceServiceV7() {
        super(PROVIDEINDIVIDUALDATASERVICESERVICEV7_WSDL_LOCATION, new QName("http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/wsdl", "ProvideIndividualDataServiceService-v7"));
    }

    /**
     * 
     * @return
     *     returns ProvideIndividualDataServiceV7
     */
    @WebEndpoint(name = "ProvideIndividualDataService-v7-soap11http")
    public ProvideIndividualDataServiceV7 getProvideIndividualDataServiceV7Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/wsdl", "ProvideIndividualDataService-v7-soap11http"), ProvideIndividualDataServiceV7.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvideIndividualDataServiceV7
     */
    @WebEndpoint(name = "ProvideIndividualDataService-v7-soap11http")
    public ProvideIndividualDataServiceV7 getProvideIndividualDataServiceV7Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/ProvideIndividualDataService-v7/wsdl", "ProvideIndividualDataService-v7-soap11http"), ProvideIndividualDataServiceV7.class, features);
    }

}
