
package com.afklm.repindpp.paymentpreference.delete;

import com.afklm.repindpp.paymentpreference.delete.deletepaymentpreferencesschema.DeletePaymentPreferencesRequest;
import com.afklm.repindpp.paymentpreference.delete.deletepaymentpreferencesschema.DeletePaymentPreferencesResponse;
import com.afklm.repindpp.paymentpreference.delete.deletepaymentpreferencesschema.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeletePaymentPreferences-v1", targetNamespace = "http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.soa.common.faults.ObjectFactory.class,
    ObjectFactory.class
})
public interface DeletePaymentPreferencesV1 {


    /**
     * 
     * @param request
     * @return
     *     returns com.afklm.repindpp.paymentpreference.delete.deletepaymentpreferencesschema.DeletePaymentPreferencesResponse
     * @throws SystemException
     * @throws BusinessException
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/DeletePaymentPreferences-v1/deletePaymentPreferences")
    @WebResult(name = "DeletePaymentPreferencesResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/DeletePaymentPreferencesSchema-v1/xsd", partName = "Response")
    public DeletePaymentPreferencesResponse deletePaymentPreferences(
        @WebParam(name = "DeletePaymentPreferencesRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/DeletePaymentPreferencesSchema-v1/xsd", partName = "Request")
        DeletePaymentPreferencesRequest request)
        throws BusinessException, SystemException
    ;

}
