/* delete permissions if exists*/
delete from SIC2.REF_PERMISSIONS where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_PERMISSIONS_QUESTION_ID = 10000001;
delete from SIC2.REF_PERMISSIONS_QUESTION where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK'  and REF_PERMISSIONS_QUESTION_ID = 10000001;
COMMIT;
