/* Delete all datas created by ROBOTFRAMEWORK */
delete from SIC2.REF_PRODUCT_COMPREF_GROUP where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_COMPREF_GROUP_INFO_ID > 30000000 and REF_COMPREF_GROUP_INFO_ID < 30000003 ;
delete from SIC2.REF_PRODUCT_OWNER where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and PRODUCTID > 10000000 and PRODUCTID < 10000020  ;
delete from SIC2.REF_COMPREF_GROUP where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_COMPREF_GROUP_INFO_ID > 30000000 and REF_COMPREF_GROUP_INFO_ID < 30000003;
delete from SIC2.REF_PRODUCT where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and PRODUCTID > 10000000 and PRODUCTID < 10000020;
delete from SIC2.REF_COMPREF_GROUP_INFO where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_COMPREF_GROUP_INFO_ID > 30000000 and REF_COMPREF_GROUP_INFO_ID < 30000003;
commit;

/* Create some REF_COMPREF_GROUP for test */
insert into SIC2.REF_COMPREF_GROUP_INFO values (30000001, 'GROUP_TEST_MA', 'Group Test MA: Y/Y', 'Group Test MA: Y/Y', 'Y', 'Y', SYSDATE, 'QVI', 'ROBOTFRAMEWORK', SYSDATE, 'QVI', 'ROBOTFRAMEWORK');
commit;

/* Associate REF_PRODUCT to REF_COMPREF_GROUP */
insert into SIC2.REF_PRODUCT_COMPREF_GROUP values (14, 30000001, SYSDATE, 'QVI', 'ROBOTFRAMEWORK', SYSDATE, 'QVI', 'ROBOTFRAMEWORK');
commit;

/* Associate COM_PREF to REF_COMPREF_GROUP*/
insert into SIC2.REF_COMPREF_GROUP values (30000001, (select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'S' AND GROUP_TYPE = 'N' AND TYPE = 'AF'), SYSDATE, 'QVI', 'ROBOTFRAMEWORK', SYSDATE, 'QVI', 'ROBOTFRAMEWORK');
commit;