/* delete permissions if exists*/
delete from SIC2.REF_PERMISSIONS where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_PERMISSIONS_QUESTION_ID = 10000001;
delete from SIC2.REF_PERMISSIONS_QUESTION where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK'  and REF_PERMISSIONS_QUESTION_ID = 10000001;
COMMIT;
/* les permissions */
Insert into SIC2.REF_PERMISSIONS_QUESTION (REF_PERMISSIONS_QUESTION_ID,SNAME,SQUESTION,SQUESTION_EN,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,'P1','P1 for test','P1 for test',SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
COMMIT;
/* l association des com pref aux  permissions */ 
Insert into SIC2.REF_PERMISSIONS (REF_PERMISSIONS_QUESTION_ID,REF_COMPREF_DGT_ID,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,(select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'F' AND GROUP_TYPE = 'N' AND TYPE = 'FB_ESS'),SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
Insert into SIC2.REF_PERMISSIONS (REF_PERMISSIONS_QUESTION_ID,REF_COMPREF_DGT_ID,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,(select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'F' AND GROUP_TYPE = 'N' AND TYPE = 'FB_PART'),SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
Insert into SIC2.REF_PERMISSIONS (REF_PERMISSIONS_QUESTION_ID,REF_COMPREF_DGT_ID,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,(select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'F' AND GROUP_TYPE = 'N' AND TYPE = 'FB_CC'),SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
Insert into SIC2.REF_PERMISSIONS (REF_PERMISSIONS_QUESTION_ID,REF_COMPREF_DGT_ID,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,(select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'F' AND GROUP_TYPE = 'N' AND TYPE = 'FB_NEWS'),SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
Insert into SIC2.REF_PERMISSIONS (REF_PERMISSIONS_QUESTION_ID,REF_COMPREF_DGT_ID,DDATE_CREATION,SSITE_CREATION,SSIGNATURE_CREATION,DDATE_MODIFICATION,SSITE_MODIFICATION,SSIGNATURE_MODIFICATION) values (10000001,(select REF_COMPREF_DGT_ID from sic2.REF_COMPREF_DGT where DOMAIN = 'F' AND GROUP_TYPE = 'N' AND TYPE = 'FB_PROG'),SYSDATE,'QVI','ROBOTFRAMEWORK',SYSDATE,'QVI','ROBOTFRAMEWORK');
COMMIT;
