/* delete permissions if exists*/
delete from SIC2.REF_PERMISSIONS where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_PERMISSIONS_QUESTION_ID > 10000000 and REF_PERMISSIONS_QUESTION_ID < 10000011;
delete from SIC2.REF_PERMISSIONS_QUESTION where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK'  and REF_PERMISSIONS_QUESTION_ID > 10000000 and REF_PERMISSIONS_QUESTION_ID < 10000011;
delete from SIC2.REF_COMPREF_DGT where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and REF_COMPREF_DGT_ID > 10000009 and REF_COMPREF_DGT_ID < 10000015;
delete from SIC2.REF_COMPREF_GTYPE where SSIGNATURE_MODIFICATION = 'ROBOTFRAMEWORK' and SCODE_GTYPE in ('A', 'X' );
COMMIT;
