spring:
  config:
    activate:
      on-profile: UTE,cae
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_CAE.WORLD
    url_pp: jdbc:oracle:thin:@REPIND_PP_CAE.WORLD
    maxPoolSize: 1

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

server:
  servlet:
    context-path: /api-mgr/delete-my-account/


apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000249
  whitelist: /actuator/health
