spring:
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@OSMN305.WORLD
    url_pp: jdbc:oracle:thin:@OSMN305_PP.WORLD
    maxPoolSize: 2

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

server:
  servlet:
    context-path: /api-mgr/delete-my-account/

apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000249
  whitelist: /actuator/health
