package com.airfrance.repindutf8.entity;

import javax.persistence.*;

/**
 * RefErreur generated by hbm2java
 */
@Entity
@Table(name = "REF_ERREUR", schema = "SIC_UTF8", uniqueConstraints = @UniqueConstraint(columnNames = "SCODE"))
public class RefErreur implements java.io.Serializable {

	private long refErreurId;
	private String slibelle;
	private String slibelleEn;
	private String scode;

	public RefErreur() {
	}

	public RefErreur(long refErreurId, String slibelle, String slibelleEn, String scode) {
		this.refErreurId = refErreurId;
		this.slibelle = slibelle;
		this.slibelleEn = slibelleEn;
		this.scode = scode;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_REF_ERREUR")
    @SequenceGenerator(name="SEQ_REF_ERREUR", sequenceName = "SEQ_REF_ERREUR", allocationSize = 1)
	@Column(name = "REF_ERREUR_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getRefErreurId() {
		return this.refErreurId;
	}

	public void setRefErreurId(long refErreurId) {
		this.refErreurId = refErreurId;
	}

	@Column(name = "SLIBELLE", nullable = false, length = 70)
	public String getSlibelle() {
		return this.slibelle;
	}

	public void setSlibelle(String slibelle) {
		this.slibelle = slibelle;
	}

	@Column(name = "SLIBELLE_EN", nullable = false, length = 70)
	public String getSlibelleEn() {
		return this.slibelleEn;
	}

	public void setSlibelleEn(String slibelleEn) {
		this.slibelleEn = slibelleEn;
	}

	@Column(name = "SCODE", unique = true, nullable = false, length = 3)
	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

}
