package com.airfrance.repindutf8.entity;

import javax.persistence.*;

/**
 * RefUtfKeyType generated by hbm2java
 */
@Entity
@Table(name = "REF_UTF_KEY_TYPE", schema = "SIC_UTF8")
public class RefUtfKeyType implements java.io.Serializable {

	private RefUtfKeyTypeId id;

	public RefUtfKeyType() {
	}

	public RefUtfKeyType(RefUtfKeyTypeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "skey", column = @Column(name = "SKEY", nullable = false, length = 50)),
			@AttributeOverride(name = "stype", column = @Column(name = "STYPE", nullable = false, length = 3)) })
	public RefUtfKeyTypeId getId() {
		return this.id;
	}

	public void setId(RefUtfKeyTypeId id) {
		this.id = id;
	}

}
