package com.airfrance.repindutf8.entity;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * RefUtfType generated by hbm2java
 */
@Entity
@Table(name = "REF_UTF_TYPE", schema = "SIC_UTF8")
public class RefUtfType implements java.io.Serializable {

	private String scode;
	private String slibelleFr;
	private String slibelleEn;
	private Long maxOccurrences;
	private Set<Utf> utfs = new HashSet<Utf>(0);
	private Set<RefUtfDataKey> refUtfDataKeys = new HashSet<RefUtfDataKey>(0);

	public RefUtfType() {
	}

	public RefUtfType(String scode) {
		this.scode = scode;
	}

	public RefUtfType(String scode, String slibelleFr, String slibelleEn, Long maxOccurrences, Set<Utf> utfs,
			Set<RefUtfDataKey> refUtfDataKeys) {
		this.scode = scode;
		this.slibelleFr = slibelleFr;
		this.slibelleEn = slibelleEn;
		this.maxOccurrences = maxOccurrences;
		this.utfs = utfs;
		this.refUtfDataKeys = refUtfDataKeys;
	}

	@Id

	@Column(name = "SCODE", unique = true, nullable = false, length = 3)
	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	@Column(name = "SLIBELLE_FR", length = 25)
	public String getSlibelleFr() {
		return this.slibelleFr;
	}

	public void setSlibelleFr(String slibelleFr) {
		this.slibelleFr = slibelleFr;
	}

	@Column(name = "SLIBELLE_EN", length = 25)
	public String getSlibelleEn() {
		return this.slibelleEn;
	}

	public void setSlibelleEn(String slibelleEn) {
		this.slibelleEn = slibelleEn;
	}

	@Column(name = "MAX_OCCURRENCES", precision = 12, scale = 0)
	public Long getMaxOccurrences() {
		return this.maxOccurrences;
	}

	public void setMaxOccurrences(Long maxOccurrences) {
		this.maxOccurrences = maxOccurrences;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refUtfType")
	public Set<Utf> getUtfs() {
		return this.utfs;
	}

	public void setUtfs(Set<Utf> utfs) {
		this.utfs = utfs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "REF_UTF_KEY_TYPE", schema = "SIC_UTF8", joinColumns = {
			@JoinColumn(name = "STYPE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "SKEY", nullable = false, updatable = false) })
	public Set<RefUtfDataKey> getRefUtfDataKeys() {
		return this.refUtfDataKeys;
	}

	public void setRefUtfDataKeys(Set<RefUtfDataKey> refUtfDataKeys) {
		this.refUtfDataKeys = refUtfDataKeys;
	}

}
