package com.airfrance.repindutf8.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RefUtfKeyTypeId generated by hbm2java
 */
@Embeddable
public class RefUtfKeyTypeId implements java.io.Serializable {

	private String skey;
	private String stype;

	public RefUtfKeyTypeId() {
	}

	public RefUtfKeyTypeId(String skey, String stype) {
		this.skey = skey;
		this.stype = stype;
	}

	@Column(name = "SKEY", nullable = false, length = 50)
	public String getSkey() {
		return this.skey;
	}

	public void setSkey(String skey) {
		this.skey = skey;
	}

	@Column(name = "STYPE", nullable = false, length = 3)
	public String getStype() {
		return this.stype;
	}

	public void setStype(String stype) {
		this.stype = stype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RefUtfKeyTypeId))
			return false;
		RefUtfKeyTypeId castOther = (RefUtfKeyTypeId) other;

		return ((this.getSkey() == castOther.getSkey()) || (this.getSkey() != null && castOther.getSkey() != null
				&& this.getSkey().equals(castOther.getSkey())))
				&& ((this.getStype() == castOther.getStype()) || (this.getStype() != null
						&& castOther.getStype() != null && this.getStype().equals(castOther.getStype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSkey() == null ? 0 : this.getSkey().hashCode());
		result = 37 * result + (getStype() == null ? 0 : this.getStype().hashCode());
		return result;
	}

}
