package com.airfrance.repindutf8.entity;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * RefUtfDataKey generated by hbm2java
 */
@Entity
@Table(name = "REF_UTF_DATA_KEY", schema = "SIC_UTF8")
public class RefUtfDataKey implements java.io.Serializable {

	private String scode;
	private String slibelleFr;
	private String slibelleEn;
	private Set<RefUtfType> refUtfTypes = new HashSet<RefUtfType>(0);
	private Set<UtfData> utfDatas = new HashSet<UtfData>(0);

	public RefUtfDataKey() {
	}

	public RefUtfDataKey(String scode) {
		this.scode = scode;
	}

	public RefUtfDataKey(String scode, String slibelleFr, String slibelleEn, Set<RefUtfType> refUtfTypes,
			Set<UtfData> utfDatas) {
		this.scode = scode;
		this.slibelleFr = slibelleFr;
		this.slibelleEn = slibelleEn;
		this.refUtfTypes = refUtfTypes;
		this.utfDatas = utfDatas;
	}

	@Id

	@Column(name = "SCODE", unique = true, nullable = false, length = 50)
	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	@Column(name = "SLIBELLE_FR", length = 25)
	public String getSlibelleFr() {
		return this.slibelleFr;
	}

	public void setSlibelleFr(String slibelleFr) {
		this.slibelleFr = slibelleFr;
	}

	@Column(name = "SLIBELLE_EN", length = 25)
	public String getSlibelleEn() {
		return this.slibelleEn;
	}

	public void setSlibelleEn(String slibelleEn) {
		this.slibelleEn = slibelleEn;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "REF_UTF_KEY_TYPE", schema = "SIC_UTF8", joinColumns = {
			@JoinColumn(name = "SKEY", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "STYPE", nullable = false, updatable = false) })
	public Set<RefUtfType> getRefUtfTypes() {
		return this.refUtfTypes;
	}

	public void setRefUtfTypes(Set<RefUtfType> refUtfTypes) {
		this.refUtfTypes = refUtfTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refUtfDataKey")
	public Set<UtfData> getUtfDatas() {
		return this.utfDatas;
	}

	public void setUtfDatas(Set<UtfData> utfDatas) {
		this.utfDatas = utfDatas;
	}

}
