package com.airfrance.repindutf8.entity;

import javax.persistence.*;
import java.util.Date;

/**
 * UtfData generated by hbm2java
 */
@Entity
@Table(name = "UTF_DATA", schema = "SIC_UTF8")
public class UtfData implements java.io.Serializable {

	private long utfDataId;
	private RefUtfDataKey refUtfDataKey;
	private Utf utf;
	private String svalue;
	private Date ddateCreation;
	private String ssiteCreation;
	private String ssignatureCreation;
	private Date ddateModification;
	private String ssiteModification;
	private String ssignatureModification;

	public UtfData() {
	}

	public UtfData(long utfDataId, RefUtfDataKey refUtfDataKey, Utf utf, String svalue) {
		this.utfDataId = utfDataId;
		this.refUtfDataKey = refUtfDataKey;
		this.utf = utf;
		this.svalue = svalue;
	}

	public UtfData(long utfDataId, RefUtfDataKey refUtfDataKey, Utf utf, String svalue, Date ddateCreation,
			String ssiteCreation, String ssignatureCreation, Date ddateModification, String ssiteModification,
			String ssignatureModification) {
		this.utfDataId = utfDataId;
		this.refUtfDataKey = refUtfDataKey;
		this.utf = utf;
		this.svalue = svalue;
		this.ddateCreation = ddateCreation;
		this.ssiteCreation = ssiteCreation;
		this.ssignatureCreation = ssignatureCreation;
		this.ddateModification = ddateModification;
		this.ssiteModification = ssiteModification;
		this.ssignatureModification = ssignatureModification;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_UTF_DATA")
    @SequenceGenerator(name="SEQ_UTF_DATA", sequenceName = "SEQ_UTF_DATA",
    		allocationSize = 1)
	@Column(name = "UTF_DATA_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getUtfDataId() {
		return this.utfDataId;
	}

	public void setUtfDataId(long utfDataId) {
		this.utfDataId = utfDataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SKEY", nullable = false)
	public RefUtfDataKey getRefUtfDataKey() {
		return this.refUtfDataKey;
	}

	public void setRefUtfDataKey(RefUtfDataKey refUtfDataKey) {
		this.refUtfDataKey = refUtfDataKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UTF_ID", nullable = false)
	public Utf getUtf() {
		return this.utf;
	}

	public void setUtf(Utf utf) {
		this.utf = utf;
	}

	@Column(name = "SVALUE", nullable = false, length = 80)
	public String getSvalue() {
		return this.svalue;
	}

	public void setSvalue(String svalue) {
		this.svalue = svalue;
	}

//	@Temporal(TemporalType.DATE)
//	@Column(name = "DDATE_CREATION", length = 7)
	@Column(name = "DDATE_CREATION")
	public Date getDdateCreation() {
		return this.ddateCreation;
	}

	public void setDdateCreation(Date ddateCreation) {
		this.ddateCreation = ddateCreation;
	}

	@Column(name = "SSITE_CREATION", length = 10)
	public String getSsiteCreation() {
		return this.ssiteCreation;
	}

	public void setSsiteCreation(String ssiteCreation) {
		this.ssiteCreation = ssiteCreation;
	}

	@Column(name = "SSIGNATURE_CREATION", length = 16)
	public String getSsignatureCreation() {
		return this.ssignatureCreation;
	}

	public void setSsignatureCreation(String ssignatureCreation) {
		this.ssignatureCreation = ssignatureCreation;
	}

//	@Temporal(TemporalType.DATE)
//	@Column(name = "DDATE_MODIFICATION", length = 7)
	@Column(name = "DDATE_MODIFICATION")
	public Date getDdateModification() {
		return this.ddateModification;
	}

	public void setDdateModification(Date ddateModification) {
		this.ddateModification = ddateModification;
	}

	@Column(name = "SSITE_MODIFICATION", length = 10)
	public String getSsiteModification() {
		return this.ssiteModification;
	}

	public void setSsiteModification(String ssiteModification) {
		this.ssiteModification = ssiteModification;
	}

	@Column(name = "SSIGNATURE_MODIFICATION", length = 16)
	public String getSsignatureModification() {
		return this.ssignatureModification;
	}

	public void setSsignatureModification(String ssignatureModification) {
		this.ssignatureModification = ssignatureModification;
	}

}
