
package com.afklm.repind.ws.w000443;

import com.afklm.repind.ws.w000443.data.schema591279.BusinessError;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BusinessErrorElement", targetNamespace = "http://www.af-klm.com/services/passenger/UpdateMyAccountCustomerType-v1/xsd")
public class MsgBusinessFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MsgBusinessFault(String message, BusinessError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public MsgBusinessFault(String message, BusinessError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.afklm.repind.ws.w000443.data.schema591279.BusinessError
     */
    public BusinessError getFaultInfo() {
        return faultInfo;
    }

}
