
package com.afklm.repind.ws.w000443;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UpdateMyAccountCustomerServiceService-v3", targetNamespace = "http://www.af-klm.com/services/passenger/UpdateMyAccountCustomerService-v3/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_UpdateMyAccountCustomerData-v03.wsdl")
public class UpdateMyAccountCustomerServiceServiceV3
    extends Service
{

    private final static URL UPDATEMYACCOUNTCUSTOMERSERVICESERVICEV3_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.afklm.repind.ws.w000443.UpdateMyAccountCustomerServiceServiceV3 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.afklm.repind.ws.w000443.UpdateMyAccountCustomerServiceServiceV3 .class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_UpdateMyAccountCustomerData-v03.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_UpdateMyAccountCustomerData-v03.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UPDATEMYACCOUNTCUSTOMERSERVICESERVICEV3_WSDL_LOCATION = url;
    }

    public UpdateMyAccountCustomerServiceServiceV3(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateMyAccountCustomerServiceServiceV3() {
        super(UPDATEMYACCOUNTCUSTOMERSERVICESERVICEV3_WSDL_LOCATION, new QName("http://www.af-klm.com/services/passenger/UpdateMyAccountCustomerService-v3/wsdl", "UpdateMyAccountCustomerServiceService-v3"));
    }

    /**
     * 
     * @return
     *     returns UpdateMyAccountCustomerServiceV3
     */
    @WebEndpoint(name = "UpdateMyAccountCustomerService-v3-soap11http")
    public UpdateMyAccountCustomerServiceV3 getUpdateMyAccountCustomerServiceV3Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/UpdateMyAccountCustomerService-v3/wsdl", "UpdateMyAccountCustomerService-v3-soap11http"), UpdateMyAccountCustomerServiceV3.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateMyAccountCustomerServiceV3
     */
    @WebEndpoint(name = "UpdateMyAccountCustomerService-v3-soap11http")
    public UpdateMyAccountCustomerServiceV3 getUpdateMyAccountCustomerServiceV3Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/UpdateMyAccountCustomerService-v3/wsdl", "UpdateMyAccountCustomerService-v3-soap11http"), UpdateMyAccountCustomerServiceV3.class, features);
    }

}
