apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-individual
  labels:
    app.kubernetes.io/name: search-individual
    app.kubernetes.io/instance: search-individual
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: search-individual
      app.kubernetes.io/instance: search-individual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: search-individual
        app.kubernetes.io/instance: search-individual
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: search-individual
                    app.kubernetes.io/instance: search-individual
      terminationGracePeriodSeconds: 30    # should be longer than needed to stop the containers
      containers:
        - name: search-individual
          image: harbor-vlb.af-klm.com/cdm/search-individual
          securityContext:
              runAsNonRoot: true
              runAsUser: 888
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /infra/healthcheck
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: repind-keytab
              mountPath: "/etc/kafka"
              readOnly: true
      volumes:
        - name: repind-keytab
          secret:
            secretName: repind-keytab
