apiVersion: v1
kind: Service
metadata:
  name: search-individual
  labels:
    app.kubernetes.io/name: search-individual
    app.kubernetes.io/instance: search-individual
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: search-individual
    app.kubernetes.io/instance: search-individual