server:
  servlet:
    context-path: /api-mgr

spring:
  neo4j:
    uri: bolt://neo4j-tribes-db-prd:7687
    authentication:
      username: ${ri_repind_neo4j_username}
      password: ${ri_repind_neo4j_password}
data:
  neo4j:
    database: tribes