spring:
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_ITE.WORLD
  wsdl:
    address:
      w002122-v01: https://ws-qvi-dev.airfrance.fr/passenger/marketing/002122v01
      w001274-v01: https://ws-qvi-dev.airfrance.fr/passenger/distribmgmt/001274v01
      w001588-v01: https://ws-qvi-dev.airfrance.fr/passenger/marketing/001588v01
    location:
      w002122-v01: classpath:/META-INF/wsdl/w002122-v01/w002122-v01-policy.wsdl
      w001274-v01: classpath:/META-INF/wsdl/w001274-v01/w001274-v01-policy.wsdl
      w001588-v01: classpath:/META-INF/wsdl/w001588-v010001/w001588-v010001-policy.wsdl

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

sdfw:
  ws:
    - id: w002122.v1
      url: https://ws-qvi-dev.airfrance.fr/passenger/marketing/002122v01
    - id: w001588.v1
      url: https://ws-qvi-dev.airfrance.fr/passenger/marketing/001588v01
