package com.airfrance.repind.entity.refTable;

public class RefTableREF_MONNAIE extends RefTableMere {


	private static RefTableREF_MONNAIE m_RefTableREF_MONNAIE = null;

	public static final String _REF_AED = "AED";
	public static final String _REF_AFA = "AFA";
	public static final String _REF_ALL = "ALL";
	public static final String _REF_AMD = "AMD";
	public static final String _REF_ANG = "ANG";
	public static final String _REF_AOA = "AOA";
	public static final String _REF_AON = "AON";
	public static final String _REF_AOR = "AOR";
	public static final String _REF_ARA = "ARA";
	public static final String _REF_ARS = "ARS";
	public static final String _REF_ATS = "ATS";
	public static final String _REF_AUD = "AUD";
	public static final String _REF_AWG = "AWG";
	public static final String _REF_AZM = "AZM";
	public static final String _REF_BAM = "BAM";
	public static final String _REF_BBD = "BBD";
	public static final String _REF_BDT = "BDT";
	public static final String _REF_BEF = "BEF";
	public static final String _REF_BGL = "BGL";
	public static final String _REF_BGN = "BGN";
	public static final String _REF_BHD = "BHD";
	public static final String _REF_BIF = "BIF";
	public static final String _REF_BMD = "BMD";
	public static final String _REF_BND = "BND";
	public static final String _REF_BOB = "BOB";
	public static final String _REF_BRC = "BRC";
	public static final String _REF_BRL = "BRL";
	public static final String _REF_BRR = "BRR";
	public static final String _REF_BSD = "BSD";
	public static final String _REF_BTN = "BTN";
	public static final String _REF_BWP = "BWP";
	public static final String _REF_BYB = "BYB";
	public static final String _REF_BYR = "BYR";
	public static final String _REF_BZD = "BZD";
	public static final String _REF_CAD = "CAD";
	public static final String _REF_CDF = "CDF";
	public static final String _REF_CHF = "CHF";
	public static final String _REF_CLP = "CLP";
	public static final String _REF_CNY = "CNY";
	public static final String _REF_COP = "COP";
	public static final String _REF_CRC = "CRC";
	public static final String _REF_CUP = "CUP";
	public static final String _REF_CVE = "CVE";
	public static final String _REF_CYP = "CYP";
	public static final String _REF_CZK = "CZK";
	public static final String _REF_DEM = "DEM";
	public static final String _REF_DJF = "DJF";
	public static final String _REF_DKK = "DKK";
	public static final String _REF_DOP = "DOP";
	public static final String _REF_DZD = "DZD";
	public static final String _REF_ECS = "ECS";
	public static final String _REF_EEK = "EEK";
	public static final String _REF_EGP = "EGP";
	public static final String _REF_ERN = "ERN";
	public static final String _REF_ESP = "ESP";
	public static final String _REF_ETB = "ETB";
	public static final String _REF_EUR = "EUR";
	public static final String _REF_FIM = "FIM";
	public static final String _REF_FJD = "FJD";
	public static final String _REF_FKP = "FKP";
	public static final String _REF_FRF = "FRF";
	public static final String _REF_FRS = "FRS";
	public static final String _REF_GBP = "GBP";
	public static final String _REF_GEL = "GEL";
	public static final String _REF_GHC = "GHC";
	public static final String _REF_GIP = "GIP";
	public static final String _REF_GMD = "GMD";
	public static final String _REF_GNF = "GNF";
	public static final String _REF_GRD = "GRD";
	public static final String _REF_GTQ = "GTQ";
	public static final String _REF_GWP = "GWP";
	public static final String _REF_GYD = "GYD";
	public static final String _REF_HKD = "HKD";
	public static final String _REF_HNL = "HNL";
	public static final String _REF_HRD = "HRD";
	public static final String _REF_HRK = "HRK";
	public static final String _REF_HTG = "HTG";
	public static final String _REF_HUF = "HUF";
	public static final String _REF_IDR = "IDR";
	public static final String _REF_IEP = "IEP";
	public static final String _REF_ILS = "ILS";
	public static final String _REF_INR = "INR";
	public static final String _REF_IQD = "IQD";
	public static final String _REF_IRR = "IRR";
	public static final String _REF_ISK = "ISK";
	public static final String _REF_ITL = "ITL";
	public static final String _REF_JMD = "JMD";
	public static final String _REF_JOD = "JOD";
	public static final String _REF_JPY = "JPY";
	public static final String _REF_KES = "KES";
	public static final String _REF_KGS = "KGS";
	public static final String _REF_KHR = "KHR";
	public static final String _REF_KMF = "KMF";
	public static final String _REF_KPW = "KPW";
	public static final String _REF_KRW = "KRW";
	public static final String _REF_KWD = "KWD";
	public static final String _REF_KYD = "KYD";
	public static final String _REF_KZT = "KZT";
	public static final String _REF_LAK = "LAK";
	public static final String _REF_LBP = "LBP";
	public static final String _REF_LKR = "LKR";
	public static final String _REF_LRD = "LRD";
	public static final String _REF_LSL = "LSL";
	public static final String _REF_LTL = "LTL";
	public static final String _REF_LUF = "LUF";
	public static final String _REF_LVL = "LVL";
	public static final String _REF_LYD = "LYD";
	public static final String _REF_MAD = "MAD";
	public static final String _REF_MDL = "MDL";
	public static final String _REF_MGA = "MGA";
	public static final String _REF_MGF = "MGF";
	public static final String _REF_MKD = "MKD";
	public static final String _REF_MMK = "MMK";
	public static final String _REF_MNT = "MNT";
	public static final String _REF_MOP = "MOP";
	public static final String _REF_MRU = "MRU";
	public static final String _REF_MTL = "MTL";
	public static final String _REF_MUR = "MUR";
	public static final String _REF_MVR = "MVR";
	public static final String _REF_MWK = "MWK";
	public static final String _REF_MXN = "MXN";
	public static final String _REF_MYR = "MYR";
	public static final String _REF_MZM = "MZM";
	public static final String _REF_MZN = "MZN";
	public static final String _REF_NAD = "NAD";
	public static final String _REF_NGN = "NGN";
	public static final String _REF_NIO = "NIO";
	public static final String _REF_NLG = "NLG";
	public static final String _REF_NOK = "NOK";
	public static final String _REF_NPR = "NPR";
	public static final String _REF_NUC = "NUC";
	public static final String _REF_NZD = "NZD";
	public static final String _REF_OMR = "OMR";
	public static final String _REF_PAB = "PAB";
	public static final String _REF_PEN = "PEN";
	public static final String _REF_PES = "PES";
	public static final String _REF_PGK = "PGK";
	public static final String _REF_PHP = "PHP";
	public static final String _REF_PKR = "PKR";
	public static final String _REF_PLN = "PLN";
	public static final String _REF_PLZ = "PLZ";
	public static final String _REF_PTE = "PTE";
	public static final String _REF_PYG = "PYG";
	public static final String _REF_QAR = "QAR";
	public static final String _REF_ROL = "ROL";
	public static final String _REF_RSD = "RSD";
	public static final String _REF_RUB = "RUB";
	public static final String _REF_RUR = "RUR";
	public static final String _REF_RWF = "RWF";
	public static final String _REF_SAR = "SAR";
	public static final String _REF_SBD = "SBD";
	public static final String _REF_SCR = "SCR";
	public static final String _REF_SDD = "SDD";
	public static final String _REF_SEK = "SEK";
	public static final String _REF_SGD = "SGD";
	public static final String _REF_SIT = "SIT";
	public static final String _REF_SLL = "SLL";
	public static final String _REF_SOS = "SOS";
	public static final String _REF_SRG = "SRG";
	public static final String _REF_STD = "STD";
	public static final String _REF_SVC = "SVC";
	public static final String _REF_SYP = "SYP";
	public static final String _REF_SZL = "SZL";
	public static final String _REF_THB = "THB";
	public static final String _REF_TJR = "TJR";
	public static final String _REF_TMM = "TMM";
	public static final String _REF_TND = "TND";
	public static final String _REF_TOP = "TOP";
	public static final String _REF_TPE = "TPE";
	public static final String _REF_TRY = "TRY";
	public static final String _REF_TTD = "TTD";
	public static final String _REF_TWD = "TWD";
	public static final String _REF_TZS = "TZS";
	public static final String _REF_UAH = "UAH";
	public static final String _REF_UAK = "UAK";
	public static final String _REF_UGX = "UGX";
	public static final String _REF_USD = "USD";
	public static final String _REF_UYU = "UYU";
	public static final String _REF_UZS = "UZS";
	public static final String _REF_VEB = "VEB";
	public static final String _REF_VEF = "VEF";
	public static final String _REF_VND = "VND";
	public static final String _REF_VUV = "VUV";
	public static final String _REF_WMP = "WMP";
	public static final String _REF_WST = "WST";
	public static final String _REF_XAF = "XAF";
	public static final String _REF_XCD = "XCD";
	public static final String _REF_XDR = "XDR";
	public static final String _REF_XFA = "XFA";
	public static final String _REF_XOF = "XOF";
	public static final String _REF_XPF = "XPF";
	public static final String _REF_YDD = "YDD";
	public static final String _REF_YER = "YER";
	public static final String _REF_YUG = "YUG";
	public static final String _REF_YUM = "YUM";
	public static final String _REF_YUX = "YUX";
	public static final String _REF_ZAR = "ZAR";
	public static final String _REF_ZMK = "ZMK";
	public static final String _REF_ZRN = "ZRN";
	public static final String _REF_ZRZ = "ZRZ";
	public static final String _REF_ZWD = "ZWD";


	public static final String DIRHAM_EMIRATS = "DIRHAM/EMIRATS";
	public static final String AFGHANI_AFGHANISTAN = "AFGHANI/AFGHANISTAN";
	public static final String KWANZA = "KWANZA";
	public static final String KWANZA_REAJUSTADO = "KWANZA REAJUSTADO";
	public static final String AUSTRAL = "AUSTRAL";
	public static final String CONVERTIBLE_MARK = "CONVERTIBLE MARK";
	public static final String BULGARIAN_LEV = "BULGARIAN LEV";
	public static final String NGULTRUM_BHUTAN = "NGULTRUM/BHUTAN";
	public static final String PULA_BOTSWANA = "PULA/BOTSWANA";
	public static final String BELARUSSIAN_RUBLE = "BELARUSSIAN RUBLE";
	public static final String FRANC_SUISSE = "FRANC SUISSE";
	public static final String MAGALASY_FRANC = "MAGALASY FRANC";
	public static final String NEW_MOZAMBICAN_METICAL = "NEW MOZAMBICAN METICAL";
	public static final String PERUVIAN_NUEVO_SOL = "PERUVIAN NUEVO SOL";
	public static final String SERBIAN_DINAR = "SERBIAN DINAR";
	public static final String RUSSIAN_RUBLE = "RUSSIAN RUBLE";
	public static final String VENEZILIAN_BOLIVAR = "VENEZILIAN BOLIVAR";
	public static final String CFA_COM_AFRICAINE = "CFA / COM.AFRICAINE";
	public static final String AFRICA_COM_CFA = "AFRICA.COM / CFA";
	public static final String SERBIAN_NEW_DINAR = "SERBIAN NEW.DINAR";
	public static final String ZAIRE = "ZAIRE";



	private RefTableREF_MONNAIE() {

		m_lstChamps.add(new RefTableChamp(_REF_AED, DIRHAM_EMIRATS, DIRHAM_EMIRATS, DIRHAM_EMIRATS));
		m_lstChamps.add(new RefTableChamp(_REF_AFA, AFGHANI_AFGHANISTAN, AFGHANI_AFGHANISTAN, AFGHANI_AFGHANISTAN));
		m_lstChamps.add(new RefTableChamp(_REF_ALL, "LEK/ALBANIE", "LEK/ALBANIA", "LEK/ALBANIA"));
		m_lstChamps.add(new RefTableChamp(_REF_AMD, "DRAM ARMENIEN", "ARMENIAN DRAM", "ARMENIAN DRAM"));
		m_lstChamps.add(new RefTableChamp(_REF_ANG, "FLORIN ANT NEERLAND", "ANT NETHERLAND FLORIN", "ANT NETHERLAND FLORIN"));
		m_lstChamps.add(new RefTableChamp(_REF_AOA, KWANZA, KWANZA, KWANZA));
		m_lstChamps.add(new RefTableChamp(_REF_AON, "NOUV.KWANZA ANGOLA", "ANGOLA NEW.KWANZA", "ANGOLA NEW.KWANZA"));
		m_lstChamps.add(new RefTableChamp(_REF_AOR, KWANZA_REAJUSTADO, KWANZA_REAJUSTADO, KWANZA_REAJUSTADO));
		m_lstChamps.add(new RefTableChamp(_REF_ARA, AUSTRAL, AUSTRAL, AUSTRAL));
		m_lstChamps.add(new RefTableChamp(_REF_ARS, "PESO ARGENTIN", "ARGENTINIAN PESO", "ARGENTINIAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_ATS, "SCHILLING AUTRICHIEN", "AUSTRIAN SCHILLING", "AUSTRIAN SCHILLING"));
		m_lstChamps.add(new RefTableChamp(_REF_AUD, "DOLLAR AUSTRALIEN", "AUSTRALIAN DOLLAR", "AUSTRALIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_AWG, "FLORIN ARUBA", "ARUBA FLORIN", "ARUBA FLORIN"));
		m_lstChamps.add(new RefTableChamp(_REF_AZM, "MANAT AZERBAIJAN", "AZERBAIJANIAN MANAT", "AZERBAIJANIAN MANAT"));
		m_lstChamps.add(new RefTableChamp(_REF_BAM, CONVERTIBLE_MARK, CONVERTIBLE_MARK, CONVERTIBLE_MARK));
		m_lstChamps.add(new RefTableChamp(_REF_BBD, "DOLLAR BARBADOS", "BARBADOS DOLLAR", "BARBADOS DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BDT, "TAKA BANGLADESH", "BANGLADESH TAKA", "BANGLADESH TAKA"));
		m_lstChamps.add(new RefTableChamp(_REF_BEF, "FRANC BELGE", "BELGIAN FRANC", "BELGIAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_BGL, "LEV BULGARE", BULGARIAN_LEV, BULGARIAN_LEV));
		m_lstChamps.add(new RefTableChamp(_REF_BGN, "LEV BULGARE", BULGARIAN_LEV, BULGARIAN_LEV));
		m_lstChamps.add(new RefTableChamp(_REF_BHD, "DINAR BAHRAIN", "BAHRAIN DINAR", "BAHRAIN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BIF, "FRANC BURUNDIEN", "BURUNDIAN FRANC", "BURUNDIAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_BMD, "DOLLAR DES BERMUDES", "BERMUDA DOLLAR", "BERMUDA DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BND, "DOLLAR BRUNEI", "BRUNEI DOLLAR", "BRUNEI DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BOB, "BOLIVAR BOLIVIEN", "BOLIVIAN BOLIVAR", "BOLIVIAN BOLIVAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BRC, "CRUZEIRO BRESILIEN", "BRAZILIAN CRUZEIRO", "BRAZILIAN CRUZEIRO"));
		m_lstChamps.add(new RefTableChamp(_REF_BRL, "REAL BRESILIEN", "BRAZILIAN REAL", "BRAZILIAN REAL"));
		m_lstChamps.add(new RefTableChamp(_REF_BRR, "CRUZEIRO REAL BRESIL", "BRAZIL CRUZEIRO REAL", "BRAZIL CRUZEIRO REAL"));
		m_lstChamps.add(new RefTableChamp(_REF_BSD, "DOLLAR DES BAHAMAS", "BAHAMAS DOLLAR", "BAHAMAS DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_BTN, NGULTRUM_BHUTAN, NGULTRUM_BHUTAN, NGULTRUM_BHUTAN));
		m_lstChamps.add(new RefTableChamp(_REF_BWP, PULA_BOTSWANA, PULA_BOTSWANA, PULA_BOTSWANA));
		m_lstChamps.add(new RefTableChamp(_REF_BYB, "ROUBLE BELARISSIEN", BELARUSSIAN_RUBLE, BELARUSSIAN_RUBLE));
		m_lstChamps.add(new RefTableChamp(_REF_BYR, "ROUBLE BELLARUSSIEN", BELARUSSIAN_RUBLE, BELARUSSIAN_RUBLE));
		m_lstChamps.add(new RefTableChamp(_REF_BZD, "DOLLAR DU BELIZE", "BELIZE DOLLAR", "BELIZE DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_CAD, "DOLLAR CANADIEN", "CANADIAN DOLLAR", "CANADIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_CDF, "FRANC CONGOLAIS", "CONGOLESE FRANC", "CONGOLESE FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_CHF, FRANC_SUISSE, FRANC_SUISSE));
		m_lstChamps.add(new RefTableChamp(_REF_CLP, "PESO CHILIEN", "CHILEAN PESO", "CHILEAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_CNY, "RIN MIN BI CHINOIS", "CHINESE RIN MIN BI", "CHINESE RIN MIN BI"));
		m_lstChamps.add(new RefTableChamp(_REF_COP, "PESO COLOMBIEN", "COLOMBIAN PESO", "COLOMBIAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_CRC, "COLON COSTARICIEN", "COSTARICAN COLON", "COSTARICAN COLON"));
		m_lstChamps.add(new RefTableChamp(_REF_CUP, "PESO CUBAIN", "CUBAN PESO", "CUBAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_CVE, "ESCUDO CAP VERT", "CAPO VERDE ESCUDO", "CAPO VERDE ESCUDO"));
		m_lstChamps.add(new RefTableChamp(_REF_CYP, "LIVRE CHYPRIOTE", "CYPRIOTE POUND", "CYPRIOTE POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_CZK, "COURONNE TCHEQUE", "CZECH CROWN", "CZECH CROWN"));
		m_lstChamps.add(new RefTableChamp(_REF_DEM, "MARK ALLEMAND", "GERMAN MARK", "GERMAN MARK"));
		m_lstChamps.add(new RefTableChamp(_REF_DJF, "FRANC DE DJIBOUTI", "DJIBOUTI FRANC", "DJIBOUTI FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_DKK, "COURONNE DANOISE", "DANISH CROWM", "DANISH CROWM"));
		m_lstChamps.add(new RefTableChamp(_REF_DOP, "PESO DOMINICAIN", "DOMINICAN PESO", "DOMINICAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_DZD, "DINAR ALGERIEN", "ALGERIAN DINAR", "ALGERIAN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_ECS, "SUCRE EQUATORIEN", "ECUADORIAN SUGAR", "ECUADORIAN SUGAR"));
		m_lstChamps.add(new RefTableChamp(_REF_EEK, "COURONNE ESTONIENNE", "ESTONIAN CROWN", "ESTONIAN CROWN"));
		m_lstChamps.add(new RefTableChamp(_REF_EGP, "LIVRE EGYPTENNE", "EGYPTIAN POUND", "EGYPTIAN POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_ERN, "NAKFA/ERITHREE", "ERITHREE/NAKFA", "ERITHREE/NAKFA"));
		m_lstChamps.add(new RefTableChamp(_REF_ESP, "PESETE ESPAGNOLE", "SPANISH PESETAS", "SPANISH PESETAS"));
		m_lstChamps.add(new RefTableChamp(_REF_ETB, "BIRR ETHIOPIEN", "ETHIOPIAN BIRR", "ETHIOPIAN BIRR"));
		m_lstChamps.add(new RefTableChamp(_REF_EUR, "EURO", "EURO", "EURO"));
		m_lstChamps.add(new RefTableChamp(_REF_FIM, "MARK FINLANDAIS", "FINN. MARK", "FINN. MARK"));
		m_lstChamps.add(new RefTableChamp(_REF_FJD, "DOLLAR FIDJIEN", "FIJI ISLANDS DOLLAR", "FIJI ISLANDS DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_FKP, "LIVRE I.FALKLAND", "FALKLAND ISLANDS POUND", "FALKLAND ISLANDS POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_FRF, "FRANC FRANCAIS", "FRANC FRANCAIS"));
		m_lstChamps.add(new RefTableChamp(_REF_FRS, FRANC_SUISSE, "SWISS FRANC", "SWISS FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_GBP, "LIVRE ANGLAISE", "POUND STERLING", "POUND STERLING"));
		m_lstChamps.add(new RefTableChamp(_REF_GEL, "LARI/GEORGIE", "GEORGIA/LARI", "GEORGIA/LARI"));
		m_lstChamps.add(new RefTableChamp(_REF_GHC, "CEDI GHANEEN", "GHANAIAN CEDI", "GHANAIAN CEDI"));
		m_lstChamps.add(new RefTableChamp(_REF_GIP, "LIVRE DE GIBRALTAR", "GIBRALTAR POUND", "GIBRALTAR POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_GMD, "DALASI GAMBIEN", "GAMBIAN DALASI", "GAMBIAN DALASI"));
		m_lstChamps.add(new RefTableChamp(_REF_GNF, "FRANC GUINEEN", "GUINEAN FRANC", "GUINEAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_GRD, "DRACHME GRECQUE", "GREEK DRACHMA", "GREEK DRACHMA"));
		m_lstChamps.add(new RefTableChamp(_REF_GTQ, "QUETZAL/GUATEMALA", "GUATEMALA/QUETZAL", "GUATEMALA/QUETZAL"));
		m_lstChamps.add(new RefTableChamp(_REF_GWP, "PESO/GUINEE BISSAO", "GUINEA BISSAU/PESO", "GUINEA BISSAU/PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_GYD, "DOLLAR GUYANAIS", "GUYANESE DOLLAR", "GUYANESE DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_HKD, "DOLLAR / HONG KONG", "HONG KONG / DOLLAR", "HONG KONG / DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_HNL, "LEMPIRA / HONDURAS", "HONDURAS / LEMPIRA", "HONDURAS / LEMPIRA"));
		m_lstChamps.add(new RefTableChamp(_REF_HRD, "DINAR CROATE", "CROATIAN DINAR", "CROATIAN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_HRK, "KUNA CROATE", "CROATIAN KUNA", "CROATIAN KUNA"));
		m_lstChamps.add(new RefTableChamp(_REF_HTG, "GOURDE HAITIENNE", "HAITIAN GOURDE", "HAITIAN GOURDE"));
		m_lstChamps.add(new RefTableChamp(_REF_HUF, "FORINT HONGROIS", "HUNGARIAN FORINT", "HUNGARIAN FORINT"));
		m_lstChamps.add(new RefTableChamp(_REF_IDR, "ROUPIE INDONESIENNE", "INDONESIAN RUPEE", "INDONESIAN RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_IEP, "LIVRE IRLANDAISE", "IRISH POUND", "IRISH POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_ILS, "SHEQUEL ISRAELIEN", "ISRAELIAN SHEQUEL", "ISRAELIAN SHEQUEL"));
		m_lstChamps.add(new RefTableChamp(_REF_INR, "ROUPIE INDIENNE", "INDIAN RUPEE", "INDIAN RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_IQD, "DINAR IRAQUIEN", "IRAKIEN DINAR", "IRAKIEN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_IRR, "RIAL IRANIEN", "IRANIAN RIAL", "IRANIAN RIAL"));
		m_lstChamps.add(new RefTableChamp(_REF_ISK, "COURONNE ISLANDAISE", "ICELANDIC CROWN", "ICELANDIC CROWN"));
		m_lstChamps.add(new RefTableChamp(_REF_ITL, "LIRE ITALIENNE", "ITALIAN LIRA", "ITALIAN LIRA"));
		m_lstChamps.add(new RefTableChamp(_REF_JMD, "DOLLAR JAMAIQUAIN", "JAMAICAN DOLLAR", "JAMAICAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_JOD, "DINAR JORDANIEN", "JORDANIAN DOLLAR", "JORDANIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_JPY, "YEN JAPONNAIS", "JAPANESE YEN", "JAPANESE YEN"));
		m_lstChamps.add(new RefTableChamp(_REF_KES, "SHILLING KENYEN", "KENYAN SHILLING", "KENYAN SHILLING"));
		m_lstChamps.add(new RefTableChamp(_REF_KGS, "SOM / KYRGYZSTAN", "KYRGYZSTAN / SOM", "KYRGYZSTAN / SOM"));
		m_lstChamps.add(new RefTableChamp(_REF_KHR, "RIEL CAMBODGIEN", "CAMBODIAN RIEL", "CAMBODIAN RIEL"));
		m_lstChamps.add(new RefTableChamp(_REF_KMF, "FRANC COMORIEN", "COMORIAN FRANC", "COMORIAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_KPW, "WON NORD COREEN", "NORTH KOREAN WON", "NORTH KOREAN WON"));
		m_lstChamps.add(new RefTableChamp(_REF_KRW, "WON SUD COREEN", "SOUTH KOREAN WON", "SOUTH KOREAN WON"));
		m_lstChamps.add(new RefTableChamp(_REF_KWD, "DINAR KOWEITIEN", "KUWAIN DINAR", "KUWAIN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_KYD, "DOLLAR I. CAIMAN", "CAYMAN I. DOLLAR", "CAYMAN I. DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_KZT, "TENGE / KAZAKSTAN", "KAZAKSTAN / TENGE", "KAZAKSTAN / TENGE"));
		m_lstChamps.add(new RefTableChamp(_REF_LAK, "KIP LAOTIEN", "LAOTIAN KIP", "LAOTIAN KIP"));
		m_lstChamps.add(new RefTableChamp(_REF_LBP, "LIVRE LIBANNAISE", "LEBANESE POUND", "LEBANESE POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_LKR, "ROUPIE SRI - LANKAISE", "SRI - LANKAN RUPEE", "SRI - LANKAN RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_LRD, "DOLLAR LIBERIEN", "LIBERIAN DOLLAR", "LIBERIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_LSL, "LOTI / ROYAUME DU LESOTO", "LESOTHO KINGDOM / LOTI", "LESOTHO KINGDOM / LOTI"));
		m_lstChamps.add(new RefTableChamp(_REF_LTL, "LITAS LITHUANIEN", "LITHIANIAN LITAS", "LITHIANIAN LITAS"));
		m_lstChamps.add(new RefTableChamp(_REF_LUF, "FRANC LUXENBOURGEOIS", "LUXEMBOURG FRANC", "LUXEMBOURG FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_LVL, "LATS LATVIA / LETTONIE", "LETTONIA / LATS LATVIA", "LETTONIA / LATS LATVIA"));
		m_lstChamps.add(new RefTableChamp(_REF_LYD, "DINAR LIBYEN", "LIBYAN DINAR", "LIBYAN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_MAD, "DIRHAM MAROCAIN", "MOROCCAN DIRHAM", "MOROCCAN DIRHAM"));
		m_lstChamps.add(new RefTableChamp(_REF_MDL, "LEU MOLDAVE", "MOLDAVIAN LEU", "MOLDAVIAN LEU"));
		m_lstChamps.add(new RefTableChamp(_REF_MGA, "FRANC MALGACHE", MAGALASY_FRANC, MAGALASY_FRANC));
		m_lstChamps.add(new RefTableChamp(_REF_MGF, "FRANC MALGACHE", MAGALASY_FRANC, MAGALASY_FRANC));
		m_lstChamps.add(new RefTableChamp(_REF_MKD, "DENAR MACEDONIEN", "MACEDONIAN DENAR", "MACEDONIAN DENAR"));
		m_lstChamps.add(new RefTableChamp(_REF_MMK, "KYAT / MYANMAR", "MYANMAR / KYAT", "MYANMAR / KYAT"));
		m_lstChamps.add(new RefTableChamp(_REF_MNT, "TOUGRIK MONGOLE", "MONGOLIA TOUGRIK", "MONGOLIA TOUGRIK"));
		m_lstChamps.add(new RefTableChamp(_REF_MOP, "PATACA MACAO", "MACAO PATACA", "MACAO PATACA"));
		m_lstChamps.add(new RefTableChamp(_REF_MRU, "OUGUIYA MAURITANIEN", "MAURITANIAN OUGUIYA", "MAURITANIAN OUGUIYA"));
		m_lstChamps.add(new RefTableChamp(_REF_MTL, "LIRE MALTAISE", "MALTESE LIRA", "MALTESE LIRA"));
		m_lstChamps.add(new RefTableChamp(_REF_MUR, "ROUPIE MAURICIENNE", "MAURITIAN RUPEE", "MAURITIAN RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_MVR, "RUFIYAA DES MALDIVES", "THE MALDIVES RUFIYAA", "THE MALDIVES RUFIYAA"));
		m_lstChamps.add(new RefTableChamp(_REF_MWK, "KWACHA DU MALAWI", "MALAWI KWACHA", "MALAWI KWACHA"));
		m_lstChamps.add(new RefTableChamp(_REF_MXN, "PESO MEXICAIN", "MEXICAN PESO", "MEXICAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_MYR, "RINGGIT MALAISIEN", "MALAYSIAN RINGGIT", "MALAYSIAN RINGGIT"));
		m_lstChamps.add(new RefTableChamp(_REF_MZM, "METICAL / MOZAMBIQUE", "MOZAMBIQUE / METICAL", "MOZAMBIQUE / METICAL"));
		m_lstChamps.add(new RefTableChamp(_REF_MZN, NEW_MOZAMBICAN_METICAL, NEW_MOZAMBICAN_METICAL, NEW_MOZAMBICAN_METICAL));
		m_lstChamps.add(new RefTableChamp(_REF_NAD, "DOLLAR NAMIBIEN", "NAMIBIAN DOLLAR", "NAMIBIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_NGN, "NAIRA NIGERIEN", "NIGERIAN NAIRA", "NIGERIAN NAIRA"));
		m_lstChamps.add(new RefTableChamp(_REF_NIO, "CORDOBA ORO /  NICARAGUA", "NICARAGUA / CORDOBA ORO", "NICARAGUA / CORDOBA ORO"));
		m_lstChamps.add(new RefTableChamp(_REF_NLG, "FLORIN HOLLANDAIS", "DUTCHMAN FLORIN", "DUTCHMAN FLORIN"));
		m_lstChamps.add(new RefTableChamp(_REF_NOK, "COURONNE NORVEGIENNE", "NORVEGIAN CROWN", "NORVEGIAN CROWN"));
		m_lstChamps.add(new RefTableChamp(_REF_NPR, "ROUPIE NEPALAISE", "NEPALESE RUPEE", "NEPALESE RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_NUC, "NUC", "NUC", "NUC"));
		m_lstChamps.add(new RefTableChamp(_REF_NZD, "DOLLAR NEO ZELANDAIS", "NEW ZEALENDER DOLLAR", "NEW ZEALENDER DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_OMR, "RIAL / OMAN", "OMAN / RIAL", "OMAN / RIAL"));
		m_lstChamps.add(new RefTableChamp(_REF_PAB, "BALBOA PANAMEEN", "PANAMANIAN BALBOA", "PANAMANIAN BALBOA"));
		m_lstChamps.add(new RefTableChamp(_REF_PEN, "NUEVO SOL PERUVIEN", PERUVIAN_NUEVO_SOL, PERUVIAN_NUEVO_SOL));
		m_lstChamps.add(new RefTableChamp(_REF_PES, "NUEVO SOL PERUVIEN", PERUVIAN_NUEVO_SOL, PERUVIAN_NUEVO_SOL));
		m_lstChamps.add(new RefTableChamp(_REF_PGK, "KINA / PAPOUASIE", "PAPUA / KINA", "PAPUA / KINA"));
		m_lstChamps.add(new RefTableChamp(_REF_PHP, "PESO PHILIPPIN", "FILIPINO PESO", "FILIPINO PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_PKR, "ROUPIE PAKISTANAISE", "PAKISTANI RUPEE", "PAKISTANI RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_PLN, "ZLOTY POLONAIS", "POLISH ZLOTY", "POLISH ZLOTY"));
		m_lstChamps.add(new RefTableChamp(_REF_PLZ, "ZLOTI POLONAIS", "POLISH ZLOTI", "POLISH ZLOTI"));
		m_lstChamps.add(new RefTableChamp(_REF_PTE, "ESCUDO PORTUGAIS", "PORTUGUESE ESCUDO", "PORTUGUESE ESCUDO"));
		m_lstChamps.add(new RefTableChamp(_REF_PYG, "GUARANI PARAGUAYEN", "PARAGUAYAN GUARANI", "PARAGUAYAN GUARANI"));
		m_lstChamps.add(new RefTableChamp(_REF_QAR, "RIAL / QUATAR", "KATAR / RIAL", "KATAR / RIAL"));
		m_lstChamps.add(new RefTableChamp(_REF_ROL, "LEI ROUMAIN", "RUMANIAN LEI", "RUMANIAN LEI"));
		m_lstChamps.add(new RefTableChamp(_REF_RSD, SERBIAN_DINAR, SERBIAN_DINAR, SERBIAN_DINAR));
		m_lstChamps.add(new RefTableChamp(_REF_RUB, "ROUBLE RUSSE", RUSSIAN_RUBLE, RUSSIAN_RUBLE));
		m_lstChamps.add(new RefTableChamp(_REF_RUR, "ROUBLE RUSSE", RUSSIAN_RUBLE, RUSSIAN_RUBLE));
		m_lstChamps.add(new RefTableChamp(_REF_RWF, "FRANC RUANDAIS", "RWANDAN FRANC", "RWANDAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_SAR, "RIYAL SAOUDIEN", "SAUDI ARABIAN RIYAL", "SAUDI ARABIAN RIYAL"));
		m_lstChamps.add(new RefTableChamp(_REF_SBD, "DOLLAR SOLOMON ISL.", "SOLOMAN ISL. DOLLAR", "SOLOMAN ISL. DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_SCR, "ROUPIE /  SEYCHELLES", "THE SEYCHELLES / RUPEE", "THE SEYCHELLES / RUPEE"));
		m_lstChamps.add(new RefTableChamp(_REF_SDD, "DINAR SOUDANAIS", "SUDANESE DINAR", "SUDANESE DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_SEK, "COURONNE SUEDOISE", "SWEDISH CROWN", "SWEDISH CROWN"));
		m_lstChamps.add(new RefTableChamp(_REF_SGD, "DOLLAR / SINGAPOUR", "SINGAPORE / DOLLAR", "SINGAPORE / DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_SIT, "TOLAR SLOVENE", "SLOVENIAN TOLAR", "SLOVENIAN TOLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_SLL, "LEONE / SIERRA LEONE", "SIERRA LEONE / LEONE", "SIERRA LEONE / LEONE"));
		m_lstChamps.add(new RefTableChamp(_REF_SOS, "SHILLING SOMALIEN", "SOMALIAN SHILLING", "SOMALIAN SHILLING"));
		m_lstChamps.add(new RefTableChamp(_REF_SRG, "FLORIN DU SURIMAN", "SURIMAN FLORIN", "SURIMAN FLORIN"));
		m_lstChamps.add(new RefTableChamp(_REF_STD, "DOBRA / SAO TOME", "SAO TOME / DOBRA", "SAO TOME / DOBRA"));
		m_lstChamps.add(new RefTableChamp(_REF_SVC, "COLON SALVADORIEN", "SALVADORIAN COLON", "SALVADORIAN COLON"));
		m_lstChamps.add(new RefTableChamp(_REF_SYP, "LIVRE SYRIENNE", "SYRIAN POUND", "SYRIAN POUND"));
		m_lstChamps.add(new RefTableChamp(_REF_SZL, "LILANGENI / SWAZILAND", "SWAZILAND / LILANGENI", "SWAZILAND / LILANGENI"));
		m_lstChamps.add(new RefTableChamp(_REF_THB, "BATH THAILANDAISE", "THAI BATH", "THAI BATH"));
		m_lstChamps.add(new RefTableChamp(_REF_TJR, "ROUBLE / TAJIKISTAN", "TAJIKISTAN / RUBLE", "TAJIKISTAN / RUBLE"));
		m_lstChamps.add(new RefTableChamp(_REF_TMM, "MANAT / TURKMENISTAN", "TURKMENISTAN / MANAT", "TURKMENISTAN / MANAT"));
		m_lstChamps.add(new RefTableChamp(_REF_TND, "DINAR TUNISIEN", "TUNISIAN DINAR", "TUNISIAN DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_TOP, "PA ANGLA / ILES TOGA", "TONGA ISLANDS / PA ANGLA", "TONGA ISLANDS / PA ANGLA"));
		m_lstChamps.add(new RefTableChamp(_REF_TPE, "ESCUDO / EST TIMOR", "EAST TIMOR / ESCUDO", "EAST TIMOR / ESCUDO"));
		m_lstChamps.add(new RefTableChamp(_REF_TRY, "LIVRE TURQUE", "TURKISH LIRA", "TURKISH LIRA"));
		m_lstChamps.add(new RefTableChamp(_REF_TTD, "DOLLAR / TRINIDAD TOBAGO", "TRINIDAD TOBAGO / DOLLAR", "TRINIDAD TOBAGO / DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_TWD, "DOLLAR TAIWANAIS", "TAIWANIAN DOLLAR", "TAIWANIAN DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_TZS, "SHILLING TANZANIEN", "TANZANIAN SHILLING", "TANZANIAN SHILLING"));
		m_lstChamps.add(new RefTableChamp(_REF_UAH, "HRYVNIA / UKRAINE", "UKRAIN / HRYVNIA", "UKRAIN / HRYVNIA"));
		m_lstChamps.add(new RefTableChamp(_REF_UAK, "KARBOVANET UKRAINIEN", "UKRAINIAN KARBOVANET", "UKRAINIAN KARBOVANET"));
		m_lstChamps.add(new RefTableChamp(_REF_UGX, "SHILLING OUGANDAIS", "UGANDAN SHILLING", "UGANDAN SHILLING"));
		m_lstChamps.add(new RefTableChamp(_REF_USD, "DOLLAR US", "US DOLLAR", "US DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_UYU, "PESO URUGUAYEN", "URUGUAYAN PESO", "URUGUAYAN PESO"));
		m_lstChamps.add(new RefTableChamp(_REF_UZS, "SUM / UZBEKISTAN", "UZBEKISTAN / SUM", "UZBEKISTAN / SUM"));
		m_lstChamps.add(new RefTableChamp(_REF_VEB, "BOLIVAR VENEZILIEN", VENEZILIAN_BOLIVAR, VENEZILIAN_BOLIVAR));
		m_lstChamps.add(new RefTableChamp(_REF_VEF, "BOLIVAR VENEZILIEN", VENEZILIAN_BOLIVAR, VENEZILIAN_BOLIVAR));
		m_lstChamps.add(new RefTableChamp(_REF_VND, "DONG VIETNAMIEN", "VIETNAMIAN DONG", "VIETNAMIAN DONG"));
		m_lstChamps.add(new RefTableChamp(_REF_VUV, "VATU / VANUATU", "VANUATU / VATU", "VANUATU / VATU"));
		m_lstChamps.add(new RefTableChamp(_REF_WMP, "WMP", "WMP", "WMP"));
		m_lstChamps.add(new RefTableChamp(_REF_WST, "TALA / SAMOA", "SAMOA / TALA", "SAMOA / TALA"));
		m_lstChamps.add(new RefTableChamp(_REF_XAF, CFA_COM_AFRICAINE, AFRICA_COM_CFA, AFRICA_COM_CFA));
		m_lstChamps.add(new RefTableChamp(_REF_XCD, "DOLLAR /  INDES OCC BRIT", "INDIA / OCC BRIT DOLLAR", "INDIA / OCC BRIT DOLLAR"));
		m_lstChamps.add(new RefTableChamp(_REF_XDR, "DTS", "DTS", "DTS"));
		m_lstChamps.add(new RefTableChamp(_REF_XFA, CFA_COM_AFRICAINE, AFRICA_COM_CFA, AFRICA_COM_CFA));
		m_lstChamps.add(new RefTableChamp(_REF_XOF, CFA_COM_AFRICAINE, AFRICA_COM_CFA, AFRICA_COM_CFA));
		m_lstChamps.add(new RefTableChamp(_REF_XPF, "FRANC POLYNESIEN", "POLYNESIAN FRANC", "POLYNESIAN FRANC"));
		m_lstChamps.add(new RefTableChamp(_REF_YDD, "DINAR / YEMEN DEMO", "YEMEN DEMO / DINAR", "YEMEN DEMO / DINAR"));
		m_lstChamps.add(new RefTableChamp(_REF_YER, "RIAL YEMENITE R.A", "YEMENI R.A RIAL", "YEMENI R.A RIAL"));
		m_lstChamps.add(new RefTableChamp(_REF_YUG, "NOUV.DINAR SERBE", SERBIAN_NEW_DINAR, SERBIAN_NEW_DINAR));
		m_lstChamps.add(new RefTableChamp(_REF_YUM, "NOU.DINAR SERBE", SERBIAN_NEW_DINAR, SERBIAN_NEW_DINAR));
		m_lstChamps.add(new RefTableChamp(_REF_YUX, "NOUV.DINAR SERBE", SERBIAN_NEW_DINAR, SERBIAN_NEW_DINAR));
		m_lstChamps.add(new RefTableChamp(_REF_ZAR, "RAND/ AFR. DU SUD", "SOUTH AFRICA / RAND", "SOUTH AFRICA / RAND"));
		m_lstChamps.add(new RefTableChamp(_REF_ZMK, "KWACHA / ZAMBIE", "ZAMBIA / KWACHA", "ZAMBIA / KWACHA"));
		m_lstChamps.add(new RefTableChamp(_REF_ZRN, "REP. DEM.  CONGO", "REP. DEM . CONGO", "REP. DEM . CONGO"));
		m_lstChamps.add(new RefTableChamp(_REF_ZRZ, ZAIRE, ZAIRE, ZAIRE));
		m_lstChamps.add(new RefTableChamp(_REF_ZWD, "DOLLAR / ZIMBABWE", "ZIMBABWE / DOLLAR", "ZIMBABWE / DOLLAR"));
	}

	public static RefTableREF_MONNAIE instance() {
		if (null == m_RefTableREF_MONNAIE) {
			m_RefTableREF_MONNAIE = new RefTableREF_MONNAIE();
		}
		return m_RefTableREF_MONNAIE;
	}


}
