package com.airfrance.repind.entity.refTable;

public class RefTableLANGUES extends RefTableMere {


	private static RefTableLANGUES m_RefTableLANGUES = null;

	public static final String _REF_AA = "AA";
	public static final String _REF_AB = "AB";
	public static final String _REF_AE = "AE";
	public static final String _REF_AF = "AF";
	public static final String _REF_AK = "AK";
	public static final String _REF_AM = "AM";
	public static final String _REF_AN = "AN";
	public static final String _REF_AR = "AR";
	public static final String _REF_AS = "AS";
	public static final String _REF_AV = "AV";
	public static final String _REF_AY = "AY";
	public static final String _REF_AZ = "AZ";
	public static final String _REF_BA = "BA";
	public static final String _REF_BE = "BE";
	public static final String _REF_BG = "BG";
	public static final String _REF_BH = "BH";
	public static final String _REF_BI = "BI";
	public static final String _REF_BM = "BM";
	public static final String _REF_BN = "BN";
	public static final String _REF_BO = "BO";
	public static final String _REF_BR = "BR";
	public static final String _REF_BS = "BS";
	public static final String _REF_CA = "CA";
	public static final String _REF_CE = "CE";
	public static final String _REF_CH = "CH";
	public static final String _REF_CO = "CO";
	public static final String _REF_CR = "CR";
	public static final String _REF_CS = "CS";
	public static final String _REF_CT = "CT";
	public static final String _REF_CU = "CU";
	public static final String _REF_CV = "CV";
	public static final String _REF_CY = "CY";
	public static final String _REF_DA = "DA";
	public static final String _REF_DE = "DE";
	public static final String _REF_DI = "DI";
	public static final String _REF_DV = "DV";
	public static final String _REF_DZ = "DZ";
	public static final String _REF_EE = "EE";
	public static final String _REF_EL = "EL";
	public static final String _REF_EN = "EN";
	public static final String _REF_EO = "EO";
	public static final String _REF_ES = "ES";
	public static final String _REF_ET = "ET";
	public static final String _REF_EU = "EU";
	public static final String _REF_FA = "FA";
	public static final String _REF_FF = "FF";
	public static final String _REF_FI = "FI";
	public static final String _REF_FJ = "FJ";
	public static final String _REF_FO = "FO";
	public static final String _REF_FR = "FR";
	public static final String _REF_FY = "FY";
	public static final String _REF_GA = "GA";
	public static final String _REF_GD = "GD";
	public static final String _REF_GL = "GL";
	public static final String _REF_GN = "GN";
	public static final String _REF_GU = "GU";
	public static final String _REF_GV = "GV";
	public static final String _REF_HA = "HA";
	public static final String _REF_HE = "HE";
	public static final String _REF_HI = "HI";
	public static final String _REF_HO = "HO";
	public static final String _REF_HR = "HR";
	public static final String _REF_HT = "HT";
	public static final String _REF_HU = "HU";
	public static final String _REF_HY = "HY";
	public static final String _REF_HZ = "HZ";
	public static final String _REF_IA = "IA";
	public static final String _REF_ID = "ID";
	public static final String _REF_IE = "IE";
	public static final String _REF_IG = "IG";
	public static final String _REF_II = "II";
	public static final String _REF_IK = "IK";
	public static final String _REF_IO = "IO";
	public static final String _REF_IS = "IS";
	public static final String _REF_IT = "IT";
	public static final String _REF_IU = "IU";
	public static final String _REF_JA = "JA";
	public static final String _REF_JV = "JV";
	public static final String _REF_KA = "KA";
	public static final String _REF_KG = "KG";
	public static final String _REF_KI = "KI";
	public static final String _REF_KJ = "KJ";
	public static final String _REF_KK = "KK";
	public static final String _REF_KL = "KL";
	public static final String _REF_KM = "KM";
	public static final String _REF_KN = "KN";
	public static final String _REF_KO = "KO";
	public static final String _REF_KR = "KR";
	public static final String _REF_KS = "KS";
	public static final String _REF_KU = "KU";
	public static final String _REF_KV = "KV";
	public static final String _REF_KW = "KW";
	public static final String _REF_KY = "KY";
	public static final String _REF_LA = "LA";
	public static final String _REF_LB = "LB";
	public static final String _REF_LG = "LG";
	public static final String _REF_LI = "LI";
	public static final String _REF_LN = "LN";
	public static final String _REF_LO = "LO";
	public static final String _REF_LT = "LT";
	public static final String _REF_LU = "LU";
	public static final String _REF_LV = "LV";
	public static final String _REF_MG = "MG";
	public static final String _REF_MH = "MH";
	public static final String _REF_MI = "MI";
	public static final String _REF_MK = "MK";
	public static final String _REF_ML = "ML";
	public static final String _REF_MN = "MN";
	public static final String _REF_MO = "MO";
	public static final String _REF_MR = "MR";
	public static final String _REF_MS = "MS";
	public static final String _REF_MT = "MT";
	public static final String _REF_MY = "MY";
	public static final String _REF_NA = "NA";
	public static final String _REF_NB = "NB";
	public static final String _REF_ND = "ND";
	public static final String _REF_NE = "NE";
	public static final String _REF_NG = "NG";
	public static final String _REF_NL = "NL";
	public static final String _REF_NN = "NN";
	public static final String _REF_NO = "NO";
	public static final String _REF_NR = "NR";
	public static final String _REF_NV = "NV";
	public static final String _REF_NY = "NY";
	public static final String _REF_OC = "OC";
	public static final String _REF_OJ = "OJ";
	public static final String _REF_OM = "OM";
	public static final String _REF_OR = "OR";
	public static final String _REF_OS = "OS";
	public static final String _REF_PA = "PA";
	public static final String _REF_PI = "PI";
	public static final String _REF_PL = "PL";
	public static final String _REF_PS = "PS";
	public static final String _REF_PT = "PT";
	public static final String _REF_QU = "QU";
	public static final String _REF_RM = "RM";
	public static final String _REF_RN = "RN";
	public static final String _REF_RO = "RO";
	public static final String _REF_RU = "RU";
	public static final String _REF_RW = "RW";
	public static final String _REF_SA = "SA";
	public static final String _REF_SC = "SC";
	public static final String _REF_SD = "SD";
	public static final String _REF_SE = "SE";
	public static final String _REF_SG = "SG";
	public static final String _REF_SI = "SI";
	public static final String _REF_SK = "SK";
	public static final String _REF_SL = "SL";
	public static final String _REF_SM = "SM";
	public static final String _REF_SN = "SN";
	public static final String _REF_SO = "SO";
	public static final String _REF_SQ = "SQ";
	public static final String _REF_SR = "SR";
	public static final String _REF_SS = "SS";
	public static final String _REF_ST = "ST";
	public static final String _REF_SU = "SU";
	public static final String _REF_SV = "SV";
	public static final String _REF_SW = "SW";
	public static final String _REF_TA = "TA";
	public static final String _REF_TE = "TE";
	public static final String _REF_TG = "TG";
	public static final String _REF_TH = "TH";
	public static final String _REF_TI = "TI";
	public static final String _REF_TK = "TK";
	public static final String _REF_TL = "TL";
	public static final String _REF_TN = "TN";
	public static final String _REF_TO = "TO";
	public static final String _REF_TR = "TR";
	public static final String _REF_TS = "TS";
	public static final String _REF_TT = "TT";
	public static final String _REF_TW = "TW";
	public static final String _REF_TY = "TY";
	public static final String _REF_UG = "UG";
	public static final String _REF_UK = "UK";
	public static final String _REF_UR = "UR";
	public static final String _REF_UZ = "UZ";
	public static final String _REF_VE = "VE";
	public static final String _REF_VI = "VI";
	public static final String _REF_VO = "VO";
	public static final String _REF_WA = "WA";
	public static final String _REF_WO = "WO";
	public static final String _REF_XH = "XH";
	public static final String _REF_YI = "YI";
	public static final String _REF_YO = "YO";
	public static final String _REF_ZA = "ZA";
	public static final String _REF_ZH = "ZH";
	public static final String _REF_ZU = "ZU";



	public static final String AFAR = "AFAR";
	public static final String AFRIKAANS = "AFRIKAANS";
	public static final String AYMARA = "AYMARA";
	public static final String BIHARI = "BIHARI";
	public static final String BAMBARA = "BAMBARA";
	public static final String BENGALI = "BENGALI";
	public static final String BRETON = "BRETON";
	public static final String CATALAN = "CATALAN";
	public static final String CHAMORRO = "CHAMORRO";
	public static final String DIVEHI = "DIVEHI";
	public static final String DZONGKHA = "DZONGKHA";
	public static final String ESPERANTO = "ESPERANTO";
	public static final String BASQUE = "BASQUE";
	public static final String GUARANI = "GUARANI";
	public static final String GUJARATI = "GUJARATI";
	public static final String HINDI = "HINDI";
	public static final String HIRI_MOTU = "HIRI MOTU";
	public static final String HERERO = "HERERO";
	public static final String INTERLINGUA = "INTERLINGUA";
	public static final String INUPIAQ = "INUPIAQ";
	public static final String INUKTITUT = "INUKTITUT";
	public static final String KIKUYU = "KIKUYU";
	public static final String KAZAKH = "KAZAKH";
	public static final String KALAALLISUT = "KALAALLISUT";
	public static final String KHMER = "KHMER";
	public static final String KASHMIRI = "KASHMIRI";
	public static final String KIRGHIZ = "KIRGHIZ";
	public static final String LATIN = "LATIN";
	public static final String GANDA = "GANDA";
	public static final String LINGALA = "LINGALA";
	public static final String MALAYALAM = "MALAYALAM";
	public static final String MARATHI = "MARATHI";
	public static final String NDONGA = "NDONGA";
	public static final String NAVAJO = "NAVAJO";
	public static final String CHICHEWA = "CHICHEWA";
	public static final String OCCITAN = "OCCITAN";
	public static final String OROMO = "OROMO";
	public static final String ORIYA = "ORIYA";
	public static final String PANJABI = "PANJABI";
	public static final String QUECHUA = "QUECHUA";
	public static final String KIRUNDI = "KIRUNDI";
	public static final String KINYARWANDA = "KINYARWANDA";
	public static final String SANSKRIT = "SANSKRIT";
	public static final String SINDHI = "SINDHI";
	public static final String SANGO = "SANGO";
	public static final String SLOVENE = "SLOVENE";
	public static final String SAMOAN = "SAMOAN";
	public static final String SHONA = "SHONA";
	public static final String SOMALI = "SOMALI";
	public static final String SWAHILI = "SWAHILI";
	public static final String TIGRINYA = "TIGRINYA";
	public static final String TAGALOG = "TAGALOG";
	public static final String TSWANA = "TSWANA";
	public static final String TSONGA = "TSONGA";
	public static final String TATAR = "TATAR";
	public static final String VENDA = "VENDA";
	public static final String VOLAPUK = "VOLAPUK";
	public static final String WOLOF = "WOLOF";
	public static final String XHOSA = "XHOSA";
	public static final String YIDDISH = "YIDDISH";
	public static final String YORUBA = "YORUBA";
	public static final String ZHUANG = "ZHUANG";



	private RefTableLANGUES() {

		m_lstChamps.add(new RefTableChamp(_REF_AA, AFAR, AFAR, AFAR));
		m_lstChamps.add(new RefTableChamp(_REF_AB, "ABKHAZE", "ABKHAZIAN", "ABKHAZIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_AE, "AVESTIQUE", "AVESTAN", "AVESTAN"));
		m_lstChamps.add(new RefTableChamp(_REF_AF, AFRIKAANS, AFRIKAANS, AFRIKAANS));
		m_lstChamps.add(new RefTableChamp(_REF_AK, "AKAN", "AKAN", "AKAN"));
		m_lstChamps.add(new RefTableChamp(_REF_AM, "AMHARIQUE", "AMHARIC", "AMHARIC"));
		m_lstChamps.add(new RefTableChamp(_REF_AN, "ARAGONAIS", "ARAGONESE", "ARAGONESE"));
		m_lstChamps.add(new RefTableChamp(_REF_AR, "ARABE", "ARAB", "ARAB"));
		m_lstChamps.add(new RefTableChamp(_REF_AS, "ASSAMAIS", "ASSAMESE", "ASSAMESE"));
		m_lstChamps.add(new RefTableChamp(_REF_AV, "AVAR", "AVARIC", "AVARIC"));
		m_lstChamps.add(new RefTableChamp(_REF_AY, AYMARA, AYMARA, AYMARA));
		m_lstChamps.add(new RefTableChamp(_REF_AZ, "AZERI", "AZERBAIJANI", "AZERBAIJANI"));
		m_lstChamps.add(new RefTableChamp(_REF_BA, "BACHKIR", "BASHKIR", "BASHKIR"));
		m_lstChamps.add(new RefTableChamp(_REF_BE, "BIELORUSSE", "BELARUSIAN", "BELARUSIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_BG, "BULGARE", "BULGARIAN", "BULGARIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_BH, BIHARI, BIHARI, BIHARI));
		m_lstChamps.add(new RefTableChamp(_REF_BI, "BICHELAMAR", "BISLAMA", "BISLAMA"));
		m_lstChamps.add(new RefTableChamp(_REF_BM, BAMBARA, BAMBARA, BAMBARA));
		m_lstChamps.add(new RefTableChamp(_REF_BN, BENGALI, BENGALI, BENGALI));
		m_lstChamps.add(new RefTableChamp(_REF_BO, "TIBETAIN", "TIBETAN", "TIBETAN"));
		m_lstChamps.add(new RefTableChamp(_REF_BR, BRETON, BRETON, BRETON));
		m_lstChamps.add(new RefTableChamp(_REF_BS, "BOSNIEN", "BOSNIAN", "BOSNIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_CA, CATALAN, CATALAN, CATALAN));
		m_lstChamps.add(new RefTableChamp(_REF_CE, "TCHETCHENE", "CHECHEN", "CHECHEN"));
		m_lstChamps.add(new RefTableChamp(_REF_CH, CHAMORRO, CHAMORRO, CHAMORRO));
		m_lstChamps.add(new RefTableChamp(_REF_CO, "CORSE", "CORSICAN", "CORSICAN"));
		m_lstChamps.add(new RefTableChamp(_REF_CR, "CRI", "CREE", "CREE"));
		m_lstChamps.add(new RefTableChamp(_REF_CS, "TCHEQUE", "CZECH", "CZECH"));
		m_lstChamps.add(new RefTableChamp(_REF_CT, "CHINOIS TRADITIONNEL", "TRADITIONAL CHINESE", "TRADITIONAL CHINESE"));
		m_lstChamps.add(new RefTableChamp(_REF_CU, "VIEUX SLAVE", "OLD CHURCH SLAVONIC", "OLD CHURCH SLAVONIC"));
		m_lstChamps.add(new RefTableChamp(_REF_CV, "TCHOUVACHE", "CHUVASH", "CHUVASH"));
		m_lstChamps.add(new RefTableChamp(_REF_CY, "GALLOIS", "WELSH", "WELSH"));
		m_lstChamps.add(new RefTableChamp(_REF_DA, "DANOIS", "DANISH", "DANISH"));
		m_lstChamps.add(new RefTableChamp(_REF_DE, "ALLEMAND", "GERMAN", "GERMAN"));
		m_lstChamps.add(new RefTableChamp(_REF_DI, "DIVERS", "MISCELLANEOUS", "MISCELLANEOUS"));
		m_lstChamps.add(new RefTableChamp(_REF_DV, DIVEHI, DIVEHI, DIVEHI));
		m_lstChamps.add(new RefTableChamp(_REF_DZ, DZONGKHA, DZONGKHA, DZONGKHA));
		m_lstChamps.add(new RefTableChamp(_REF_EE, "EWE", "EWE", "EWE"));
		m_lstChamps.add(new RefTableChamp(_REF_EL, "GREC", "GREEK", "GREEK"));
		m_lstChamps.add(new RefTableChamp(_REF_EN, "ANGLAIS", "ENGLISH", "ENGLISH"));
		m_lstChamps.add(new RefTableChamp(_REF_EO, ESPERANTO, ESPERANTO, ESPERANTO));
		m_lstChamps.add(new RefTableChamp(_REF_ES, "ESPAGNOL", "SPANISH", "SPANISH"));
		m_lstChamps.add(new RefTableChamp(_REF_ET, "ESTONIEN", "ESTONIAN", "ESTONIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_EU, BASQUE, BASQUE, BASQUE));
		m_lstChamps.add(new RefTableChamp(_REF_FA, "PERSAN", "PERSIAN", "PERSIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_FF, "PEUL", "FULAH", "FULAH"));
		m_lstChamps.add(new RefTableChamp(_REF_FI, "FINNOIS", "FINNISH", "FINNISH"));
		m_lstChamps.add(new RefTableChamp(_REF_FJ, "FIDJIEN", "FIJIAN", "FIJIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_FO, "FERINGIEN", "FAROESE", "FAROESE"));
		m_lstChamps.add(new RefTableChamp(_REF_FR, "FRANCAIS", "FRENCH", "FRENCH"));
		m_lstChamps.add(new RefTableChamp(_REF_FY, "FRISON", "WESTERN FRISIAN", "WESTERN FRISIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_GA, "IRLANDAIS", "IRISH", "IRISH"));
		m_lstChamps.add(new RefTableChamp(_REF_GD, "ECOSSAIS", "SCOTTISH GAELIC", "SCOTTISH GAELIC"));
		m_lstChamps.add(new RefTableChamp(_REF_GL, "GALICIEN", "GALICIAN", "GALICIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_GN, GUARANI, GUARANI, GUARANI));
		m_lstChamps.add(new RefTableChamp(_REF_GU, GUJARATI, GUJARATI, GUJARATI));
		m_lstChamps.add(new RefTableChamp(_REF_GV, "MANNOIS", "MANX", "MANX"));
		m_lstChamps.add(new RefTableChamp(_REF_HA, "HAOUSSA", "HAUSA", "HAUSA"));
		m_lstChamps.add(new RefTableChamp(_REF_HE, "HEBREU", "HEBREW", "HEBREW"));
		m_lstChamps.add(new RefTableChamp(_REF_HI, HINDI, HINDI, HINDI));
		m_lstChamps.add(new RefTableChamp(_REF_HO, HIRI_MOTU, HIRI_MOTU, HIRI_MOTU));
		m_lstChamps.add(new RefTableChamp(_REF_HR, "CROATE", "CROATIAN", "CROATIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_HT, "CREOLE HAITIEN", "HAITIAN", "HAITIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_HU, "HONGROIS", "HUNGARIAN", "HUNGARIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_HY, "ARMENIEN", "ARMENIAN", "ARMENIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_HZ, HERERO, HERERO, HERERO));
		m_lstChamps.add(new RefTableChamp(_REF_IA, INTERLINGUA, INTERLINGUA, INTERLINGUA));
		m_lstChamps.add(new RefTableChamp(_REF_ID, "INDONESIEN", "INDONESIAN", "INDONESIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_IE, "OCCIDENTAL", "INTERLINGUE", "INTERLINGUE"));
		m_lstChamps.add(new RefTableChamp(_REF_IG, "IGBO", "IGBO", "IGBO"));
		m_lstChamps.add(new RefTableChamp(_REF_II, "YI", "SICHUAN YI", "SICHUAN YI"));
		m_lstChamps.add(new RefTableChamp(_REF_IK, INUPIAQ, INUPIAQ, INUPIAQ));
		m_lstChamps.add(new RefTableChamp(_REF_IO, "IDO", "IDO", "IDO"));
		m_lstChamps.add(new RefTableChamp(_REF_IS, "ISLANDAIS", "ICELANDIC", "ICELANDIC"));
		m_lstChamps.add(new RefTableChamp(_REF_IT, "ITALIEN", "ITALIAN", "ITALIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_IU, INUKTITUT, INUKTITUT, INUKTITUT));
		m_lstChamps.add(new RefTableChamp(_REF_JA, "JAPONAIS", "JAPANESE", "JAPANESE"));
		m_lstChamps.add(new RefTableChamp(_REF_JV, "JAVANAIS", "JAVANESE", "JAVANESE"));
		m_lstChamps.add(new RefTableChamp(_REF_KA, "GEORGIEN", "GEORGIAN", "GEORGIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_KG, "KIKONGO", "KONGO", "KONGO"));
		m_lstChamps.add(new RefTableChamp(_REF_KI, KIKUYU, KIKUYU, KIKUYU));
		m_lstChamps.add(new RefTableChamp(_REF_KJ, "KUANYAMA", "KWANYAMA", "KWANYAMA"));
		m_lstChamps.add(new RefTableChamp(_REF_KK, KAZAKH, KAZAKH, KAZAKH));
		m_lstChamps.add(new RefTableChamp(_REF_KL, KALAALLISUT, KALAALLISUT, KALAALLISUT));
		m_lstChamps.add(new RefTableChamp(_REF_KM, KHMER, KHMER, KHMER));
		m_lstChamps.add(new RefTableChamp(_REF_KN, "KANNARA", "KANNADA", "KANNADA"));
		m_lstChamps.add(new RefTableChamp(_REF_KO, "COREEN", "KOREAN", "KOREAN"));
		m_lstChamps.add(new RefTableChamp(_REF_KR, "KANOURI", "KANURI", "KANURI"));
		m_lstChamps.add(new RefTableChamp(_REF_KS, KASHMIRI, KASHMIRI, KASHMIRI));
		m_lstChamps.add(new RefTableChamp(_REF_KU, "KURDE", "KURDISH", "KURDISH"));
		m_lstChamps.add(new RefTableChamp(_REF_KV, "KOMI", "KOMI", "KOMI"));
		m_lstChamps.add(new RefTableChamp(_REF_KW, "CORNIQUE", "CORNISH", "CORNISH"));
		m_lstChamps.add(new RefTableChamp(_REF_KY, KIRGHIZ, KIRGHIZ, KIRGHIZ));
		m_lstChamps.add(new RefTableChamp(_REF_LA, LATIN, LATIN, LATIN));
		m_lstChamps.add(new RefTableChamp(_REF_LB, "LUXEMBOURGEOIS", "LUXEMBOURGISH", "LUXEMBOURGISH"));
		m_lstChamps.add(new RefTableChamp(_REF_LG, GANDA, GANDA, GANDA));
		m_lstChamps.add(new RefTableChamp(_REF_LI, "LIMBOURGEOIS", "LIMBURGISH", "LIMBURGISH"));
		m_lstChamps.add(new RefTableChamp(_REF_LN, LINGALA, LINGALA, LINGALA));
		m_lstChamps.add(new RefTableChamp(_REF_LO, "LAO", "LAO", "LAO"));
		m_lstChamps.add(new RefTableChamp(_REF_LT, "LITUANIEN", "LITHUANIAN", "LITHUANIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_LU, "TCHILUBA", "LUBA-KATANGA", "LUBA-KATANGA"));
		m_lstChamps.add(new RefTableChamp(_REF_LV, "LETTON", "LATVIAN", "LATVIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_MG, "MALGACHE", "MALAGASY", "MALAGASY"));
		m_lstChamps.add(new RefTableChamp(_REF_MH, "MARSHALLAIS", "MARSHALLESE", "MARSHALLESE"));
		m_lstChamps.add(new RefTableChamp(_REF_MI, "MAORINOUVELLEZELANDE", "MAORI", "MAORI"));
		m_lstChamps.add(new RefTableChamp(_REF_MK, "MACEDONIEN", "MACEDONIAN", "MACEDONIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_ML, MALAYALAM, MALAYALAM, MALAYALAM));
		m_lstChamps.add(new RefTableChamp(_REF_MN, "MONGOL", "MONGOLIAN", "MONGOLIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_MO, "MOLDAVE", "MOLDAVIAN", "MOLDAVIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_MR, MARATHI, MARATHI, MARATHI));
		m_lstChamps.add(new RefTableChamp(_REF_MS, "MALAIS", "MALAY", "MALAY"));
		m_lstChamps.add(new RefTableChamp(_REF_MT, "MALTAIS", "MALTESE", "MALTESE"));
		m_lstChamps.add(new RefTableChamp(_REF_MY, "BIRMAN", "BURMESE", "BURMESE"));
		m_lstChamps.add(new RefTableChamp(_REF_NA, "NAURUAN", "NAURU", "NAURU"));
		m_lstChamps.add(new RefTableChamp(_REF_NB, "NORVEGIEN BOKMAL", "NORWEGIAN BOKMAL", "NORWEGIAN BOKMAL"));
		m_lstChamps.add(new RefTableChamp(_REF_ND, "NDEBELE DU NORD", "NORTH NDEBELE", "NORTH NDEBELE"));
		m_lstChamps.add(new RefTableChamp(_REF_NE, "NEPALAIS", "NEPALI", "NEPALI"));
		m_lstChamps.add(new RefTableChamp(_REF_NG, NDONGA, NDONGA, NDONGA));
		m_lstChamps.add(new RefTableChamp(_REF_NL, "NEERLANDAIS", "DUTCH", "DUTCH"));
		m_lstChamps.add(new RefTableChamp(_REF_NN, "NORVEGIEN NYNORSK", "NORWEGIAN NYNORSK", "NORWEGIAN NYNORSK"));
		m_lstChamps.add(new RefTableChamp(_REF_NO, "NORVEGIEN", "NORVEGIAN", "NORVEGIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_NR, "NDEBELE DU SUD", "SOUTH NDEBELE", "SOUTH NDEBELE"));
		m_lstChamps.add(new RefTableChamp(_REF_NV, NAVAJO, NAVAJO, NAVAJO));
		m_lstChamps.add(new RefTableChamp(_REF_NY, CHICHEWA, CHICHEWA, CHICHEWA));
		m_lstChamps.add(new RefTableChamp(_REF_OC, OCCITAN, OCCITAN, OCCITAN));
		m_lstChamps.add(new RefTableChamp(_REF_OJ, "OJIBWE", "OJIBWA", "OJIBWA"));
		m_lstChamps.add(new RefTableChamp(_REF_OM, OROMO, OROMO, OROMO));
		m_lstChamps.add(new RefTableChamp(_REF_OR, ORIYA, ORIYA, ORIYA));
		m_lstChamps.add(new RefTableChamp(_REF_OS, "OSSETE", "OSSETIAN", "OSSETIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_PA, PANJABI, PANJABI, PANJABI));
		m_lstChamps.add(new RefTableChamp(_REF_PI, "PALI", "PALI", "PALI"));
		m_lstChamps.add(new RefTableChamp(_REF_PL, "POLONAIS", "POLISH", "POLISH"));
		m_lstChamps.add(new RefTableChamp(_REF_PS, "PACHTO", "PASHTO", "PASHTO"));
		m_lstChamps.add(new RefTableChamp(_REF_PT, "PORTUGUAIS", "PORTUGESE", "PORTUGESE"));
		m_lstChamps.add(new RefTableChamp(_REF_QU, QUECHUA, QUECHUA, QUECHUA));
		m_lstChamps.add(new RefTableChamp(_REF_RM, "ROMANCHE", "RAETO-ROMANCE", "RAETO-ROMANCE"));
		m_lstChamps.add(new RefTableChamp(_REF_RN, KIRUNDI, KIRUNDI, KIRUNDI));
		m_lstChamps.add(new RefTableChamp(_REF_RO, "ROM", "ROMANIAN", "ROMANIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_RU, "RUSSE", "RUSSIAN", "RUSSIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_RW, KINYARWANDA, KINYARWANDA, KINYARWANDA));
		m_lstChamps.add(new RefTableChamp(_REF_SA, SANSKRIT, SANSKRIT, SANSKRIT));
		m_lstChamps.add(new RefTableChamp(_REF_SC, "SARDE", "SARDINIAN", "SARDINIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_SD, SINDHI, SINDHI, SINDHI));
		m_lstChamps.add(new RefTableChamp(_REF_SE, "SAME DU NORD", "NORTHERN SAMI", "NORTHERN SAMI"));
		m_lstChamps.add(new RefTableChamp(_REF_SG, SANGO, SANGO, SANGO));
		m_lstChamps.add(new RefTableChamp(_REF_SI, "CINGALAIS", "SINHALESE", "SINHALESE"));
		m_lstChamps.add(new RefTableChamp(_REF_SK, "SLOVAQUE", "SLOVAK", "SLOVAK"));
		m_lstChamps.add(new RefTableChamp(_REF_SL, SLOVENE, SLOVENE, SLOVENE));
		m_lstChamps.add(new RefTableChamp(_REF_SM, SAMOAN, SAMOAN, SAMOAN));
		m_lstChamps.add(new RefTableChamp(_REF_SN, SHONA, SHONA, SHONA));
		m_lstChamps.add(new RefTableChamp(_REF_SO, SOMALI, SOMALI, SOMALI));
		m_lstChamps.add(new RefTableChamp(_REF_SQ, "ALBANAIS", "ALBANIAN", "ALBANIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_SR, "SERBE", "SERBIAN", "SERBIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_SS, "SISWATI", "SWATI", "SWATI"));
		m_lstChamps.add(new RefTableChamp(_REF_ST, "SOTHO DU SUD", "SOTHO", "SOTHO"));
		m_lstChamps.add(new RefTableChamp(_REF_SU, "SOUNDANAIS", "SUNDANESE", "SUNDANESE"));
		m_lstChamps.add(new RefTableChamp(_REF_SV, "SUEDOIS", "SWEDISH", "SWEDISH"));
		m_lstChamps.add(new RefTableChamp(_REF_SW, SWAHILI, SWAHILI, SWAHILI));
		m_lstChamps.add(new RefTableChamp(_REF_TA, "TAMOUL", "TAMIL", "TAMIL"));
		m_lstChamps.add(new RefTableChamp(_REF_TE, "TELOUGOU", "TELUGU", "TELUGU"));
		m_lstChamps.add(new RefTableChamp(_REF_TG, "TADJIK", "TAJIK", "TAJIK"));
		m_lstChamps.add(new RefTableChamp(_REF_TH, "THAI", "THAI", "THAI"));
		m_lstChamps.add(new RefTableChamp(_REF_TI, TIGRINYA, TIGRINYA, TIGRINYA));
		m_lstChamps.add(new RefTableChamp(_REF_TK, "TURKMENE", "TURKMEN", "TURKMEN"));
		m_lstChamps.add(new RefTableChamp(_REF_TL, TAGALOG, TAGALOG, TAGALOG));
		m_lstChamps.add(new RefTableChamp(_REF_TN, TSWANA, TSWANA, TSWANA));
		m_lstChamps.add(new RefTableChamp(_REF_TO, "TONGIEN", "TONGA", "TONGA"));
		m_lstChamps.add(new RefTableChamp(_REF_TR, "TURC", "TURKISH", "TURKISH"));
		m_lstChamps.add(new RefTableChamp(_REF_TS, TSONGA, TSONGA, TSONGA));
		m_lstChamps.add(new RefTableChamp(_REF_TT, TATAR, TATAR, TATAR));
		m_lstChamps.add(new RefTableChamp(_REF_TW, "TWI", "TWI", "TWI"));
		m_lstChamps.add(new RefTableChamp(_REF_TY, "TAHITIEN", "TAHITIAN", "TAHITIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_UG, "OUIGHOUR", "UIGHUR", "UIGHUR"));
		m_lstChamps.add(new RefTableChamp(_REF_UK, "UKRAINIEN", "UKRAINIAN", "UKRAINIAN"));
		m_lstChamps.add(new RefTableChamp(_REF_UR, "OURDOU", "URDU", "URDU"));
		m_lstChamps.add(new RefTableChamp(_REF_UZ, "OUZBEK", "UZBEK", "UZBEK"));
		m_lstChamps.add(new RefTableChamp(_REF_VE, VENDA, VENDA, VENDA));
		m_lstChamps.add(new RefTableChamp(_REF_VI, "VIETNAMIEN", "VIETNAMESE", "VIETNAMESE"));
		m_lstChamps.add(new RefTableChamp(_REF_VO, VOLAPUK, VOLAPUK, VOLAPUK));
		m_lstChamps.add(new RefTableChamp(_REF_WA, "WALLON", "WALLOON", "WALLOON"));
		m_lstChamps.add(new RefTableChamp(_REF_WO, WOLOF, WOLOF, WOLOF));
		m_lstChamps.add(new RefTableChamp(_REF_XH, XHOSA, XHOSA, XHOSA));
		m_lstChamps.add(new RefTableChamp(_REF_YI, YIDDISH, YIDDISH, YIDDISH));
		m_lstChamps.add(new RefTableChamp(_REF_YO, YORUBA, YORUBA, YORUBA));
		m_lstChamps.add(new RefTableChamp(_REF_ZA, ZHUANG, ZHUANG, ZHUANG));
		m_lstChamps.add(new RefTableChamp(_REF_ZH, "CHINOIS SIMPLIFIE", "SIMPLIFIED CHINESE", "SIMPLIFIED CHINESE"));
		m_lstChamps.add(new RefTableChamp(_REF_ZU, "ZOULOU", "ZULU", "ZULU"));
	}

	public static RefTableLANGUES instance() {
		if (null == m_RefTableLANGUES) {
			m_RefTableLANGUES = new RefTableLANGUES();
		}
		return m_RefTableLANGUES;
	}


}
