spring:
  config:
    activate:
      on-profile: ITE,dev
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_ITE.WORLD
    maxPoolSize: 1

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
    
ri-search-gin-by-lastname-firstname:
  url: http://search-gin-by-lastname-firstname-ite:8080/
