---
spring:
  config:
    activate:
      on-profile: default,local
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_ITE.WORLD

apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000058
  errorEnabled: false

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: ITE,dev
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_ITE.WORLD

apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000058

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: UTE,rct
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_CAE.WORLD

apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000058

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: AE,qal
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@OSMN305.WORLD

apim.jwt.validation:
  environment: NPR
  securityId: w04776476
  serviceIds:
    - R000058

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: LE,prd
  datasource:
    tns_admin_env: PROD
    url: jdbc:oracle:thin:@REPIND_PRD.WORLD

apim.jwt.validation:
  environment: PRD
  securityId: w04776476
  serviceIds:
    - R000058

vault:
  uri: https://vault-tls.airfranceklm.com
  namespace: repind
  env: prod
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}
debug: false
logging:
  level:
    root: INFO
---