

DROP TABLE PURGE_AGENCES;

CREATE TABLE PURGE_AGENCES (
ICLE NUMBER(10),
GIN VARCHAR(12) NOT NULL,
NUM_AGENCE VARCHAR(20),
NUM_AGENCE_MERE VARCHAR(20),
STATUT VARCHAR(2) NOT NULL,
ZC1 VARCHAR(3),
TYPE_AGENCE VARCHAR(2),
RAISON_SOCIALE VARCHAR(45),
NOM_USUEL VARCHAR(45),
DATE_OUVERTURE DATE,
DATE_RADIATION DATE,
DATE_FERMETURE DATE,
TYPE_CONTRAT VARCHAR(2),
SOUS_TYPE_CONTRAT VARCHAR(2),
DEBUT_VALIDITE DATE,
FIN_VALIDITE DATE,
RESULTAT VARCHAR(12),
MONNAIE VARCHAR(3),
GIN_FIRME VARCHAR(12),
ZC_FIRME VARCHAR(18),
LIEN_ZC_FIRME VARCHAR(1),
DATE_FIN_FIRME DATE,
ZC_FIRME_ACTIF VARCHAR(1),
APURGER VARCHAR(1) DEFAULT 'O',
CONSTRAINT PK_PURGE_AGENCES
PRIMARY KEY( ICLE ))
TABLESPACE SIC_TBL;

CREATE INDEX IND_PURGE_GIN ON PURGE_AGENCES(GIN) TABLESPACE SIC_TBL;

exit;