
package com.afklm.bird.ws.w000309;

import com.afklm.bird.ws.w000309.data.schema6538.BirdWSCityBusinessFault;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BirdWSCityBusinessFaultElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd")
public class MsgBirdWSCityBusinessFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BirdWSCityBusinessFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MsgBirdWSCityBusinessFault(String message, BirdWSCityBusinessFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public MsgBirdWSCityBusinessFault(String message, BirdWSCityBusinessFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.afklm.bird.ws.w000309.data.schema6538.BirdWSCityBusinessFault
     */
    public BirdWSCityBusinessFault getFaultInfo() {
        return faultInfo;
    }

}
