
package com.afklm.bird.ws.w000309;

import com.afklm.bird.ws.w000309.data.schema6538.CityRequest;
import com.afklm.bird.ws.w000309.data.schema6538.CityResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProvideCityInformation-v1", targetNamespace = "http://www.af-klm.com/services/passenger/ProvideCityInformation-v1/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.bird.ws.w000309.data.schema6538.ObjectFactory.class,
    com.afklm.bird.ws.w000309.data.schema5297.ObjectFactory.class,
    com.afklm.bird.ws.w000309.data.schema864.ObjectFactory.class,
    com.afklm.bird.ws.w000309.data.schema5299.ObjectFactory.class
})
public interface ProvideCityInformationV1 {


    /**
     * 
     * @param criteria
     * @return
     *     returns com.afklm.bird.ws.w000309.data.schema6538.CityResponse
     * @throws SystemFault
     * @throws MsgBirdWSCityBusinessFault
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/ProvideCityInformation-v1/provideCityInformation")
    @WebResult(name = "CityResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd", partName = "results")
    public CityResponse provideCityInformation(
        @WebParam(name = "CityRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd", partName = "criteria")
        CityRequest criteria)
        throws MsgBirdWSCityBusinessFault, SystemFault
    ;

}
