/*
 * DQE Address API
 * Endpoints documentation
 *
 * OpenAPI spec version: 3.2.0
 * Contact: support_dqe@dqe-software.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.afklm.rigui.client.dqe;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RNVP
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-26T10:57:41.966347600+02:00[Europe/Paris]")
public class RNVP {
  @JsonProperty("1")
  private RNVP1 _1 = null;

  public RNVP _1(RNVP1 _1) {
    this._1 = _1;
    return this;
  }

  /**
   * Get _1
   * @return _1
   **/
  @Schema(required = true, description = "")
  public RNVP1 get1() {
    return _1;
  }

  public void set1(RNVP1 _1) {
    this._1 = _1;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RNVP RNVP = (RNVP) o;
    return Objects.equals(this._1, RNVP._1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RNVP {\n");

    sb.append("    _1: ").append(toIndentedString(_1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
