replicaCount: 2

# Describes the pdb.Value for this is half of replica count
podDisruptionBudget:
  minAvailable: 1

# claim the user node pool for deployment
nodeSelector:
  kubernetes.azure.com/mode: user

image: 
  repository: acrriprd09999808.azurecr.io/ri-gui-ss
  pullPolicy: "Always"
  tag: latest


serviceAccount:
  # Specifies whether a service account should be created or not 
  create: true
  
runAsUser: 1000

rbac:
  enabled: true
  roles:
    - apiGroups: [""]
      resources: ["pods", "nodes", "configmaps", "endpoints", "namespaces", "services", "events"]
      verbs: ["get", "list", "watch" ]
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: [ "create", "update"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]

isTmpVolumeRequired: true

#key vault related configuration
secretProvider:
  keyVaultName: 'kv-ri-pr-8366'
  keyVaultRG: 'rg-ri-spoke-prod-frc-001'
  subscriptionId: '9451007c-eb98-4383-a8e9-3a86406810ee'
  keyVaultTenantId: '9b802d8b-33fa-40fb-acb7-9ffdbd1919eb'
  objects:
    - objectName: vaultRoleId # Key Vault secret name
      objectType: "secret"
    - objectName: vaultSecretId # Key Vault secret name
      objectType: "secret"
  secretObjects: # Sync as Kubernetes Secret
    - secretName: app-secret-ri-gui-ss # Kubernetes Secret
      type: Opaque
      data:
      - objectName: vaultRoleId # Key Vault Secret name
        key: VAULT_CREDENTIALS_ROLE_ID # Secret Key
      - objectName: vaultSecretId # Key Vault Secret name
        key: VAULT_CREDENTIALS_SECRET_ID # Secret Key

# Describes the Azure Managed AAD Pod Identity
azureIdentity: 
  name: "repind-ri-gui-ss-prd-azureidentity"
  type: 0
  configmap:
    name: aks-kv-sp-identity
    namespace: prd
    clientid: aks-kv-sp-client-id
    resourceid: aks-kv-sp-resource-id

# Describes the identity binding relationship between an AzureIdentity and a pod with a specific selector as part of its label
azureIdentityBinding:
  name: "repind-ri-gui-ss-prd-azureidentitybinding"
  selector: "repind-ri-gui-ss-prd-selector"

# Specifies whether autoscaling should be enabled or not
autoscaling:
  enabled: 'true'
  minReplicas: 2
  maxReplicas: 4
  targetAverageUtilization: 80
  targetAverageValue: 40Mi

ingress:
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/rewrite-target: /
  private: 
    enabled: 'true'
    annotations:
      kubernetes.io/ingress.class: haproxy
    hosts:
      - host: ri-az.airfrance.fr
        paths:
          - /rigui-api/
  tls:
    - hosts:
      - ri-az.airfrance.fr
      secretName: defaultcert

# resource management for pods
resources:
  limits:
    cpu: 900m
    memory: 732Mi
  requests:
    cpu: 300m
    memory: 336Mi

#liveness and readiness probe for container
#probes:
#  livenessProbe:
#    path: /api-mgr/repind-ri-gui-ss/infra/healthcheck
#  readinessProbe:
#    path: /api-mgr/repind-ri-gui-ss/infra/healthcheck

deployment:
  containerPort: 8080

service:
  type: ClusterIP
  port: 8080

# config Map individual key/value pairs
configMap:
  SPRING_PROFILES_ACTIVE: "LE,prd"
  ENV: "prd"
  SPRING_CONFIG_LOCATION: "classpath:/config/web-config-prd.properties"
  SPRING_DATASOURCE_SIC_URL: "jdbc:oracle:thin:@SIC_PLE.WORLD"
  ENV_REPIND_BOOTSTRAP_SERVERS: "bootstrap.servers=qvipclogkb01.france.airfrance.fr:6668,qvipclogkb02.france.airfrance.fr:6668,qvipclogkb03.france.airfrance.fr:6668,qvipclogkb04.france.airfrance.fr:6668"
  JAVA_OPTS: "-Dspring.profiles.active=azure,kube,habile,LE,prd -Doracle.jdbc.timezoneAsRegion=false -Djava.security.krb5.kdc=qvipbkrbrs01.france.airfrance.fr -Djava.security.krb5.realm=PRD.FRANCE.AIRFRANCE.FR -Djava.sun.security.krb5.debug=false -Djava.security.auth.login.config=/home/vcap/tmp/jaas.config --add-opens=java.base/java.lang=ALL-UNNAMED"


# env variables from secretProviderClass
envFrom:
  - secretRef:
      name: app-secret-ri-gui-ss
