package com.afklm.repind.msv.mapping.model.error;

import java.util.EnumMap;
import java.util.Map;

/**
 * Business errors list
 *
 * @author m312812
 *
 */
public enum BusinessErrorList {

	API_CUSTOMER_EMPTY(
			new RestError("business.001", "gin or frequentFlyerNumber must not be empty", null, ErrorType.WARNING)),

	API_COMPLAINT_NOT_FOUND(new RestError("business.002", "Complaint id not found", null, ErrorType.WARNING)),

	API_STATION_NOT_FOUND(new RestError("business.003", "Station not found", null, ErrorType.WARNING)),

	API_NOTHING_TO_UPDATE(new RestError("business.004", "Nothing to update", null, ErrorType.WARNING)),

	API_NOTHING_TO_DELETE(new RestError("business.005", "Nothing to delete", null, ErrorType.WARNING)),

	API_MISSING_REQUEST_PARAMETER(new RestError("business.400", "Missing Request Parameter", null, ErrorType.WARNING)),

	API_REF_MAPPING_NOT_FOUND(
			new RestError("business.404.001", BusinessErorMessageList.ERROR_MESSAGE_404_001, null, ErrorType.WARNING)),

	API_LANGUAGE_MAPPING_NOT_FOUND(
			new RestError("business.404.002", BusinessErorMessageList.ERROR_MESSAGE_404_002, null, ErrorType.WARNING)),

	API_CONSTRAINT_VIOLATION(new RestError("business.412", "Business constraint violation", null, ErrorType.WARNING)),

	API_PARAMETER_TYPE_MISMATCH(new RestError("business.412.001", "Mismatch type parameter", null, ErrorType.WARNING)),

	API_CONTEXT_VIOLATION(
			new RestError("business.412.002", BusinessErorMessageList.ERROR_MESSAGE_412_001, null, ErrorType.WARNING)),

	API_CONTEXT_VIOLATION_LANGUAGE(
			new RestError("business.412.003", BusinessErorMessageList.ERROR_MESSAGE_412_002, null, ErrorType.WARNING)),
	
	API_LANGUAGE_VIOLATION(
			new RestError("business.412.004", BusinessErorMessageList.ERROR_MESSAGE_412_003, null, ErrorType.WARNING)),

	API_MARKET_VIOLATION(
			new RestError("business.412.005", BusinessErorMessageList.ERROR_MESSAGE_412_004, null, ErrorType.WARNING)),

	API_INVALID_BUSINESS_RULE(new RestError("business.412.004", "Invalid business rule", null, ErrorType.WARNING)),

	API_UNKNOWN_BUSINESS_ERROR(new RestError("business.005", "Business unknown error", null, ErrorType.WARNING)),

	API_BUSINESS_ERROR(new RestError("business.1000", "Business error generated by backend", null, ErrorType.WARNING));;

	static Map<BusinessErrorList, RestError> enumMap = new EnumMap<>(BusinessErrorList.class);

	static {
		for (final BusinessErrorList element : values()) {
			enumMap.put(element, element.getError());
		}
	}

	

	public static void setEnumMap(final Map<BusinessErrorList, RestError> enumMap) {
		BusinessErrorList.enumMap = enumMap;
	}

	private RestError error;

	private BusinessErrorList(final RestError error) {
		this.error = error;
	}

	public RestError getError() {
		return error;
	}

}
