apiVersion: "apps/v1beta2"
kind: StatefulSet
metadata:
  name: neo4j-core
spec:
  podManagementPolicy: Parallel
  serviceName: neo4j-db
  replicas: 1
  selector:
    matchLabels:
      release: stable
      app: neo4j
      component: core
  template:
    metadata:
      labels:
        release: stable
        app: neo4j
        component: core
    spec:
      serviceAccountName: neo4j-toolbox-sa
      containers:
      - name: neo4j-db
        image: neo4j
        imagePullPolicy: "IfNotPresent"
        env:
          - name: NEO4J_USERNAME
            valueFrom:
              secretKeyRef:
                name: neo4j-secrets
                key: neo4j-username
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: neo4j-secrets
                key: neo4j-password
        command:
          - "/bin/bash"
          - "-c"
          - |
            export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
            export NEO4J_dbms_connectors_default__listen__address=0.0.0.0
            export NEO4J_dbms_tx__log_rotation_size=10M
            export NEO4J_dbms_tx__log_rotation_retention__policy="30 days"
            export NEO4J_AUTH="${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
            export NEO4J_dbms_memory_pagecache_size=512M
            export NEO4J_dbms_memory_heap_initial__size=512M
            export NEO4J_dbms_memory_heap_max__size=2G
            export NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
            export NEO4J_apoc_import_file_enabled=true
            export NEO4J_apoc_export_file_enabled=true
            exec /docker-entrypoint.sh "neo4j"
        ports:
        - containerPort: 5000
          name: discovery
        - containerPort: 7000
          name: raft
        - containerPort: 6000
          name: tx
        - containerPort: 7474
          name: browserhttp
        - containerPort: 7473
          name: browserhttps
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: datadir
          mountPath: /data
        - name: plugins
          mountPath: /plugins
        resources:
          requests:
            cpu: "200m"
            memory: "512M"
          limits:
            cpu: "8"
            memory: "8Gi"
      initContainers:
        - name: init-plugins
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: plugins
            mountPath: /plugins
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.4/apoc-3.5.0.4-all.jar -O 
              cp apoc-3.5.0.4-all.jar /plugins/
      volumes:
        - name: plugins
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "5Gi"