apiVersion: v1
kind: Service
metadata:
  name: neo4jbrowser
  namespace: repind
spec:
  type: NodePort
  ports:
  - name: http
    port: 7474
    nodePort: 30092
  - name: bolt
    port: 7687
    nodePort: 30093
  selector:
    app: neo4j
    component: core
    release: stable