apiVersion: v1
kind: Service
metadata:
  name: neo4j-db-readreplica-svc
  labels:
    release: stable
    app: neo4j
    component: readreplica
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: https
      protocol: TCP
      port: 7473
      targetPort: 7473
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  selector:
    app: neo4j
    release: stable
    component: readreplica