spring:
  config:
    activate:
      on-profile: AE,qal,acp
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@OSMN305.WORLD
    maxPoolSize: 2

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: qal
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

ri-search-gin-by-email:
  url: http://search-gin-by-email-acp:8080/
ri-search-gin-by-phone:
  url: http://search-gin-by-phone-acp:8080/
ri-search-gin-by-contract:
  url: http://search-gin-by-contract-acp:8080/
ri-search-gin-by-social-media:
  url: http://search-gin-by-social-media-acp:8080/
ri-search-gin-by-lastname-firstname:
  url: http://search-gin-by-lastname-firstname-acp:8080/


springdoc:
  enable-hateoas: false
