package com.afklm.rigui.entity.refTable;

public class RefTablePAYS extends RefTableMere {


	private static RefTablePAYS m_RefTablePAYS = null;

	public static final String _REF_AD = "AD";
	public static final String _REF_AE = "AE";
	public static final String _REF_AF = "AF";
	public static final String _REF_AG = "AG";
	public static final String _REF_AI = "AI";
	public static final String _REF_AL = "AL";
	public static final String _REF_AM = "AM";
	public static final String _REF_AN = "AN";
	public static final String _REF_AO = "AO";
	public static final String _REF_AQ = "AQ";
	public static final String _REF_AR = "AR";
	public static final String _REF_AS = "AS";
	public static final String _REF_AT = "AT";
	public static final String _REF_AU = "AU";
	public static final String _REF_AW = "AW";
	public static final String _REF_AX = "AX";
	public static final String _REF_AZ = "AZ";
	public static final String _REF_BA = "BA";
	public static final String _REF_BB = "BB";
	public static final String _REF_BD = "BD";
	public static final String _REF_BE = "BE";
	public static final String _REF_BF = "BF";
	public static final String _REF_BG = "BG";
	public static final String _REF_BH = "BH";
	public static final String _REF_BI = "BI";
	public static final String _REF_BJ = "BJ";
	public static final String _REF_BL = "BL";
	public static final String _REF_BM = "BM";
	public static final String _REF_BN = "BN";
	public static final String _REF_BO = "BO";
	public static final String _REF_BQ = "BQ";
	public static final String _REF_BR = "BR";
	public static final String _REF_BS = "BS";
	public static final String _REF_BT = "BT";
	public static final String _REF_BV = "BV";
	public static final String _REF_BW = "BW";
	public static final String _REF_BY = "BY";
	public static final String _REF_BZ = "BZ";
	public static final String _REF_CA = "CA";
	public static final String _REF_CC = "CC";
	public static final String _REF_CD = "CD";
	public static final String _REF_CE = "CE";
	public static final String _REF_CF = "CF";
	public static final String _REF_CG = "CG";
	public static final String _REF_CH = "CH";
	public static final String _REF_CI = "CI";
	public static final String _REF_CK = "CK";
	public static final String _REF_CL = "CL";
	public static final String _REF_CM = "CM";
	public static final String _REF_CN = "CN";
	public static final String _REF_CO = "CO";
	public static final String _REF_CR = "CR";
	public static final String _REF_CS = "CS";
	public static final String _REF_CU = "CU";
	public static final String _REF_CV = "CV";
	public static final String _REF_CW = "CW";
	public static final String _REF_CX = "CX";
	public static final String _REF_CY = "CY";
	public static final String _REF_CZ = "CZ";
	public static final String _REF_DE = "DE";
	public static final String _REF_DJ = "DJ";
	public static final String _REF_DK = "DK";
	public static final String _REF_DM = "DM";
	public static final String _REF_DO = "DO";
	public static final String _REF_DZ = "DZ";
	public static final String _REF_EC = "EC";
	public static final String _REF_EE = "EE";
	public static final String _REF_EG = "EG";
	public static final String _REF_EH = "EH";
	public static final String _REF_ER = "ER";
	public static final String _REF_ES = "ES";
	public static final String _REF_ET = "ET";
	public static final String _REF_FI = "FI";
	public static final String _REF_FJ = "FJ";
	public static final String _REF_FK = "FK";
	public static final String _REF_FM = "FM";
	public static final String _REF_FO = "FO";
	public static final String _REF_FR = "FR";
	public static final String _REF_GA = "GA";
	public static final String _REF_GB = "GB";
	public static final String _REF_GD = "GD";
	public static final String _REF_GE = "GE";
	public static final String _REF_GF = "GF";
	public static final String _REF_GG = "GG";
	public static final String _REF_GH = "GH";
	public static final String _REF_GI = "GI";
	public static final String _REF_GL = "GL";
	public static final String _REF_GM = "GM";
	public static final String _REF_GN = "GN";
	public static final String _REF_GP = "GP";
	public static final String _REF_GQ = "GQ";
	public static final String _REF_GR = "GR";
	public static final String _REF_GS = "GS";
	public static final String _REF_GT = "GT";
	public static final String _REF_GU = "GU";
	public static final String _REF_GW = "GW";
	public static final String _REF_GY = "GY";
	public static final String _REF_HK = "HK";
	public static final String _REF_HM = "HM";
	public static final String _REF_HN = "HN";
	public static final String _REF_HR = "HR";
	public static final String _REF_HT = "HT";
	public static final String _REF_HU = "HU";
	public static final String _REF_ID = "ID";
	public static final String _REF_IE = "IE";
	public static final String _REF_IL = "IL";
	public static final String _REF_IM = "IM";
	public static final String _REF_IN = "IN";
	public static final String _REF_IO = "IO";
	public static final String _REF_IQ = "IQ";
	public static final String _REF_IR = "IR";
	public static final String _REF_IS = "IS";
	public static final String _REF_IT = "IT";
	public static final String _REF_JE = "JE";
	public static final String _REF_JM = "JM";
	public static final String _REF_JO = "JO";
	public static final String _REF_JP = "JP";
	public static final String _REF_KE = "KE";
	public static final String _REF_KG = "KG";
	public static final String _REF_KH = "KH";
	public static final String _REF_KI = "KI";
	public static final String _REF_KM = "KM";
	public static final String _REF_KN = "KN";
	public static final String _REF_KP = "KP";
	public static final String _REF_KR = "KR";
	public static final String _REF_KW = "KW";
	public static final String _REF_KY = "KY";
	public static final String _REF_KZ = "KZ";
	public static final String _REF_LA = "LA";
	public static final String _REF_LB = "LB";
	public static final String _REF_LC = "LC";
	public static final String _REF_LI = "LI";
	public static final String _REF_LK = "LK";
	public static final String _REF_LR = "LR";
	public static final String _REF_LS = "LS";
	public static final String _REF_LT = "LT";
	public static final String _REF_LU = "LU";
	public static final String _REF_LV = "LV";
	public static final String _REF_LY = "LY";
	public static final String _REF_M1 = "M1";
	public static final String _REF_MA = "MA";
	public static final String _REF_MC = "MC";
	public static final String _REF_MD = "MD";
	public static final String _REF_ME = "ME";
	public static final String _REF_MF = "MF";
	public static final String _REF_MG = "MG";
	public static final String _REF_MH = "MH";
	public static final String _REF_MK = "MK";
	public static final String _REF_ML = "ML";
	public static final String _REF_MM = "MM";
	public static final String _REF_MN = "MN";
	public static final String _REF_MO = "MO";
	public static final String _REF_MP = "MP";
	public static final String _REF_MQ = "MQ";
	public static final String _REF_MR = "MR";
	public static final String _REF_MS = "MS";
	public static final String _REF_MT = "MT";
	public static final String _REF_MU = "MU";
	public static final String _REF_MV = "MV";
	public static final String _REF_MW = "MW";
	public static final String _REF_MX = "MX";
	public static final String _REF_MY = "MY";
	public static final String _REF_MZ = "MZ";
	public static final String _REF_NA = "NA";
	public static final String _REF_NC = "NC";
	public static final String _REF_NE = "NE";
	public static final String _REF_NF = "NF";
	public static final String _REF_NG = "NG";
	public static final String _REF_NI = "NI";
	public static final String _REF_NL = "NL";
	public static final String _REF_NO = "NO";
	public static final String _REF_NP = "NP";
	public static final String _REF_NR = "NR";
	public static final String _REF_NU = "NU";
	public static final String _REF_NZ = "NZ";
	public static final String _REF_OM = "OM";
	public static final String _REF_PA = "PA";
	public static final String _REF_PE = "PE";
	public static final String _REF_PF = "PF";
	public static final String _REF_PG = "PG";
	public static final String _REF_PH = "PH";
	public static final String _REF_PK = "PK";
	public static final String _REF_PL = "PL";
	public static final String _REF_PM = "PM";
	public static final String _REF_PN = "PN";
	public static final String _REF_PR = "PR";
	public static final String _REF_PS = "PS";
	public static final String _REF_PT = "PT";
	public static final String _REF_PW = "PW";
	public static final String _REF_PY = "PY";
	public static final String _REF_QA = "QA";
	public static final String _REF_RE = "RE";
	public static final String _REF_RO = "RO";
	public static final String _REF_RS = "RS";
	public static final String _REF_RU = "RU";
	public static final String _REF_RW = "RW";
	public static final String _REF_SA = "SA";
	public static final String _REF_SB = "SB";
	public static final String _REF_SC = "SC";
	public static final String _REF_SD = "SD";
	public static final String _REF_SE = "SE";
	public static final String _REF_SG = "SG";
	public static final String _REF_SH = "SH";
	public static final String _REF_SI = "SI";
	public static final String _REF_SJ = "SJ";
	public static final String _REF_SK = "SK";
	public static final String _REF_SL = "SL";
	public static final String _REF_SM = "SM";
	public static final String _REF_SN = "SN";
	public static final String _REF_SO = "SO";
	public static final String _REF_SR = "SR";
	public static final String _REF_SS = "SS";
	public static final String _REF_ST = "ST";
	public static final String _REF_SV = "SV";
	public static final String _REF_SX = "SX";
	public static final String _REF_SY = "SY";
	public static final String _REF_SZ = "SZ";
	public static final String _REF_TC = "TC";
	public static final String _REF_TD = "TD";
	public static final String _REF_TF = "TF";
	public static final String _REF_TG = "TG";
	public static final String _REF_TH = "TH";
	public static final String _REF_TJ = "TJ";
	public static final String _REF_TK = "TK";
	public static final String _REF_TL = "TL";
	public static final String _REF_TM = "TM";
	public static final String _REF_TN = "TN";
	public static final String _REF_TO = "TO";
	public static final String _REF_TP = "TP";
	public static final String _REF_TR = "TR";
	public static final String _REF_TT = "TT";
	public static final String _REF_TV = "TV";
	public static final String _REF_TW = "TW";
	public static final String _REF_TZ = "TZ";
	public static final String _REF_UA = "UA";
	public static final String _REF_UG = "UG";
	public static final String _REF_UM = "UM";
	public static final String _REF_US = "US";
	public static final String _REF_UY = "UY";
	public static final String _REF_UZ = "UZ";
	public static final String _REF_VA = "VA";
	public static final String _REF_VC = "VC";
	public static final String _REF_VE = "VE";
	public static final String _REF_VG = "VG";
	public static final String _REF_VI = "VI";
	public static final String _REF_VN = "VN";
	public static final String _REF_VU = "VU";
	public static final String _REF_WF = "WF";
	public static final String _REF_WS = "WS";
	public static final String _REF_XA = "XA";
	public static final String _REF_XK = "XK";
	public static final String _REF_XU = "XU";
	public static final String _REF_YE = "YE";
	public static final String _REF_YT = "YT";
	public static final String _REF_ZA = "ZA";
	public static final String _REF_ZM = "ZM";
	public static final String _REF_ZW = "ZW";
	public static final String _REF_ZZ = "ZZ";

	public static final String TIMOR_LESTE = "TIMOR LESTE";

	private RefTablePAYS() {

		m_lstChamps.add(new RefTableChamp(_REF_AD, "ANDORRE", "ANDORRA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AE, "EMIRATS ARABES UNIS", "UNITED ARAB EMIRATES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AF, "AFGHANISTAN", "AFGHANISTAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AG, "ANTIGUA ET BARBUDA", "ANTIGUA AND BARBUDA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AI, "ANGUILLA", "ANGUILLA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AL, "ALBANIE", "ALBANIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AM, "ARMENIE", "ARMENIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AN, "ANTILLES NEERLANDAISES", "NETHERLANDS ANTILLES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AO, "ANGOLA", "ANGOLA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AQ, "ANTARCTIQUE", "ANTARCTICA", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_AR, "ARGENTINE", "ARGENTINA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AS, "SAMOA AMERICAINES", "AMERICAN SAMOA", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_AT, "AUTRICHE", "AUSTRIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AU, "AUSTRALIE", "AUSTRALIA", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_AW, "ARUBA", "ARUBA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AX, "ILES ALAND", "ALAND ISLANDS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_AZ, "AZERBAIDJAN", "AZERBAIJAN", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_BA, "BOSNIE HERZEGOVINE", "BOSNIA AND HERZEGOVINA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BB, "BARBADE", "BARBADOS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BD, "BANGLADESH", "BANGLADESH", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_BE, "BELGIQUE", "BELGIUM", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BF, "BURKINA FASO", "BURKINA FASO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BG, "BULGARIE", "BULGARIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BH, "BAHREIN", "BAHRAIN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_BI, "BURUNDI", "BURUNDI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BJ, "BENIN", "BENIN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BL, "SAINT BARTHELEMY", "SAINT BARTHELEMY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BM, "BERMUDES", "BERMUDA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_BN, "BRUNEI DARUSSALAM", "BRUNEI DARUSSALAM", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_BO, "BOLIVIE", "BOLIVIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BQ, "BONAIRE, ST EUSTACHE ET SABA", "BONAIRE, ST EUSTATIUS AND SABA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BR, "BRESIL", "BRAZIL", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_BS, "BAHAMAS", "BAHAMAS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BT, "BHOUTAN", "BHUTAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BV, "BOUVET, ILE", "BOUVET ISLAND", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BW, "BOTSWANA", "BOTSWANA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BY, "BELARUS", "BELARUS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_BZ, "BELIZE", "BELIZE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CA, "CANADA", "CANADA", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_CC, "COCOS (KEELING), ILES", "COCOS (KEELING) ISLANDS", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_CD, "CONGO, LA REP. DEMOCRATIQUE DU", "CONGO, DEMOCRATIC REP. OF THE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CE, "DON T USE---> COMMUNAUTE EUR.", "DON T USE---> EUR. COMMUNITY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CF, "CENTRAFRICAINE, REPUBLIQUE", "CENTRAL AFRICAN REPUBLIC", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CG, "CONGO", "CONGO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CH, "SUISSE", "SWITZERLAND", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CI, "COTE D IVOIRE", "IVORY COAST", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CK, "COOK, ILES", "COOK ISLANDS", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_CL, "CHILI", "CHILE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CM, "CAMEROUN", "CAMEROON", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CN, "CHINE", "CHINA", "7"));
		m_lstChamps.add(new RefTableChamp(_REF_CO, "COLOMBIE", "COLOMBIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CR, "COSTA RICA", "COSTA RICA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CS, "NE PAS UTILISER", "DO NOT USE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CU, "CUBA", "CUBA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CV, "CAP VERT", "CAPE VERDE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CW, "CURACAO", "CURACAO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CX, "CHRISTMAS, ILE", "CHRISTMAS ISLAND", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_CY, "CHYPRE", "CYPRUS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_CZ, "TCHEQUE, REPUBLIQUE", "CZECH REPUBLIC", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DE, "ALLEMAGNE", "GERMANY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DJ, "DJIBOUTI", "DJIBOUTI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DK, "DANEMARK", "DENMARK", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DM, "DOMINIQUE", "DOMINICA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DO, "DOMINICAINE, REPUBLIQUE", "DOMINICAN REPUBLIC", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_DZ, "ALGERIE", "ALGERIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_EC, "EQUATEUR", "ECUADOR", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_EE, "ESTONIE", "ESTONIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_EG, "EGYPTE", "EGYPT", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_EH, "SAHARA OCCIDENTAL", "WESTERN SAHARA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ER, "ERYTHREE", "ERITREA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ES, "ESPAGNE", "SPAIN", "6"));
		m_lstChamps.add(new RefTableChamp(_REF_ET, "ETHIOPIE", "ETHIOPIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_FI, "FINLANDE", "FINLAND", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_FJ, "FIDJI", "FIJI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_FK, "FALKLAND, ILES (MALVINAS)", "FALKLAND ISLANDS (MALVINAS)", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_FM, "MICRONESIE, ETATS FEDERES DE", "MICRONESIA, FED. STATES OF", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_FO, "FEROE, ILES", "FAROE ISLANDS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_FR, "FRANCE", "FRANCE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GA, "GABON", "GABON", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GB, "ROYAUME UNI", "UNITED KINGDOM", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_GD, "GRENADE", "GRENADA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GE, "GEORGIE", "GEORGIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GF, "GUYANE FRANCAISE", "FRENCH GUIANA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GG, "GUERNESEY", "GUERNSEY", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_GH, "GHANA", "GHANA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GI, "GIBRALTAR", "GIBRALTAR", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_GL, "GROENLAND", "GREENLAND", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GM, "GAMBIE", "GAMBIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GN, "GUINEE", "GUINEA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GP, "GUADELOUPE", "GUADELOUPE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GQ, "GUINEE EQUATORIALE", "EQUATORIAL GUINEA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GR, "GRECE", "GREECE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GS, "GEORGIE DU SUD,ILES SANDWICH", "SOUTH GEORGIA,SANDWICH ISLANDS", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_GT, "GUATEMALA", "GUATEMALA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GU, "GUAM", "GUAM", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_GW, "GUINEE BISSAU", "GUINEA BISSAU", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_GY, "GUYANA", "GUYANA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_HK, "HONG KONG", "HONG KONG", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_HM, "HEARD, ILE ET MCDONALD, ILES", "HEARD ISLAND, MCDONALD ISLANDS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_HN, "HONDURAS", "HONDURAS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_HR, "CROATIE", "CROATIA", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_HT, "HAITI", "HAITI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_HU, "HONGRIE", "HUNGARY", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_ID, "INDONESIE", "INDONESIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IE, "IRLANDE", "IRELAND", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IL, "ISRAEL", "ISRAEL", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_IM, "ILE DE MAN", "ISLE OF MAN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IN, "INDE", "INDIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IO, "OCEAN INDIEN, TER. BRITANNIQUE", "BRITISH INDIAN OCEAN TERRITORY", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IQ, "IRAQ", "IRAQ", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_IR, "IRAN, REPUBLIQUE ISLAMIQUE D", "IRAN, ISLAMIC REPUBLIC OF", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_IS, "ISLANDE", "ICELAND", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_IT, "ITALIE", "ITALY", "6"));
		m_lstChamps.add(new RefTableChamp(_REF_JE, "JERSEY", "JERSEY", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_JM, "JAMAIQUE", "JAMAICA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_JO, "JORDANIE", "JORDAN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_JP, "JAPON", "JAPAN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KE, "KENYA", "KENYA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KG, "KIRGHIZISTAN", "KYRGYZSTAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_KH, "CAMBODGE", "CAMBODIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KI, "KIRIBATI", "KIRIBATI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_KM, "COMORES", "COMOROS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_KN, "SAINT KITTS ET NEVIS", "SAINT KITTS AND NEVIS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_KP, "COREE, REP. POPULAIRE DEM. DE", "KOREA, DEM. PEOPLE S REP. OF", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KR, "COREE, REPUBLIQUE DE", "KOREA, REPUBLIC OF", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KW, "KOWEIT", "KUWAIT", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_KY, "CAIMANES, ILES", "CAYMAN ISLANDS", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_KZ, "KAZAKHSTAN", "KAZAKHSTAN", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_LA, "LAO, REP. DEM. POPULAIRE", "LAO PEOPLE S DEMOCRATIC REP.", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_LB, "LIBAN", "LEBANON", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_LC, "SAINTE LUCIE", "SAINT LUCIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_LI, "LIECHTENSTEIN", "LIECHTENSTEIN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_LK, "SRI LANKA", "SRI LANKA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_LR, "LIBERIA", "LIBERIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_LS, "LESOTHO", "LESOTHO", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_LT, "LITUANIE", "LITHUANIA", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_LU, "LUXEMBOURG", "LUXEMBOURG", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_LV, "LETTONIE", "LATVIA", "5"));
		m_lstChamps.add(new RefTableChamp(_REF_LY, "LIBYENNE, JAMAHIRIYA ARABE", "LIBYAN ARAB JAMAHIRIYA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_M1, "MONDE", "WORLD", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MA, "MAROC", "MOROCCO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MC, "MONACO", "MONACO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MD, "MOLDOVA, REPUBLIQUE DE", "MOLDOVA, REPUBLIC OF", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_ME, "MONTENEGRO", "MONTENEGRO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MF, "SAINT MARTIN", "SAINT MARTEEN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MG, "MADAGASCAR", "MADAGASCAR", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MH, "MARSHALL, ILES", "MARSHALL ISLANDS", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_MK, "MACEDOINE, EX REP. YOUGOSLAVE", "MACEDONIA,FORMER YUGOSLAV REP.", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ML, "MALI", "MALI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MM, "MYANMAR", "MYANMAR", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_MN, "MONGOLIE", "MONGOLIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_MO, "MACAO", "MACAO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MP, "MARIANNES DU NORD, ILES", "NORTHERN MARIANA ISLANDS", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_MQ, "MARTINIQUE", "MARTINIQUE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MR, "MAURITANIE", "MAURITANIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MS, "MONTSERRAT", "MONTSERRAT", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MT, "MALTE", "MALTA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_MU, "MAURICE", "MAURITIUS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MV, "MALDIVES", "MALDIVES", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_MW, "MALAWI", "MALAWI", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MX, "MEXIQUE", "MEXICO", "6"));
		m_lstChamps.add(new RefTableChamp(_REF_MY, "MALAISIE", "MALAYSIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_MZ, "MOZAMBIQUE", "MOZAMBIQUE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NA, "NAMIBIE", "NAMIBIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NC, "NOUVELLE CALEDONIE", "NEW CALEDONIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NE, "NIGER", "NIGER", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NF, "NORFOLK, ILE", "NORFOLK ISLAND", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_NG, "NIGERIA", "NIGERIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_NI, "NICARAGUA", "NICARAGUA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NL, "PAYS BAS", "NETHERLANDS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NO, "NORVEGE", "NORWAY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NP, "NEPAL", "NEPAL", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_NR, "NAURU", "NAURU", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_NU, "NIUE", "NIUE", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_NZ, "NOUVELLE ZELANDE", "NEW ZEALAND", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_OM, "OMAN", "OMAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PA, "PANAMA", "PANAMA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PE, "PEROU", "PERU", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PF, "POLYNESIE FRANCAISE", "FRENCH POLYNESIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PG, "PAPOUASIE NOUVELLE GUINEE", "PAPUA NEW GUINEA", "7"));
		m_lstChamps.add(new RefTableChamp(_REF_PH, "PHILIPPINES", "PHILIPPINES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PK, "PAKISTAN", "PAKISTAN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_PL, "POLOGNE", "POLAND", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PM, "SAINT PIERRE ET MIQUELON", "SAINT PIERRE AND MIQUELON", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PN, "PITCAIRN", "PITCAIRN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_PR, "PORTO RICO", "PUERTO RICO", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_PS, "PALESTINIEN OCCUPE, TERRITOIRE", "PALESTINIAN TERRITORY,OCCUPIED", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PT, "PORTUGAL", "PORTUGAL", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_PW, "PALAOS", "PALAU", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_PY, "PARAGUAY", "PARAGUAY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_QA, "QATAR", "QATAR", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_RE, "REUNION", "REUNION", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_RO, "ROUMANIE", "ROMANIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_RS, "SERBIE", "SERBIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_RU, "RUSSIE, FEDERATION DE", "RUSSIAN FEDERATION", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_RW, "RWANDA", "RWANDA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SA, "ARABIE SAOUDITE", "SAUDI ARABIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_SB, "SALOMON, ILES", "SOLOMON ISLANDS", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SC, "SEYCHELLES", "SEYCHELLES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SD, "SOUDAN", "SUDAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SE, "SUEDE", "SWEDEN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SG, "SINGAPOUR", "SINGAPORE", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_SH, "SAINTE HELENE", "SAINT HELENA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_SI, "SLOVENIE", "SLOVENIA", "4"));
		m_lstChamps.add(new RefTableChamp(_REF_SJ, "SVALBARD ET ILE JAN MAYEN", "SVALBARD AND JAN MAYEN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SK, "SLOVAQUIE", "SLOVAKIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SL, "SIERRA LEONE", "SIERRA LEONE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SM, "SAINT MARIN", "SAN MARINO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SN, "SENEGAL", "SENEGAL", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SO, "SOMALIE", "SOMALIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_SR, "SURINAME", "SURINAME", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SS, "SUD SOUDAN", "SOUTH SUDAN", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_ST, "SAO TOME ET PRINCIPE", "SAO TOME AND PRINCIPE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SV, "EL SALVADOR", "EL SALVADOR", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SX, "SAINT MAARTIN", "SAINT MAARTEN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SY, "SYRIENNE, REPUBLIQUE ARABE", "SYRIAN ARAB REPUBLIC", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_SZ, "SWAZILAND", "SWAZILAND", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_TC, "TURKS ET CAIQUES, ILES", "TURKS AND CAICOS ISLANDS", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_TD, "TCHAD", "CHAD", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TF, "TERRES AUSTRALES FRANCAISES", "FRENCH SOUTHERN TERRITORIES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TG, "TOGO", "TOGO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TH, "THAILANDE", "THAILAND", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_TJ, "TADJIKISTAN", "TAJIKISTAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TK, "TOKELAU", "TOKELAU", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_TL, TIMOR_LESTE, TIMOR_LESTE, "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TM, "TURKMENISTAN", "TURKMENISTAN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TN, "TUNISIE", "TUNISIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TO, "TONGA", "TONGA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TP, TIMOR_LESTE, TIMOR_LESTE, "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TR, "TURQUIE", "TURKEY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TT, "TRINITE ET TOBAGO", "TRINIDAD AND TOBAGO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TV, "TUVALU", "TUVALU", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TW, "TAIWAN, PROVINCE DE CHINE", "TAIWAN, PROVINCE OF CHINA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_TZ, "TANZANIE, REPUBLIQUE UNIE DE", "TANZANIA, UNITED REPUBLIC OF", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_UA, "UKRAINE", "UKRAINE", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_UG, "OUGANDA", "UGANDA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_UM, "ILES MINEURES ELOIGNEES DES US", "US MINOR OUTLYING ISLANDS", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_US, "ETATS UNIS", "UNITED STATES", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_UY, "URUGUAY", "URUGUAY", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_UZ, "OUZBEKISTAN", "UZBEKISTAN", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_VA, "SAINT SIEGE (CITE DU VATICAN)", "HOLY SEE (VATICAN CITY STATE)", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_VC, "SAINT VINCENT ET GRENADINES", "SAINT VINCENT AND GRENADINES", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_VE, "VENEZUELA", "VENEZUELA", "8"));
		m_lstChamps.add(new RefTableChamp(_REF_VG, "ILES VIERGES BRITANNIQUES", "VIRGIN ISLANDS, BRITISH", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_VI, "ILES VIERGES DES ETATS UNIS", "VIRGIN ISLANDS, U.S.", "3"));
		m_lstChamps.add(new RefTableChamp(_REF_VN, "VIET NAM", "VIET NAM", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_VU, "VANUATU", "VANUATU", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_WF, "WALLIS ET FUTUNA", "WALLIS AND FUTUNA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_WS, "SAMOA", "SAMOA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_XA, "DON T USE---> GAZA", "DON T USE--->", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_XK, "KOSOVO", "KOSOVO", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_XU, "DON T USE---> RUSSIE", "DON T USE---> RUSSIA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_YE, "YEMEN", "YEMEN", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_YT, "MAYOTTE", "MAYOTTE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ZA, "AFRIQUE DU SUD", "SOUTH AFRICA", "2"));
		m_lstChamps.add(new RefTableChamp(_REF_ZM, "ZAMBIE", "ZAMBIA", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ZW, "ZIMBABWE", "ZIMBABWE", "1"));
		m_lstChamps.add(new RefTableChamp(_REF_ZZ, "DON T USE---> UNKNOWN COUNTRY", "DON T USE--->", "1"));
	}

	public static RefTablePAYS instance() {
		if (null == m_RefTablePAYS) {
			m_RefTablePAYS = new RefTablePAYS();
		}
		return m_RefTablePAYS;
	}


}
