package com.afklm.rigui.entity.refTable;

public class RefTableREF_ERREUR extends RefTableMere {


	private static RefTableREF_ERREUR m_RefTableREF_ERREUR = null;

	public static final String _REF_000 = "000";
	public static final String _REF_001 = "001";
	public static final String _REF_002 = "002"; 
	public static final String _REF_003 = "003";
	public static final String _REF_004 = "004";
	public static final String _REF_006 = "006";
	public static final String _REF_100 = "100";
	public static final String _REF_101 = "101";
	public static final String _REF_102 = "102";
	public static final String _REF_103 = "103";
	public static final String _REF_104 = "104";
	public static final String _REF_105 = "105";
	public static final String _REF_106 = "106";
	public static final String _REF_107 = "107";
	public static final String _REF_108 = "108";
	public static final String _REF_109 = "109";
	public static final String _REF_110 = "110";
	public static final String _REF_111 = "111";
	public static final String _REF_112 = "112";
	public static final String _REF_113 = "113";
	public static final String _REF_114 = "114";
	public static final String _REF_115 = "115";
	public static final String _REF_116 = "116";
	public static final String _REF_117 = "117";
	public static final String _REF_118 = "118";
	public static final String _REF_119 = "119";
	public static final String _REF_120 = "120";
	public static final String _REF_121 = "121";
	public static final String _REF_122 = "122";
	public static final String _REF_123 = "123";
	public static final String _REF_124 = "124";
	public static final String _REF_125 = "125";
	public static final String _REF_126 = "126";
	public static final String _REF_127 = "127";
	public static final String _REF_128 = "128";
	public static final String _REF_129 = "129";
	public static final String _REF_130 = "130";
	public static final String _REF_131 = "131";
	public static final String _REF_132 = "132";
	public static final String _REF_133 = "133";
	public static final String _REF_134 = "134";
	public static final String _REF_135 = "135";
	public static final String _REF_136 = "136";
	public static final String _REF_137 = "137";
	public static final String _REF_138 = "138";
	public static final String _REF_139 = "139";
	public static final String _REF_140 = "140";
	public static final String _REF_141 = "141";
	public static final String _REF_142 = "142";
	public static final String _REF_143 = "143";
	public static final String _REF_144 = "144";
	public static final String _REF_145 = "145";
	public static final String _REF_146 = "146";
	public static final String _REF_147 = "147";
	public static final String _REF_148 = "148";
	public static final String _REF_149 = "149";
	public static final String _REF_150 = "150";
	public static final String _REF_151 = "151";
	public static final String _REF_152 = "152";
	public static final String _REF_153 = "153";
	public static final String _REF_154 = "154";
	public static final String _REF_155 = "155";
	public static final String _REF_156 = "156";
	public static final String _REF_157 = "157";
	public static final String _REF_158 = "158";
	public static final String _REF_159 = "159";
	public static final String _REF_160 = "160";
	public static final String _REF_161 = "161";
	public static final String _REF_162 = "162";
	public static final String _REF_163 = "163";
	public static final String _REF_164 = "164";
	public static final String _REF_165 = "165";
	public static final String _REF_166 = "166";
	public static final String _REF_167 = "167";
	public static final String _REF_168 = "168";
	public static final String _REF_169 = "169";
	public static final String _REF_170 = "170";
	public static final String _REF_171 = "171";
	public static final String _REF_172 = "172";
	public static final String _REF_173 = "173";
	public static final String _REF_174 = "174";
	public static final String _REF_175 = "175";
	public static final String _REF_176 = "176";
	public static final String _REF_177 = "177";
	public static final String _REF_178 = "178";
	public static final String _REF_179 = "179";
	public static final String _REF_180 = "180";
	public static final String _REF_181 = "181";
	public static final String _REF_182 = "182";
	public static final String _REF_183 = "183";
	public static final String _REF_184 = "184";
	public static final String _REF_185 = "185";
	public static final String _REF_186 = "186";
	public static final String _REF_187 = "187";
	public static final String _REF_188 = "188";
	public static final String _REF_189 = "189";
	public static final String _REF_190 = "190";
	public static final String _REF_191 = "191";
	public static final String _REF_192 = "192";
	public static final String _REF_193 = "193";
	public static final String _REF_194 = "194";
	public static final String _REF_195 = "195";
	public static final String _REF_196 = "196";
	public static final String _REF_197 = "197";
	public static final String _REF_198 = "198";
	public static final String _REF_199 = "199";
	public static final String _REF_200 = "200";
	public static final String _REF_201 = "201";
	public static final String _REF_202 = "202";
	public static final String _REF_203 = "203";
	public static final String _REF_204 = "204";
	public static final String _REF_205 = "205";
	public static final String _REF_206 = "206";
	public static final String _REF_207 = "207";
	public static final String _REF_208 = "208";
	public static final String _REF_209 = "209";
	public static final String _REF_210 = "210";
	public static final String _REF_211 = "211";
	public static final String _REF_212 = "212";
	public static final String _REF_213 = "213";
	public static final String _REF_214 = "214";
	public static final String _REF_215 = "215";
	public static final String _REF_216 = "216";
	public static final String _REF_217 = "217";
	public static final String _REF_218 = "218";
	public static final String _REF_219 = "219";
	public static final String _REF_220 = "220";
	public static final String _REF_221 = "221";
	public static final String _REF_222 = "222";
	public static final String _REF_223 = "223";
	public static final String _REF_224 = "224";
	public static final String _REF_225 = "225";
	public static final String _REF_226 = "226";
	public static final String _REF_227 = "227";
	public static final String _REF_228 = "228";
	public static final String _REF_229 = "229";
	public static final String _REF_230 = "230";
	public static final String _REF_231 = "231";
	public static final String _REF_232 = "232";
	public static final String _REF_233 = "233";
	public static final String _REF_234 = "234";
	public static final String _REF_235 = "235";
	public static final String _REF_236 = "236";
	public static final String _REF_237 = "237";
	public static final String _REF_238 = "238";
	public static final String _REF_239 = "239";
	public static final String _REF_240 = "240";
	public static final String _REF_241 = "241";
	public static final String _REF_242 = "242";
	public static final String _REF_243 = "243";
	public static final String _REF_244 = "244";
	public static final String _REF_245 = "245";
	public static final String _REF_246 = "246";
	public static final String _REF_250 = "250";
	public static final String _REF_251 = "251";
	public static final String _REF_252 = "252";
	public static final String _REF_253 = "253";
	public static final String _REF_254 = "254";
	public static final String _REF_255 = "255";
	public static final String _REF_256 = "256";
	public static final String _REF_257 = "257";
	public static final String _REF_258 = "258";
	public static final String _REF_259 = "259";
	public static final String _REF_260 = "260";
	public static final String _REF_261 = "261";
	public static final String _REF_262 = "262";
	public static final String _REF_263 = "263";
	public static final String _REF_264 = "264";
	public static final String _REF_265 = "265";
	public static final String _REF_266 = "266";
	public static final String _REF_267 = "267";
	public static final String _REF_268 = "268";
	public static final String _REF_269 = "269";
	public static final String _REF_272 = "272";
	public static final String _REF_274 = "274";
	public static final String _REF_275 = "275";
	public static final String _REF_277 = "277";
	public static final String _REF_278 = "278";
	public static final String _REF_279 = "279";
	public static final String _REF_280 = "280";
	public static final String _REF_281 = "281";
	public static final String _REF_282 = "282";
	public static final String _REF_283 = "283";
	public static final String _REF_284 = "284";
	public static final String _REF_285 = "285";
	public static final String _REF_286 = "286";
	public static final String _REF_287 = "287";
	public static final String _REF_288 = "288";
	public static final String _REF_289 = "289";
	public static final String _REF_290 = "290";
	public static final String _REF_291 = "291";
	public static final String _REF_299 = "299";
	public static final String _REF_300 = "300";
	public static final String _REF_301 = "301";
	public static final String _REF_302 = "302";
	public static final String _REF_303 = "303";
	public static final String _REF_304 = "304";
	public static final String _REF_305 = "305";
	public static final String _REF_306 = "306";
	public static final String _REF_307 = "307";
	public static final String _REF_308 = "308";
	public static final String _REF_309 = "309";
	public static final String _REF_310 = "310";
	public static final String _REF_311 = "311";
	public static final String _REF_312 = "312";
	public static final String _REF_313 = "313";
	public static final String _REF_314 = "314";
	public static final String _REF_315 = "315";
	public static final String _REF_316 = "316";
	public static final String _REF_317 = "317";
	public static final String _REF_318 = "318";
	public static final String _REF_319 = "319";
	public static final String _REF_320 = "320";
	public static final String _REF_321 = "321";
	public static final String _REF_322 = "322";
	public static final String _REF_323 = "323";
	public static final String _REF_324 = "324";
	public static final String _REF_325 = "325";
	public static final String _REF_326 = "326";
	public static final String _REF_327 = "327";
	public static final String _REF_328 = "328";
	public static final String _REF_329 = "329";
	public static final String _REF_330 = "330";
	public static final String _REF_331 = "331";
	public static final String _REF_332 = "332";
	public static final String _REF_333 = "333";
	public static final String _REF_334 = "334";
	public static final String _REF_335 = "335";
	public static final String _REF_337 = "337";
	public static final String _REF_338 = "338";
	public static final String _REF_339 = "339";
	public static final String _REF_340 = "340";
	public static final String _REF_341 = "341";
	public static final String _REF_342 = "342";
	public static final String _REF_343 = "343";
	public static final String _REF_344 = "344";
	public static final String _REF_345 = "345";
	public static final String _REF_346 = "346";
	public static final String _REF_347 = "347";
	public static final String _REF_348 = "348";
	public static final String _REF_349 = "349";
	public static final String _REF_350 = "350";
	public static final String _REF_351 = "351";
	public static final String _REF_352 = "352";
	public static final String _REF_353 = "353";
	public static final String _REF_354 = "354";
	public static final String _REF_355 = "355";
	public static final String _REF_356 = "356";
	public static final String _REF_357 = "357";
	public static final String _REF_358 = "358";
	public static final String _REF_359 = "359";
	public static final String _REF_360 = "360";
	public static final String _REF_361 = "361";
	public static final String _REF_362 = "362";
	public static final String _REF_363 = "363";
	public static final String _REF_364 = "364";
	public static final String _REF_365 = "365";
	public static final String _REF_366 = "366";
	public static final String _REF_367 = "367";
	public static final String _REF_368 = "368";
	public static final String _REF_369 = "369";
	public static final String _REF_370 = "370";
	public static final String _REF_371 = "371";
	public static final String _REF_372 = "372";
	public static final String _REF_373 = "373";
	public static final String _REF_374 = "374";
	public static final String _REF_375 = "375";
	public static final String _REF_376 = "376";
	public static final String _REF_377 = "377";
	public static final String _REF_378 = "378";
	public static final String _REF_379 = "379";
	public static final String _REF_380 = "380";
	public static final String _REF_381 = "381";
	public static final String _REF_382 = "382";
	public static final String _REF_383 = "383";
	public static final String _REF_384 = "384";
	public static final String _REF_385 = "385";
	public static final String _REF_386 = "386";
	public static final String _REF_387 = "387";
	public static final String _REF_388 = "388";
	public static final String _REF_389 = "389";
	public static final String _REF_390 = "390";
	public static final String _REF_511 = "511";
	public static final String _REF_512 = "512";
	public static final String _REF_515 = "515";
	public static final String _REF_516 = "516";
	public static final String _REF_517 = "517";
	public static final String _REF_521 = "521";
	public static final String _REF_522 = "522";
	public static final String _REF_526 = "526";
	public static final String _REF_530 = "530";
	public static final String _REF_531 = "531";
	public static final String _REF_532 = "532";
	public static final String _REF_533 = "533";
	public static final String _REF_534 = "534";
	public static final String _REF_535 = "535";
	public static final String _REF_536 = "536";
	public static final String _REF_537 = "537";
	public static final String _REF_539 = "539";
	public static final String _REF_551 = "551";
	public static final String _REF_600 = "600";
	public static final String _REF_601 = "601";
	public static final String _REF_602 = "602";
	public static final String _REF_603 = "603";
	public static final String _REF_604 = "604";
	public static final String _REF_605 = "605";
	public static final String _REF_606 = "606";
	public static final String _REF_607 = "607";
	public static final String _REF_608 = "608";
	public static final String _REF_609 = "609";
	public static final String _REF_610 = "610";
	public static final String _REF_611 = "611";
	public static final String _REF_612 = "612";
	public static final String _REF_613 = "613";
	public static final String _REF_614 = "614";
	public static final String _REF_777 = "777";
	public static final String _REF_888 = "888";
	public static final String _REF_900 = "900";
	public static final String _REF_901 = "901";
	public static final String _REF_902 = "902";
	public static final String _REF_903 = "903";
	public static final String _REF_904 = "904";
	public static final String _REF_905 = "905";
	public static final String _REF_906 = "906";
	public static final String _REF_907 = "907";
	public static final String _REF_910 = "910";
	public static final String _REF_911 = "911";
	public static final String _REF_912 = "912";
	public static final String _REF_913 = "913";
	public static final String _REF_914 = "914";
	public static final String _REF_915 = "915";
	public static final String _REF_916 = "916";
	public static final String _REF_917 = "917";
	public static final String _REF_918 = "918";
	public static final String _REF_919 = "919";
	public static final String _REF_920 = "920";
	public static final String _REF_921 = "921";
	public static final String _REF_922 = "922";
	public static final String _REF_923 = "923";
	public static final String _REF_924 = "924";
	public static final String _REF_925 = "925";
	public static final String _REF_926 = "926";
	public static final String _REF_927 = "927";
	public static final String _REF_928 = "928";
	public static final String _REF_929 = "929";
	public static final String _REF_930 = "930";
	public static final String _REF_931 = "931";
	public static final String _REF_932 = "932";
	public static final String _REF_933 = "933";
	public static final String _REF_934 = "934";
	public static final String _REF_935 = "935";
	public static final String _REF_940 = "940";
	public static final String _REF_941 = "941";
	public static final String _REF_942 = "942";
	public static final String _REF_943 = "943";


	public static final String NOT_FOUND = "NOT FOUND";
	public static final String MORE_THAN_ONE_INDIVIDUAL_FOR_THAT_NAME = "MORE THAN ONE INDIVIDUAL  FOR THAT NAME";
	public static final String SIMULTANEOUS_UPDATE = "SIMULTANEOUS UPDATE";
	public static final String INACTIVE_INDIVIDUAL = "INACTIVE INDIVIDUAL";
	public static final String UNAUTHORIZED_APPLICATION_CODE = "UNAUTHORIZED APPLICATION CODE";
	public static final String MAILING_DATA_MANDATORY = "MAILING DATA MANDATORY";
	public static final String SOLVENCY_DATA_MANDATORY = "SOLVENCY DATA MANDATORY";
	public static final String SIGNATURE_BLOCK_MANDATORY = "SIGNATURE BLOCK MANDATORY";
	public static final String LAST_NAME_DATA_MANDATORY = "LAST NAME DATA MANDATORY";
	public static final String FIRST_NAME_DATA_MANDATORY = "FIRST NAME DATA MANDATORY";
	public static final String CIVILITY_DATA_MANDATORY = "CIVILITY DATA MANDATORY";
	public static final String WRONG_CIVILITY_DATA = "WRONG CIVILITY DATA";
	public static final String GENDER_DATA_MANDATORY = "GENDER DATA MANDATORY";
	public static final String MERGE_FLAG_MANDATORY = "MERGE FLAG MANDATORY";
	public static final String SIGNATURE_TYPE_MANDATORY = "SIGNATURE TYPE MANDATORY";
	public static final String SIGNATURE_SITE_MANDATORY = "SIGNATURE SITE MANDATORY";
	public static final String MANDATORY_SIGNATURE_DATA = "MANDATORY SIGNATURE DATA";
	public static final String SIGNATURE_DATE_MANDATORY = "SIGNATURE DATE MANDATORY";
	public static final String SIGNATURE_TIME_MANDATORY = "SIGNATURE TIME MANDATORY";
	public static final String INDIVIDUAL_GIN_MANDATORY = "INDIVIDUAL GIN MANDATORY";
	public static final String INVALID_MEDIUM_TYPE = "INVALID MEDIUM TYPE";
	public static final String INVALID_MEDIUM_CODE = "INVALID MEDIUM CODE";
	public static final String MEDIUM_CODE_MANDATORY = "MEDIUM CODE MANDATORY";
	public static final String APPLICATION_CODE_MANDATORY = "APPLICATION CODE MANDATORY";
	public static final String INVALID_DATE = "INVALID DATE";
	public static final String WRONG_NORMALIZED_ADDRESS = "WRONG NORMALIZED ADDRESS";
	public static final String INVALID_SIGNATURE_TYPE = "INVALID SIGNATURE TYPE";
	public static final String INVALID_TERMINAL_TYPE = "INVALID TERMINAL TYPE";
	public static final String PHONETIC_PRBLM_WITH_FIRST_AND_LAST_NAME = "PHONETIC PRBLM WITH FIRST AND LAST NAME";
	public static final String PHONETIC_PRBLM_WITH_BUSINESS_NAME = "PHONETIC PRBLM WITH BUSINESS NAME";
	public static final String INVALID_TITLE_CODE = "INVALID TITLE CODE";
	public static final String INVALID_JOB_TITLE_CODE = "INVALID JOB TITLE CODE";
	public static final String INVALID_ACTIVITY_SECTOR_CODE = "INVALID ACTIVITY SECTOR CODE";
	public static final String CONTRACT_NUMBER_MANDATORY = "CONTRACT NUMBER MANDATORY";
	public static final String CONTRACT_STATUS_MANDATORY = "CONTRACT STATUS MANDATORY";
	public static final String CONTRACT_TYPE_MANDATORY = "CONTRACT TYPE MANDATORY";
	public static final String INVALID_COUNTRY = "INVALID COUNTRY";
	public static final String MAXIMUM_NUMBER_OF_ADDRESS_REACHED = "MAXIMUM NUMBER OF ADDRESS REACHED";
	public static final String MISSING_PARAMETERS = "MISSING PARAMETERS";
	public static final String EXISTING_INDIVIDUAL_CONTRACT_NUMBER = "EXISTING INDIVIDUAL CONTRACT NUMBER";
	public static final String INVALID_LANGUAGE_CODE = "INVALID LANGUAGE CODE";
	public static final String INVALID_EXPORT_CODE_Y_N = "INVALID EXPORT CODE (Y/N)";
	public static final String INVALID_MEDIUM_STATUS = "INVALID MEDIUM STATUS";
	public static final String MEDIUM_STATUS_MANDATORY = "MEDIUM STATUS MANDATORY";
	public static final String VALID_ADDRESS_ALREADY_FILLED = "VALID ADDRESS ALREADY FILLED";
	public static final String TELECOM_NUMBER_MANDATORY = "TELECOM NUMBER MANDATORY";
	public static final String USAGE_ALREADY_EXISTS = "USAGE ALREADY EXISTS";
	public static final String BIRTH_DATE_MANDATORY = "BIRTH DATE MANDATORY";
	public static final String FIRM_TYPE_MANDATORY = "FIRM TYPE MANDATORY";
	public static final String GROUP_CODE_MANDATORY = "GROUP CODE MANDATORY";
	public static final String INVALID_FIRM_TYPE_G_E_T = "INVALID FIRM TYPE (G,E OR T)";
	public static final String INVALID_LEGAL_STATUS = "INVALID LEGAL STATUS";
	public static final String INVALID_SOURCE_CODE = "INVALID SOURCE CODE";
	public static final String INVALID_SUPPORT_CODE = "INVALID SUPPORT CODE";
	public static final String INVALID_DOOR_TO_DOOR_SELLING = "INVALID DOOR TO DOOR SELLING";
	public static final String INVALID_CONTRACT_TYPE = "INVALID CONTRACT TYPE";
	public static final String INVALID_CONTRACT_SUBTYPE = "INVALID CONTRACT SUBTYPE";
	public static final String HISTORICAL_MODIFICATION_IMPOSSIBLE = "HISTORICAL MODIFICATION IMPOSSIBLE";
	public static final String INVALID_MARKET_CHOICE_LEVEL = "INVALID MARKET CHOICE LEVEL";
	public static final String STATUS_MANDATORY = "STATUS MANDATORY";
	public static final String INVALID_HIERARCHICAL_RELATION = "INVALID HIERARCHICAL RELATION";
	public static final String INVALID_FIRM_TYPE = "INVALID FIRM TYPE";
	public static final String INVALID_WORKS_COUNCIL = "INVALID WORKS COUNCIL";
	public static final String INVALID_HEAD_OFFICE = "INVALID HEAD OFFICE";
	public static final String INVALID_INDUSTRY_CODE = "INVALID INDUSTRY CODE";
	public static final String INVALID_ACTIVITY_CODE = "INVALID ACTIVITY CODE";
	public static final String INVALID_IMPORT_CODE_Y_N = "INVALID IMPORT CODE (Y/N)";
	public static final String INVALID_SALES_RESTRICTION_CODE_Y_N = "INVALID SALES RESTRICTION CODE (Y/N)";
	public static final String INVALID_NON_PAYMENT_CODE_Y_N = "INVALID NON PAYMENT CODE (Y/N)";
	public static final String INVALID_MAILING_CODE_A_T_N = "INVALID MAILING CODE (A,T OR N)";
	public static final String SIRET_NUMBER_ALREADY_USED = "SIRET NUMBER ALREADY USED";
	public static final String ADDRESS_MANDATORY = "ADDRESS MANDATORY";
	public static final String SIRET_NUMBER_MANDATORY = "SIRET NUMBER MANDATORY";
	public static final String SIRET_NUMBER_NOT_ALLOWED = "SIRET NUMBER NOT ALLOWED";
	public static final String INVALID_SIRET_NUMBER = "INVALID SIRET NUMBER";
	public static final String COMMERCIAL_ZONE_MANDATORY = "COMMERCIAL ZONE MANDATORY";
	public static final String INVALID_COMMERCIAL_ZONE = "INVALID COMMERCIAL ZONE";
	public static final String ZONE_NOT_FOUND_OR_INVALID = "ZONE NOT FOUND OR INVALID";
	public static final String INVALID_SIREN_NUMBER = "INVALID SIREN NUMBER";
	public static final String SIREN_NUMBER_ALREADY_USED = "SIREN NUMBER ALREADY USED";
	public static final String INVALID_ZONE_TYPE = "INVALID ZONE TYPE";
	public static final String INVALID_STATUS = "INVALID STATUS";

	public static final String ADDRESS_UNCOMPLETELY_FILLED = "ADDRESS UNCOMPLETELY FILLED";
	public static final String COMMERCIAL_ZONE_DELETION_PROHIBITED = "COMMERCIAL ZONE DELETION PROHIBITED";
	public static final String MAXIMUM_NUMBER_LIST_REACHED = "MAXIMUM NUMBER LIST REACHED";
	public static final String UF_CODE_MANDATORY = "UF CODE MANDATORY";
	public static final String GIN_FIRM_MANDATORY = "GIN FIRM MANDATORY";
	public static final String MORE_THAN_ONE_ACCOUNT_NUMBER = "MORE THAN ONE ACCOUNT NUMBER";
	public static final String IATA_NUMBER_MANDATORY = "IATA NUMBER MANDATORY";
	public static final String MORE_THAN_ONE_DUPLICATE = "MORE THAN ONE DUPLICATE";
	public static final String DUPLICATE_NOT_FOUND = "DUPLICATE NOT FOUND";
	public static final String MERGED_APPLICATION_NOT_FOUND = "MERGED APPLICATION NOT FOUND";
	public static final String MERGE_GIN_MANDATORY = "MERGE GIN MANDATORY";
	public static final String TARGET_GIN_MANDATORY = "TARGET GIN MANDATORY";
	public static final String LAST_VALID_ADDRESS_REMOVAL_NOT_ALLOWED = "LAST VALID ADDRESS REMOVAL NOT ALLOWED";
	public static final String COUNTRY_CODE_MANDATORY = "COUNTRY CODE MANDATORY";
	public static final String ADDRESS_NOT_FOUND = "ADDRESS NOT FOUND";
	public static final String MEDIUM_USAGE_NOT_FOUND = "MEDIUM USAGE NOT FOUND";
	public static final String USAGE_NUMBER_MANDATORY = "USAGE NUMBER MANDATORY";
	public static final String INVALID_USAGE = "INVALID USAGE";
	public static final String SALES_ZONE_REMOVAL_NOT_ALLOWED = "SALES ZONE REMOVAL NOT ALLOWED";
	public static final String INDIVIDUAL_MERGING_LOOP = "INDIVIDUAL MERGING LOOP";
	public static final String NUMBER_TYPE_MANDATORY = "NUMBER TYPE MANDATORY";
	public static final String CITY_NOT_FOUND = "CITY NOT FOUND";
	public static final String ZIP_CODE_NOT_FOUND = "ZIP CODE NOT FOUND";
	public static final String STREET_NOT_FOUND = "STREET NOT FOUND";
	public static final String GIN_ALREADY_USED = "GIN ALREADY USED";
	public static final String MANDATORY_SIRET_NUMBER_FOR_BUSINESS_PHONE = "MANDATORY SIRET NUMBER FOR BUSINESS PHONE";
	public static final String DUPLICATE_ALREADY_LOCKED_BY_AN_OTHER_USER = "DUPLICATE ALREADY LOCKED BY AN OTHER USER";
	public static final String UNLOCK_ATTEMPT_OF_AN_UNLOCKED_DUPLICATE = "UNLOCK ATTEMPT OF AN UNLOCKED DUPLICATE";
	public static final String NO_DUPLICATE_LIST_FOR_THIS_PROFILE = "NO DUPLICATE LIST FOR THIS PROFILE";
	public static final String MERGED_GROUP_CANCELLATION_NOT_ALLOWED = "MERGED GROUP CANCELLATION NOT ALLOWED";
	public static final String INDIVIDUAL_TRANSFERED = "INDIVIDUAL TRANSFERED";
	public static final String ACCOUNT_NUMBER_MANDATORY = "ACCOUNT NUMBER MANDATORY";
	public static final String VALIDITY_START_DATE_MANDATORY = "VALIDITY START DATE MANDATORY";
	public static final String CONTRACT_NOT_FOUND = "CONTRACT NOT FOUND";
	public static final String LOCALISATION_ADDRESS_REMOVAL_NOT_ALLOWED = "LOCALISATION ADDRESS REMOVAL NOT ALLOWED";
	public static final String VALID_LOCALIZATION_ADDRESS_IS_MANDATORY = "VALID LOCALIZATION ADDRESS IS MANDATORY";
	public static final String INVALID_NUMBER_TYPE = "INVALID NUMBER TYPE";
	public static final String IDENTIFICATION_NUMBER_TYPE_MANDATORY = "IDENTIFICATION NUMBER TYPE MANDATORY";
	public static final String INVALID_IDENTIFICATION_NUMBER_TYPE = "INVALID IDENTIFICATION NUMBER TYPE";
	public static final String SYNONYM_TYPE_MANDATORY = "SYNONYM TYPE MANDATORY";
	public static final String INVALID_SYNONYM_TYPE = "INVALID SYNONYM TYPE";
	public static final String INVALID_MAILING = "INVALID MAILING";
	public static final String AGENCY_TYPE_MANDATORY = "AGENCY TYPE MANDATORY";
	public static final String INVALID_LOCALISATION_TYPE = "INVALID LOCALISATION TYPE";
	public static final String INVALID_INFRASTRUCTURE_TYPE = "INVALID INFRASTRUCTURE TYPE";
	public static final String INVALID_SALES_IMPACTS_SENDING_Y_N = "INVALID SALES IMPACTS SENDING (Y/N)";
	public static final String INVALID_TARGET_O_N = "INVALID TARGET (O/N)";
	public static final String INVALID_SALES_TYPE = "INVALID SALES TYPE";
	public static final String INVALID_AGREEMENT_TYPE = "INVALID AGREEMENT TYPE";
	public static final String INVALID_AGENCY_TYPE = "INVALID AGENCY TYPE";
	public static final String INVALID_DISTRIBUTION_CHANNEL = "INVALID DISTRIBUTION CHANNEL";
	public static final String INVALID_SUB_DISTRIBUTION_CHANNEL = "INVALID SUB DISTRIBUTION CHANNEL";
	public static final String INVALID_MARKET_CHOICE_LEVEL_TYPE = "INVALID MARKET CHOICE LEVEL TYPE";
	public static final String INVALID_GDS_CODE = "INVALID GDS CODE";
	public static final String INVALID_IATA_STATUS = "INVALID IATA STATUS";
	public static final String INVALID_MARKET_CHOICE_TYPE = "INVALID MARKET CHOICE TYPE";
	public static final String INVALID_GROUPING_CODE = "INVALID GROUPING CODE";
	public static final String INVALID_NETWORK_CODE = "INVALID NETWORK CODE";
	public static final String MARKET_CHOICE_ON_CLOSED_AGENCY = "MARKET CHOICE ON CLOSED AGENCY";
	public static final String MERGED_FIRM_CAN_T_BE_MODIFIED = "MERGED FIRM CAN T BE MODIFIED";
	public static final String USE_CORPORATE_MERGE_TOOL = "USE CORPORATE MERGE TOOL";
	public static final String INVALID_PHONE_NUMBER_DATA = "INVALID PHONE NUMBER DATA";
	public static final String SAME_TARGET_AND_SOURCE_GIN = "SAME TARGET AND SOURCE GIN";
	public static final String LINK_DOES_NOT_EXIST = "LINK DOES NOT EXIST";
	public static final String INVALID_LINK_TYPE = "INVALID LINK TYPE";
	public static final String LINK_ALREADY_EXISTS = "LINK ALREADY EXISTS";
	public static final String CONTACT_PHONE_NOT_FOUND = "CONTACT PHONE NOT FOUND";
	public static final String TOO_MANY_RESULTS_FOUND = "TOO MANY RESULTS FOUND";
	public static final String TECHNICAL_PROBLEM_ON_ADDRESS = "TECHNICAL PROBLEM ON ADDRESS";
	public static final String GP_DUPLICATE = "GP DUPLICATE";
	public static final String IDENTIFICATION_NUMBER_MANDATORY = "IDENTIFICATION NUMBER MANDATORY";
	public static final String RANK_MANDATORY = "RANK MANDATORY";
	public static final String GP_INFO_MANDATORY = "GP INFO MANDATORY";
	public static final String MARKET_CHOICE_TYPE_MANDATORY = "MARKET CHOICE TYPE MANDATORY";
	public static final String ZONE_TYPE_MANDATORY = "ZONE TYPE MANDATORY";
	public static final String INCOMPLETE_COMMERCIAL_ZONE = "INCOMPLETE COMMERCIAL ZONE";
	public static final String INCOMPLETE_SALES_ZONE = "INCOMPLETE SALES ZONE";
	public static final String INVALID_NETWORK_TYPE = "INVALID NETWORK TYPE";
	public static final String INVALID_PRIMARY_NETWORK = "INVALID PRIMARY NETWORK";
	public static final String NATURE_ZONE_MANDATORY = "NATURE ZONE MANDATORY";
	public static final String NETWORK_TYPE_MANDATORY = "NETWORK TYPE  MANDATORY";
	public static final String NETWORK_NAME_MANDATORY = "NETWORK NAME MANDATORY";
	public static final String GIN_NOT_NULL_FOR_CREATION = "GIN NOT NULL FOR CREATION";
	public static final String VALIDITY_PERIODS_OVERLAPPING = "VALIDITY PERIODS OVERLAPPING";
	public static final String END_DATE_START_DATE = "END DATE < START DATE";
	public static final String ENTER_8_DIGITS_FOR_IDENTIFICATION_NUMBER = "ENTER 8 DIGITS FOR IDENTIFICATION NUMBER";
	public static final String INVALID_TRAVEL_POLICY_CODE = "INVALID TRAVEL POLICY CODE";
	public static final String SIRET_AND_SIREN_NUMBERS_COHERENCE = "SIRET AND SIREN NUMBERS COHERENCE";
	public static final String INVALID_ALIAS_NAME = "INVALID  ALIAS NAME";
	public static final String INVALID_MIDDLE_NAME = "INVALID MIDDLE NAME";
	public static final String INVALID_ALIAS_FIRST_NAME = "INVALID ALIAS FIRST NAME";
	public static final String VISA_DURATION_EXPIRED = "VISA DURATION EXPIRED";
	public static final String INVALID_CITY = "INVALID CITY";
	public static final String STREET_AND_NUMBER_MANDATORY = "STREET AND NUMBER MANDATORY";
	public static final String INVALID_PROVINCE_DISTRICT_CODE = "INVALID PROVINCE/DISTRICT CODE";
	public static final String INVALID_ZIP_CODE = "INVALID ZIP CODE";
	public static final String INVALID_APPLICATION_CODE = "INVALID APPLICATION CODE";
	public static final String ADRESS_LINE_PROBLEM = "ADRESS LINE PROBLEM";
	public static final String ADRESS_LINE_TOO_LONG = "ADRESS LINE TOO LONG";
	public static final String INVALID_OR_MISSING_STREET_NUMBER = "INVALID OR MISSING STREET NUMBER";
	public static final String SECOND_ADRESS_FOUND_FOR_SAME_RECORD = "SECOND ADRESS FOUND FOR SAME RECORD";
	public static final String MISSING_NUMBER_FLAT_BUILDING_SUITE_FLOOR = "MISSING NUMBER (FLAT,BUILDING,SUITE,FLOOR)";
	public static final String LOCKBOX_BAG_POBOX_RANGE_NOT_FOUND = "LOCKBOX/BAG/POBOX RANGE NOT FOUND";
	public static final String STATE_INCORRECT = "STATE INCORRECT";
	public static final String CITY_NOT_FOUND_FOR_THIS_ZIP_CODE = "CITY NOT FOUND FOR THIS ZIP CODE";
	public static final String MEDIAPOST_FILES_NOT_FOUND = "MEDIAPOST FILES NOT FOUND";

	public static final String UPDATED_ADDRESS = "UPDATED ADDRESS";
	public static final String UNAUTHORIZED_ACCESS = "UNAUTHORIZED ACCESS";
	public static final String INVALID_ISO_CITY_CODE = "INVALID ISO CITY CODE";
	public static final String INVALID_COUNTER_S_LETTER = "INVALID COUNTER S LETTER";
	public static final String MOTHER_IATA_NUMBER_MANDATORY = "MOTHER IATA NUMBER MANDATORY";
	public static final String HEAD_OFFICE_IATA_NUMBER_MANDATORY = "HEAD OFFICE IATA NUMBER MANDATORY";
	public static final String ATAF_NUMBER_MANDATORY = "ATAF NUMBER MANDATORY";
	public static final String NETWORK_MANDATORY = "NETWORK MANDATORY";
	public static final String CATCHMENT_ZONE_MANDATORY = "CATCHMENT ZONE MANDATORY";
	public static final String DISTRIBUTION_CHANNEL_MANDATORY = "DISTRIBUTION CHANNEL MANDATORY";
	public static final String SALES_TYPE_MANDATORY = "SALES TYPE MANDATORY";
	public static final String DOOR_TO_DOOR_PROFILE_MANDATORY = "DOOR TO DOOR PROFILE MANDATORY";
	public static final String FIRM_MANDATORY = "FIRM MANDATORY";
	public static final String INVALID_DOCUMENT_CODE = "INVALID DOCUMENT CODE";
	public static final String INVALID_GSA_CODE = "INVALID GSA CODE";
	public static final String INVALID_NETWORK_NATURE = "INVALID NETWORK NATURE";
	public static final String INVALID_GROUPING_TYPE = "INVALID GROUPING TYPE";
	public static final String TRADE_NAME_MANDATORY = "TRADE NAME MANDATORY";
	public static final String COMPANY_MANDATORY = "COMPANY MANDATORY";
	public static final String MARKET_CHOICE_MANDATORY = "MARKET CHOICE MANDATORY";
	public static final String NO_SEARCH_TYPE_AVAILABLE = "NO SEARCH TYPE AVAILABLE";
	public static final String INVALID_SEARCH_TYPE = "INVALID SEARCH TYPE";
	public static final String INVALID_CURRENCY_CODE = "INVALID CURRENCY CODE";
	public static final String INVALID_MARITAL_STATUS = "INVALID MARITAL STATUS";
	public static final String INVALID_NATURE_ZONE = "INVALID NATURE ZONE";
	public static final String INVALID_SUB_TYPE_ZONE = "INVALID SUB TYPE ZONE";
	public static final String COUNTER_S_LETTER_ALREADY_EXISTS = "COUNTER S LETTER ALREADY EXISTS";
	public static final String IATA_NUMBER_ALREADY_USED = "IATA NUMBER ALREADY USED";
	public static final String ATAF_NUMBER_ALREADY_USED = "ATAF NUMBER ALREADY USED";
	public static final String DOCUMENT_TYPE_MANDATORY = "DOCUMENT TYPE MANDATORY";
	public static final String DOCUMENTATION_NUMBER_MANDATORY = "DOCUMENTATION NUMBER MANDATORY";
	public static final String PRIMARY_OR_SECONDARY_ZONE_MANDATORY = "PRIMARY OR SECONDARY ZONE MANDATORY";
	public static final String COUNTER_S_LETTER_MANDATORY = "COUNTER S LETTER MANDATORY";
	public static final String INVALIDE_DOCUMENT_TYPE = "INVALIDE DOCUMENT TYPE";
	public static final String ZONE_LINK_NOT_FOUND = "ZONE LINK NOT FOUND";
	public static final String MORE_THAN_ONE_UNAPPROVED_NUMBERS_VALID = "MORE THAN ONE UNAPPROVED NUMBERS  VALID";
	public static final String MORE_THAN_ONE_VALID_IATA_NUMBERS_FOUND = "MORE THAN ONE VALID IATA NUMBERS FOUND";
	public static final String MORE_THAN_ONE_VALID_ATAF_NUMBERS_FOUND = "MORE THAN ONE VALID ATAF NUMBERS FOUND";
	public static final String MORE_THAN_ONE_ARC_NUMBERS_VALID = "MORE THAN ONE ARC NUMBERS VALID";
	public static final String MORE_THAN_ONE_VALID_MOTHER_IATA_NUMBERS_FOUND = "MORE THAN ONE VALID MOTHER IATA NUMBERS FOUND";
	public static final String INCOMPATIBLE_NUMBERS = "INCOMPATIBLE NUMBERS";
	public static final String AGENCY_FIRM_LINK_UPDATE_NOT_ALLOWED = "AGENCY/FIRM LINK UPDATE NOT ALLOWED";
	public static final String ZONE_NOT_FOUND = "ZONE NOT FOUND";
	public static final String COOPERATING_COMPANY_ALREADY_EXISTS = "COOPERATING COMPANY ALREADY EXISTS";
	public static final String MARKET_CHOICE_ALREADY_EXISTING = "MARKET CHOICE ALREADY EXISTING";
	public static final String INCONSISTENT_GA_IMPLANT_AND_INFRASTRUCTURE = "INCONSISTENT GA IMPLANT AND INFRASTRUCTURE";
	public static final String IMPLANT_NAME_MANDATORY = "IMPLANT NAME MANDATORY";
	public static final String INVALID_IDENTIFICATION_NUMBER = "INVALID IDENTIFICATION NUMBER";
	public static final String INVALID_TRADE_NAME = "INVALID TRADE NAME";
	public static final String INVALID_BUSINESS_NAME = "INVALID BUSINESS NAME";
	public static final String AGENCY_ALREADY_CLOSED = "AGENCY ALREADY CLOSED";
	public static final String AGENCY_ALREADY_EXISTS = "AGENCY ALREADY EXISTS";
	public static final String UNAPPROVED_AGENCY = "UNAPPROVED AGENCY";
	public static final String INVALID_STRUCK_OFF_DATE = "INVALID STRUCK OFF DATE";
	public static final String IDENTIFICATION_NUMBER_TOO_LONG = "IDENTIFICATION NUMBER TOO LONG";
	public static final String DIVERGENT_ADDRESSES = "DIVERGENT ADDRESSES";
	public static final String FIRM_CANCELLATION = "FIRM CANCELLATION";
	public static final String LIKELY_MERGED = "LIKELY MERGED";
	public static final String INSUFFICIENT_SEARCH_CRITERIA = "INSUFFICIENT SEARCH CRITERIA";
	public static final String MORE_THAN_ONE_ZONE_FILLED = "MORE THAN ONE ZONE FILLED";
	public static final String IATA_STATUS_MANDATORY = "IATA STATUS MANDATORY";
	public static final String SAME_IATA_AND_MOTHER_IATA_NUMBER = "SAME IATA AND MOTHER IATA NUMBER";
	public static final String INVALID_CATCHMENT_AREA = "INVALID CATCHMENT AREA";
	public static final String INVALID_BILL = "INVALID BILL";
	public static final String INVALID_BILLING_DUTY = "INVALID BILLING DUTY";
	public static final String START_DATE_LINK_CAN_T_BE_CHANGE = "START DATE LINK CAN T BE CHANGE";
	public static final String AGENCY_FIRM_START_DATE_LINK_AGENCY_START_DATE = "AGENCY/FIRM START DATE LINK < AGENCY START DATE";
	public static final String INVALID_HIERARCHY = "INVALID HIERARCHY";
	public static final String CONTACT_TRAVELLER_START_DATE_LINK_AGENCY_START_DATE = "CONTACT/TRAVELLER START DATE LINK < AGENCY START DATE";
	public static final String ZONE_ALREADY_EXISTS = "ZONE ALREADY EXISTS";
	public static final String CURRENCY_CODE_MANDATORY = "CURRENCY CODE MANDATORY";
	public static final String MODIFICATION_NOT_ALLOWED = "MODIFICATION NOT ALLOWED";
	public static final String EXISTING_CONTRACT_FOUND_FOR_SAME_PERIOD = "EXISTING CONTRACT FOUND FOR SAME PERIOD";
	public static final String NO_AGENT_MATCHING_CRITERIA = "NO AGENT MATCHING CRITERIA";
	public static final String NO_COMPANY_MATCHING_CRITERIA = "NO COMPANY MATCHING CRITERIA";
	public static final String NO_AGENT_OR_COMPANY_MATCHING_CRITERIA = "NO AGENT OR COMPANY MATCHING CRITERIA";
	public static final String EMAIL_ALREADY_USED_BY_FLYING_BLUE_MEMBERS = "EMAIL ALREADY USED BY FLYING BLUE MEMBERS";
	public static final String BAD_ANSWER = "BAD ANSWER";
	public static final String ACCOUNT_ALREADY_EXIST = "ACCOUNT ALREADY EXIST";
	public static final String ACCOUNT_NOT_FOUND = "ACCOUNT NOT FOUND";
	public static final String ONLY_FLYING_BLUE = "ONLY FLYING BLUE";
	public static final String ONLY_MYACCOUNT = "ONLY MYACCOUNT";
	public static final String NUMBER_ALREADY_USED = "NUMBER ALREADY USED";
	public static final String PERMISSION_ID_UNKNOWN = "PERMISSION ID UNKNOWN";
	public static final String ID_MANDATORY = "ID MANDATORY";
	public static final String ID_NOT_VALID = "ID NOT VALID";
	public static final String ID_EXISTS = "ID EXISTS";
	public static final String MISMATCH_ERROR_BETWEEN_ID_AND_GIN = "MISMATCH ERROR BETWEEN ID AND GIN";
	public static final String ID_PASSWORD_NOT_ALLOWED = "ID/PASSWORD NOT ALLOWED";
	public static final String PASSWORD_MANDATORY = "PASSWORD_MANDATORY";
	public static final String INVALID_PASSWORD = "INVALID PASSWORD";
	public static final String MISMATCH_ERROR_BETWEEN_PASSWORD_AND_GIN = "MISMATCH ERROR BETWEEN PASSWORD AND GIN";
	public static final String BAD_PASSWORD = "BAD PASSWORD";
	public static final String SITE_NOT_NORMALIZED = "SITE NOT NORMALIZED";

	public static final String SIGNATURE_NOT_NORMALIZED = "SIGNATURE NOT NORMALIZED";
	public static final String WRONG_PASSWORD_2_ATTEMPTS_LEFT = "WRONG PASSWORD, 2 ATTEMPTS LEFT";
	public static final String WRONG_PASSWORD_ATTEMPT_LEFT = "WRONG PASSWORD, 1 ATTEMPT LEFT";
	public static final String WRONG_PASSWORD_ACCESS_LOCKED = "WRONG PASSWORD, ACCESS LOCKED";
	public static final String ACCESS_LOCKED = "ACCESS LOCKED";
	public static final String UNABLE_TO_CREATE_ALIAS = "UNABLE TO CREATE ALIAS";
	public static final String ERROR_TESTING_CRITERIA = "ERROR TESTING CRITERIA";
	public static final String FIRM_MODIFICATION_TOO_RECENT = "FIRM MODIFICATION TOO RECENT";
	public static final String FIRM_NOT_LINKED_TO_COMMERCIAL_OR_CANCELLATION_ZONE = "FIRM NOT LINKED TO COMMERCIAL OR CANCELLATION ZONE";
	public static final String MORE_THAN_ONE_ZC_FOR_THIS_FIRM = "MORE THAN ONE ZC FOR THIS FIRM";
	public static final String FIRM_WITHOUT_VALID_ZC = "FIRM WITHOUT VALID ZC";
	public static final String FIRM_TRANSFERT_TO_WAITING_ZC_TOO_RECENT = "FIRM TRANSFERT TO WAITING ZC TOO RECENT";
	public static final String EXISTING_MEMBERS_PURGE_NOT_ALLOWED = "EXISTING MEMBERS PURGE NOT ALLOWED";
	public static final String MEMBERS_TOO_RECENT_FOR_TRANSFERT = "MEMBERS TOO RECENT FOR TRANSFERT";
	public static final String ZC_LINK_TOO_RECENT = "ZC LINK TOO RECENT";
	public static final String ACTIVE_CONTRACTS = "ACTIVE CONTRACTS";
	public static final String FIDELIO_LINK = "FIDELIO LINK";
	public static final String EXISTING_AGENCY_LINK = "EXISTING AGENCY LINK";
	public static final String INVALID_FIRM_IN_CANCELLATION_ZONE = "INVALID FIRM IN CANCELLATION ZONE";
	public static final String MAXIMUM_NUMBER_OF_TELECOMS_REACHED = "MAXIMUM NUMBER OF TELECOMS REACHED";
	public static final String FUNCTION_ALREADY_EXISTS = "FUNCTION ALREADY EXISTS";
	public static final String APPLICATION_IDENTIFICATION_FAILURE_unknown_user = "APPLICATION IDENTIFICATION FAILURE: unknown user";
	public static final String APPLICATION_IDENTIFICATION_FAILURE_access_denied = "APPLICATION IDENTIFICATION FAILURE: access denied";
	public static final String TECHNICAL_ERROR_ORACLE = "TECHNICAL ERROR : ORACLE";
	public static final String TECHNICAL_ERROR_PERSISTENCE = "TECHNICAL ERROR : PERSISTENCE";
	public static final String OBJECTS_NOT_FOUND = "OBJECTS NOT FOUND";
	public static final String INVALID_OBJECTS_OCCURRENCES = "INVALID OBJECTS OCCURRENCES";
	public static final String INVALID_SEQUENCE = "INVALID SEQUENCE";
	public static final String TECHNICAL_ERROR = "TECHNICAL ERROR";
	public static final String REQUEST_ALREADY_IN_PROGRESS = "REQUEST ALREADY IN PROGRESS";
	public static final String INVALID_DATA_FILE_LINE = "INVALID DATA FILE LINE";
	public static final String DATABASE_ACCESS_ERROR = "DATABASE ACCESS ERROR";
	public static final String DATABASE_CLOSURE_ERROR = "DATABASE CLOSURE ERROR";
	public static final String DATABASE_CONNECTION_ERROR = "DATABASE CONNECTION ERROR";
	public static final String DATABASE_CONNECTION_DESTROYED = "DATABASE CONNECTION DESTROYED";
	public static final String ID_RANK_COMBINATION_ALREADY_EXISTS = "ID/RANK COMBINATION ALREADY EXISTS";
	public static final String WRONG_TYPE = "WRONG TYPE";
	public static final String PRIMARY_KEY_ALREADY_EXISTING = "PRIMARY KEY ALREADY EXISTING";
	public static final String OFFICE_ID_ALREADY_EXISTS = "OFFICE ID ALREADY EXISTS";
	public static final String NATIONALITY_MANDATORY = "NATIONALITY MANDATORY";
	public static final String AGENCY_GIN_NOT_ALLOWED = "AGENCY GIN NOT ALLOWED";
	public static final String ENGLISH_COLUMN_NOT_FOUND = "ENGLISH COLUMN NOT FOUND";
	public static final String PRIMARY_COLUMN_NOT_FOUND = "PRIMARY COLUMN NOT FOUND";
	public static final String REFERENCE_TABLE_NOT_FOUND = "REFERENCE TABLE NOT FOUND";
	public static final String INVALID_CHECK_DIGIT = "INVALID CHECK DIGIT";
	public static final String INVALID_SALES_ZONE = "INVALID SALES ZONE";
	public static final String SALES_ZONE_MISSING = "SALES ZONE MISSING";
	public static final String SALES_ZONE_MANDATORY = "SALES ZONE MANDATORY";
	public static final String RA2_FLAG_MANDATORY = "RA2 FLAG MANDATORY";
	public static final String CITY_ZONE_LINK_UNKNOWN = "CITY/ZONE LINK UNKNOWN";
	public static final String RA2_AGENCY_NOT_ALLOWED = "RA2 AGENCY NOT ALLOWED";
	public static final String INVALID_PARAMETER = "INVALID PARAMETER";
	public static final String TOO_MANY_FIRMS_FOUND_REFINE_CRITERIA = "TOO MANY FIRMS FOUND, REFINE CRITERIA";
	public static final String DEFAULT_VALUES_RETURNED = "DEFAULT VALUES RETURNED";
	public static final String DEFAULT_VALUES_TOO_MANY_FIRMS_FOUND_CHECK_CRITERIA = "DEFAULT VALUES + TOO MANY FIRMS FOUND, CHECK CRITERIA";
	public static final String PP_ALREADY_EXIST = "PP ALREADY EXIST";
	public static final String CANNOT_CREATE_LINK_BETWEEN_AGENCY_AND_R_OR_S= "CANNOT CREATE LINK BETWEEN AGENCY AND (R OR S)";
	public static final String CANNOT_UPDAT_LINKE_BETWEEN_AGENCY_AND_R_OR_S = "CANNOT UPDATE LINK BETWEEN AGENCY AND (R OR S)";
	public static final String CANNOT_DELETE_LINK_BETWEEN_AGENCY_AND_R_OR_S = "CANNOT DELETE LINK BETWEEN AGENCY AND (R OR S)";

	private RefTableREF_ERREUR() {
 
		m_lstChamps.add(new RefTableChamp(_REF_000,"0","ok","ok"));
		m_lstChamps.add(new RefTableChamp(_REF_001,NOT_FOUND,NOT_FOUND,NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_002,MORE_THAN_ONE_INDIVIDUAL_FOR_THAT_NAME,MORE_THAN_ONE_INDIVIDUAL_FOR_THAT_NAME,MORE_THAN_ONE_INDIVIDUAL_FOR_THAT_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_003,SIMULTANEOUS_UPDATE,SIMULTANEOUS_UPDATE,SIMULTANEOUS_UPDATE));
		m_lstChamps.add(new RefTableChamp(_REF_004,INACTIVE_INDIVIDUAL,INACTIVE_INDIVIDUAL,INACTIVE_INDIVIDUAL));
		m_lstChamps.add(new RefTableChamp(_REF_006,UNAUTHORIZED_APPLICATION_CODE,UNAUTHORIZED_APPLICATION_CODE,UNAUTHORIZED_APPLICATION_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_100,MAILING_DATA_MANDATORY,MAILING_DATA_MANDATORY,MAILING_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_101,SOLVENCY_DATA_MANDATORY,SOLVENCY_DATA_MANDATORY,SOLVENCY_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_102,SIGNATURE_BLOCK_MANDATORY,SIGNATURE_BLOCK_MANDATORY,SIGNATURE_BLOCK_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_103,LAST_NAME_DATA_MANDATORY,LAST_NAME_DATA_MANDATORY,LAST_NAME_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_104,FIRST_NAME_DATA_MANDATORY,FIRST_NAME_DATA_MANDATORY,FIRST_NAME_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_105,CIVILITY_DATA_MANDATORY,CIVILITY_DATA_MANDATORY,CIVILITY_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_106,WRONG_CIVILITY_DATA,WRONG_CIVILITY_DATA,WRONG_CIVILITY_DATA));
		m_lstChamps.add(new RefTableChamp(_REF_107,GENDER_DATA_MANDATORY,GENDER_DATA_MANDATORY,GENDER_DATA_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_108,MERGE_FLAG_MANDATORY,MERGE_FLAG_MANDATORY,MERGE_FLAG_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_109,SIGNATURE_TYPE_MANDATORY,SIGNATURE_TYPE_MANDATORY,SIGNATURE_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_110,SIGNATURE_SITE_MANDATORY,SIGNATURE_SITE_MANDATORY,SIGNATURE_SITE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_111,MANDATORY_SIGNATURE_DATA,MANDATORY_SIGNATURE_DATA,MANDATORY_SIGNATURE_DATA));
		m_lstChamps.add(new RefTableChamp(_REF_112,SIGNATURE_DATE_MANDATORY,SIGNATURE_DATE_MANDATORY,SIGNATURE_DATE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_113,SIGNATURE_TIME_MANDATORY,SIGNATURE_TIME_MANDATORY,SIGNATURE_TIME_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_114,INDIVIDUAL_GIN_MANDATORY,INDIVIDUAL_GIN_MANDATORY,INDIVIDUAL_GIN_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_115,INVALID_MEDIUM_TYPE,INVALID_MEDIUM_TYPE,INVALID_MEDIUM_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_116,INVALID_MEDIUM_CODE,INVALID_MEDIUM_CODE,INVALID_MEDIUM_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_117,MEDIUM_CODE_MANDATORY,MEDIUM_CODE_MANDATORY,MEDIUM_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_118,APPLICATION_CODE_MANDATORY,APPLICATION_CODE_MANDATORY,APPLICATION_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_119,INVALID_DATE,INVALID_DATE,INVALID_DATE));
		m_lstChamps.add(new RefTableChamp(_REF_120,WRONG_NORMALIZED_ADDRESS,WRONG_NORMALIZED_ADDRESS,WRONG_NORMALIZED_ADDRESS));
		m_lstChamps.add(new RefTableChamp(_REF_121,INVALID_SIGNATURE_TYPE,INVALID_SIGNATURE_TYPE,INVALID_SIGNATURE_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_122,INVALID_TERMINAL_TYPE,INVALID_TERMINAL_TYPE,INVALID_TERMINAL_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_123,PHONETIC_PRBLM_WITH_FIRST_AND_LAST_NAME,PHONETIC_PRBLM_WITH_FIRST_AND_LAST_NAME,PHONETIC_PRBLM_WITH_FIRST_AND_LAST_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_124,PHONETIC_PRBLM_WITH_BUSINESS_NAME,PHONETIC_PRBLM_WITH_BUSINESS_NAME,PHONETIC_PRBLM_WITH_BUSINESS_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_125,INVALID_TITLE_CODE,INVALID_TITLE_CODE,INVALID_TITLE_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_126,INVALID_JOB_TITLE_CODE,INVALID_JOB_TITLE_CODE,INVALID_JOB_TITLE_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_127,INVALID_ACTIVITY_SECTOR_CODE,INVALID_ACTIVITY_SECTOR_CODE,INVALID_ACTIVITY_SECTOR_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_128,CONTRACT_NUMBER_MANDATORY,CONTRACT_NUMBER_MANDATORY,CONTRACT_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_129,CONTRACT_STATUS_MANDATORY,CONTRACT_STATUS_MANDATORY,CONTRACT_STATUS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_130,CONTRACT_TYPE_MANDATORY,CONTRACT_TYPE_MANDATORY,CONTRACT_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_131,INVALID_COUNTRY,INVALID_COUNTRY,INVALID_COUNTRY));
		m_lstChamps.add(new RefTableChamp(_REF_132,MAXIMUM_NUMBER_OF_ADDRESS_REACHED,MAXIMUM_NUMBER_OF_ADDRESS_REACHED,MAXIMUM_NUMBER_OF_ADDRESS_REACHED));
		m_lstChamps.add(new RefTableChamp(_REF_133,MISSING_PARAMETERS,MISSING_PARAMETERS,MISSING_PARAMETERS));
		m_lstChamps.add(new RefTableChamp(_REF_134,EXISTING_INDIVIDUAL_CONTRACT_NUMBER,EXISTING_INDIVIDUAL_CONTRACT_NUMBER,EXISTING_INDIVIDUAL_CONTRACT_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_135,INVALID_LANGUAGE_CODE,INVALID_LANGUAGE_CODE,INVALID_LANGUAGE_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_136,INVALID_MEDIUM_STATUS,INVALID_MEDIUM_STATUS,INVALID_MEDIUM_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_137,MEDIUM_STATUS_MANDATORY,MEDIUM_STATUS_MANDATORY,MEDIUM_STATUS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_138,VALID_ADDRESS_ALREADY_FILLED,VALID_ADDRESS_ALREADY_FILLED,VALID_ADDRESS_ALREADY_FILLED));
		m_lstChamps.add(new RefTableChamp(_REF_139,TELECOM_NUMBER_MANDATORY,TELECOM_NUMBER_MANDATORY,TELECOM_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_140,USAGE_ALREADY_EXISTS,USAGE_ALREADY_EXISTS,USAGE_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_141,BIRTH_DATE_MANDATORY,BIRTH_DATE_MANDATORY,BIRTH_DATE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_142,FIRM_TYPE_MANDATORY,FIRM_TYPE_MANDATORY,FIRM_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_143,GROUP_CODE_MANDATORY,GROUP_CODE_MANDATORY,GROUP_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_144,FIRM_TYPE_MANDATORY,FIRM_TYPE_MANDATORY,FIRM_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_145,INVALID_FIRM_TYPE_G_E_T,INVALID_FIRM_TYPE_G_E_T,INVALID_FIRM_TYPE_G_E_T));
		m_lstChamps.add(new RefTableChamp(_REF_146,INVALID_LEGAL_STATUS,INVALID_LEGAL_STATUS,INVALID_LEGAL_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_147,INVALID_SOURCE_CODE,INVALID_SOURCE_CODE,INVALID_SOURCE_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_148,INVALID_SUPPORT_CODE,INVALID_SUPPORT_CODE,INVALID_SUPPORT_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_149,INVALID_DOOR_TO_DOOR_SELLING,INVALID_DOOR_TO_DOOR_SELLING,INVALID_DOOR_TO_DOOR_SELLING));
		m_lstChamps.add(new RefTableChamp(_REF_150,INVALID_CONTRACT_TYPE,INVALID_CONTRACT_TYPE,INVALID_CONTRACT_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_151,INVALID_CONTRACT_SUBTYPE,INVALID_CONTRACT_SUBTYPE,INVALID_CONTRACT_SUBTYPE));
		m_lstChamps.add(new RefTableChamp(_REF_152,HISTORICAL_MODIFICATION_IMPOSSIBLE,HISTORICAL_MODIFICATION_IMPOSSIBLE,HISTORICAL_MODIFICATION_IMPOSSIBLE));
		m_lstChamps.add(new RefTableChamp(_REF_153,INVALID_MARKET_CHOICE_LEVEL,INVALID_MARKET_CHOICE_LEVEL,INVALID_MARKET_CHOICE_LEVEL));
		m_lstChamps.add(new RefTableChamp(_REF_154,STATUS_MANDATORY,STATUS_MANDATORY,STATUS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_155,INVALID_HIERARCHICAL_RELATION,INVALID_HIERARCHICAL_RELATION,INVALID_HIERARCHICAL_RELATION));
		m_lstChamps.add(new RefTableChamp(_REF_156,INVALID_FIRM_TYPE,INVALID_FIRM_TYPE,INVALID_FIRM_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_157,INVALID_WORKS_COUNCIL,INVALID_WORKS_COUNCIL,INVALID_WORKS_COUNCIL));
		m_lstChamps.add(new RefTableChamp(_REF_158,INVALID_HEAD_OFFICE,INVALID_HEAD_OFFICE,INVALID_HEAD_OFFICE));
		m_lstChamps.add(new RefTableChamp(_REF_159,INVALID_INDUSTRY_CODE,INVALID_INDUSTRY_CODE,INVALID_INDUSTRY_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_160,INVALID_ACTIVITY_CODE,INVALID_ACTIVITY_CODE,INVALID_ACTIVITY_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_161,INVALID_EXPORT_CODE_Y_N,INVALID_EXPORT_CODE_Y_N,INVALID_EXPORT_CODE_Y_N));
		m_lstChamps.add(new RefTableChamp(_REF_162,INVALID_IMPORT_CODE_Y_N,INVALID_IMPORT_CODE_Y_N,INVALID_IMPORT_CODE_Y_N));
		m_lstChamps.add(new RefTableChamp(_REF_163,INVALID_SALES_RESTRICTION_CODE_Y_N,INVALID_SALES_RESTRICTION_CODE_Y_N,INVALID_SALES_RESTRICTION_CODE_Y_N));
		m_lstChamps.add(new RefTableChamp(_REF_164,INVALID_NON_PAYMENT_CODE_Y_N,INVALID_NON_PAYMENT_CODE_Y_N,INVALID_NON_PAYMENT_CODE_Y_N));
		m_lstChamps.add(new RefTableChamp(_REF_165,INVALID_MAILING_CODE_A_T_N,INVALID_MAILING_CODE_A_T_N,INVALID_MAILING_CODE_A_T_N));
		m_lstChamps.add(new RefTableChamp(_REF_166,SIRET_NUMBER_ALREADY_USED,SIRET_NUMBER_ALREADY_USED,SIRET_NUMBER_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_167,ADDRESS_MANDATORY,ADDRESS_MANDATORY,ADDRESS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_168,SIRET_NUMBER_MANDATORY,SIRET_NUMBER_MANDATORY,SIRET_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_169,SIRET_NUMBER_NOT_ALLOWED,SIRET_NUMBER_NOT_ALLOWED,SIRET_NUMBER_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_170,INVALID_SIRET_NUMBER,INVALID_SIRET_NUMBER,INVALID_SIRET_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_171,COMMERCIAL_ZONE_MANDATORY,COMMERCIAL_ZONE_MANDATORY,COMMERCIAL_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_172,INVALID_COMMERCIAL_ZONE,INVALID_COMMERCIAL_ZONE,INVALID_COMMERCIAL_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_173,ZONE_NOT_FOUND_OR_INVALID,ZONE_NOT_FOUND_OR_INVALID,ZONE_NOT_FOUND_OR_INVALID));
		m_lstChamps.add(new RefTableChamp(_REF_174,INVALID_SIREN_NUMBER,INVALID_SIREN_NUMBER,INVALID_SIREN_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_175,SIREN_NUMBER_ALREADY_USED,SIREN_NUMBER_ALREADY_USED,SIREN_NUMBER_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_176,INVALID_ZONE_TYPE,INVALID_ZONE_TYPE,INVALID_ZONE_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_177,INVALID_STATUS,INVALID_STATUS,INVALID_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_178,ADDRESS_UNCOMPLETELY_FILLED,ADDRESS_UNCOMPLETELY_FILLED,ADDRESS_UNCOMPLETELY_FILLED));
		m_lstChamps.add(new RefTableChamp(_REF_179,COMMERCIAL_ZONE_DELETION_PROHIBITED,COMMERCIAL_ZONE_DELETION_PROHIBITED,COMMERCIAL_ZONE_DELETION_PROHIBITED));
		m_lstChamps.add(new RefTableChamp(_REF_180,MAXIMUM_NUMBER_LIST_REACHED,MAXIMUM_NUMBER_LIST_REACHED,MAXIMUM_NUMBER_LIST_REACHED));
		m_lstChamps.add(new RefTableChamp(_REF_181,UF_CODE_MANDATORY,UF_CODE_MANDATORY,UF_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_182,GIN_FIRM_MANDATORY,GIN_FIRM_MANDATORY,GIN_FIRM_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_183,MORE_THAN_ONE_ACCOUNT_NUMBER,MORE_THAN_ONE_ACCOUNT_NUMBER,MORE_THAN_ONE_ACCOUNT_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_184,IATA_NUMBER_MANDATORY,IATA_NUMBER_MANDATORY,IATA_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_185,MORE_THAN_ONE_DUPLICATE,MORE_THAN_ONE_DUPLICATE,MORE_THAN_ONE_DUPLICATE));
		m_lstChamps.add(new RefTableChamp(_REF_186,DUPLICATE_NOT_FOUND,DUPLICATE_NOT_FOUND,DUPLICATE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_187,MERGED_APPLICATION_NOT_FOUND,MERGED_APPLICATION_NOT_FOUND,MERGED_APPLICATION_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_188,MERGE_GIN_MANDATORY,MERGE_GIN_MANDATORY,MERGE_GIN_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_189,TARGET_GIN_MANDATORY,TARGET_GIN_MANDATORY,TARGET_GIN_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_190,INDIVIDUAL_GIN_MANDATORY,INDIVIDUAL_GIN_MANDATORY,INDIVIDUAL_GIN_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_191,LAST_VALID_ADDRESS_REMOVAL_NOT_ALLOWED,LAST_VALID_ADDRESS_REMOVAL_NOT_ALLOWED,LAST_VALID_ADDRESS_REMOVAL_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_192,COUNTRY_CODE_MANDATORY,COUNTRY_CODE_MANDATORY,COUNTRY_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_193,ADDRESS_NOT_FOUND,ADDRESS_NOT_FOUND,ADDRESS_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_194,MEDIUM_USAGE_NOT_FOUND,MEDIUM_USAGE_NOT_FOUND,MEDIUM_USAGE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_195,USAGE_NUMBER_MANDATORY,USAGE_NUMBER_MANDATORY,USAGE_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_196,INVALID_USAGE,INVALID_USAGE,INVALID_USAGE));
		m_lstChamps.add(new RefTableChamp(_REF_197,SALES_ZONE_REMOVAL_NOT_ALLOWED,SALES_ZONE_REMOVAL_NOT_ALLOWED,SALES_ZONE_REMOVAL_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_198,INDIVIDUAL_MERGING_LOOP,INDIVIDUAL_MERGING_LOOP,INDIVIDUAL_MERGING_LOOP));
		m_lstChamps.add(new RefTableChamp(_REF_199,NUMBER_TYPE_MANDATORY,NUMBER_TYPE_MANDATORY,NUMBER_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_200,CITY_NOT_FOUND,CITY_NOT_FOUND,CITY_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_201,ZIP_CODE_NOT_FOUND,ZIP_CODE_NOT_FOUND,ZIP_CODE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_202,STREET_NOT_FOUND,STREET_NOT_FOUND,STREET_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_203,GIN_ALREADY_USED,GIN_ALREADY_USED,GIN_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_204,MANDATORY_SIRET_NUMBER_FOR_BUSINESS_PHONE,MANDATORY_SIRET_NUMBER_FOR_BUSINESS_PHONE,MANDATORY_SIRET_NUMBER_FOR_BUSINESS_PHONE));
		m_lstChamps.add(new RefTableChamp(_REF_205,DUPLICATE_ALREADY_LOCKED_BY_AN_OTHER_USER,DUPLICATE_ALREADY_LOCKED_BY_AN_OTHER_USER,DUPLICATE_ALREADY_LOCKED_BY_AN_OTHER_USER));
		m_lstChamps.add(new RefTableChamp(_REF_206,UNLOCK_ATTEMPT_OF_AN_UNLOCKED_DUPLICATE,UNLOCK_ATTEMPT_OF_AN_UNLOCKED_DUPLICATE,UNLOCK_ATTEMPT_OF_AN_UNLOCKED_DUPLICATE));
		m_lstChamps.add(new RefTableChamp(_REF_207,NO_DUPLICATE_LIST_FOR_THIS_PROFILE,NO_DUPLICATE_LIST_FOR_THIS_PROFILE,NO_DUPLICATE_LIST_FOR_THIS_PROFILE));
		m_lstChamps.add(new RefTableChamp(_REF_208,MERGED_GROUP_CANCELLATION_NOT_ALLOWED,MERGED_GROUP_CANCELLATION_NOT_ALLOWED,MERGED_GROUP_CANCELLATION_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_209,INDIVIDUAL_TRANSFERED,INDIVIDUAL_TRANSFERED,INDIVIDUAL_TRANSFERED));
		m_lstChamps.add(new RefTableChamp(_REF_210,ACCOUNT_NUMBER_MANDATORY,ACCOUNT_NUMBER_MANDATORY,ACCOUNT_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_211,VALIDITY_START_DATE_MANDATORY,VALIDITY_START_DATE_MANDATORY,VALIDITY_START_DATE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_212,CONTRACT_NOT_FOUND,CONTRACT_NOT_FOUND,CONTRACT_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_213,LOCALISATION_ADDRESS_REMOVAL_NOT_ALLOWED,LOCALISATION_ADDRESS_REMOVAL_NOT_ALLOWED,LOCALISATION_ADDRESS_REMOVAL_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_214,VALID_LOCALIZATION_ADDRESS_IS_MANDATORY,VALID_LOCALIZATION_ADDRESS_IS_MANDATORY,VALID_LOCALIZATION_ADDRESS_IS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_215,INVALID_NUMBER_TYPE,INVALID_NUMBER_TYPE,INVALID_NUMBER_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_216,IDENTIFICATION_NUMBER_TYPE_MANDATORY,IDENTIFICATION_NUMBER_TYPE_MANDATORY,IDENTIFICATION_NUMBER_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_217,INVALID_IDENTIFICATION_NUMBER_TYPE,INVALID_IDENTIFICATION_NUMBER_TYPE,INVALID_IDENTIFICATION_NUMBER_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_218,SYNONYM_TYPE_MANDATORY,SYNONYM_TYPE_MANDATORY,SYNONYM_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_219,INVALID_SYNONYM_TYPE,INVALID_SYNONYM_TYPE,INVALID_SYNONYM_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_220,INVALID_MAILING,INVALID_MAILING,INVALID_MAILING));
		m_lstChamps.add(new RefTableChamp(_REF_221,AGENCY_TYPE_MANDATORY,AGENCY_TYPE_MANDATORY,AGENCY_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_222,INVALID_LOCALISATION_TYPE,INVALID_LOCALISATION_TYPE,INVALID_LOCALISATION_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_223,INVALID_INFRASTRUCTURE_TYPE,INVALID_INFRASTRUCTURE_TYPE,INVALID_INFRASTRUCTURE_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_224,INVALID_SALES_IMPACTS_SENDING_Y_N,INVALID_SALES_IMPACTS_SENDING_Y_N,INVALID_SALES_IMPACTS_SENDING_Y_N));
		m_lstChamps.add(new RefTableChamp(_REF_225,INVALID_TARGET_O_N,INVALID_TARGET_O_N,INVALID_TARGET_O_N));
		m_lstChamps.add(new RefTableChamp(_REF_226,INVALID_SALES_TYPE,INVALID_SALES_TYPE,INVALID_SALES_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_227,INVALID_AGREEMENT_TYPE,INVALID_AGREEMENT_TYPE,INVALID_AGREEMENT_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_228,INVALID_AGENCY_TYPE,INVALID_AGENCY_TYPE,INVALID_AGENCY_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_229,INVALID_DISTRIBUTION_CHANNEL,INVALID_DISTRIBUTION_CHANNEL,INVALID_DISTRIBUTION_CHANNEL));
		m_lstChamps.add(new RefTableChamp(_REF_230,INVALID_SUB_DISTRIBUTION_CHANNEL,INVALID_SUB_DISTRIBUTION_CHANNEL,INVALID_SUB_DISTRIBUTION_CHANNEL));
		m_lstChamps.add(new RefTableChamp(_REF_231,INVALID_MARKET_CHOICE_LEVEL_TYPE,INVALID_MARKET_CHOICE_LEVEL_TYPE,INVALID_MARKET_CHOICE_LEVEL_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_232,INVALID_GDS_CODE,INVALID_GDS_CODE,INVALID_GDS_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_233,INVALID_IATA_STATUS,INVALID_IATA_STATUS,INVALID_IATA_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_234,INVALID_MARKET_CHOICE_TYPE,INVALID_MARKET_CHOICE_TYPE,INVALID_MARKET_CHOICE_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_235,INVALID_GROUPING_CODE,INVALID_GROUPING_CODE,INVALID_GROUPING_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_236,INVALID_NETWORK_CODE,INVALID_NETWORK_CODE,INVALID_NETWORK_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_237,MARKET_CHOICE_ON_CLOSED_AGENCY,MARKET_CHOICE_ON_CLOSED_AGENCY,MARKET_CHOICE_ON_CLOSED_AGENCY));
		m_lstChamps.add(new RefTableChamp(_REF_238,MERGED_FIRM_CAN_T_BE_MODIFIED,MERGED_FIRM_CAN_T_BE_MODIFIED,MERGED_FIRM_CAN_T_BE_MODIFIED));
		m_lstChamps.add(new RefTableChamp(_REF_239,USE_CORPORATE_MERGE_TOOL,USE_CORPORATE_MERGE_TOOL,USE_CORPORATE_MERGE_TOOL));
		m_lstChamps.add(new RefTableChamp(_REF_240,INVALID_PHONE_NUMBER_DATA,INVALID_PHONE_NUMBER_DATA,INVALID_PHONE_NUMBER_DATA));
		m_lstChamps.add(new RefTableChamp(_REF_241,SAME_TARGET_AND_SOURCE_GIN,SAME_TARGET_AND_SOURCE_GIN,SAME_TARGET_AND_SOURCE_GIN));
		m_lstChamps.add(new RefTableChamp(_REF_242,LINK_DOES_NOT_EXIST,LINK_DOES_NOT_EXIST,LINK_DOES_NOT_EXIST));
		m_lstChamps.add(new RefTableChamp(_REF_243,INVALID_LINK_TYPE,INVALID_LINK_TYPE,INVALID_LINK_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_244,LINK_ALREADY_EXISTS,LINK_ALREADY_EXISTS,LINK_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_245,CONTACT_PHONE_NOT_FOUND,CONTACT_PHONE_NOT_FOUND,CONTACT_PHONE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_246,TOO_MANY_RESULTS_FOUND,TOO_MANY_RESULTS_FOUND,TOO_MANY_RESULTS_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_250,TECHNICAL_PROBLEM_ON_ADDRESS,TECHNICAL_PROBLEM_ON_ADDRESS,TECHNICAL_PROBLEM_ON_ADDRESS));
		m_lstChamps.add(new RefTableChamp(_REF_251,GP_DUPLICATE,GP_DUPLICATE,GP_DUPLICATE));
		m_lstChamps.add(new RefTableChamp(_REF_252,IDENTIFICATION_NUMBER_MANDATORY,IDENTIFICATION_NUMBER_MANDATORY,IDENTIFICATION_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_253,RANK_MANDATORY,RANK_MANDATORY,RANK_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_254,GP_INFO_MANDATORY,GP_INFO_MANDATORY,GP_INFO_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_255,MARKET_CHOICE_TYPE_MANDATORY,MARKET_CHOICE_TYPE_MANDATORY,MARKET_CHOICE_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_256,ZONE_TYPE_MANDATORY,ZONE_TYPE_MANDATORY,ZONE_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_257,INCOMPLETE_COMMERCIAL_ZONE,INCOMPLETE_COMMERCIAL_ZONE,INCOMPLETE_COMMERCIAL_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_258,INCOMPLETE_SALES_ZONE,INCOMPLETE_SALES_ZONE,INCOMPLETE_SALES_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_259,INVALID_NETWORK_TYPE,INVALID_NETWORK_TYPE,INVALID_NETWORK_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_260,INVALID_PRIMARY_NETWORK,INVALID_PRIMARY_NETWORK,INVALID_PRIMARY_NETWORK));
		m_lstChamps.add(new RefTableChamp(_REF_261,NATURE_ZONE_MANDATORY,NATURE_ZONE_MANDATORY,NATURE_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_262,NETWORK_TYPE_MANDATORY,NETWORK_TYPE_MANDATORY,NETWORK_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_263,NETWORK_NAME_MANDATORY,NETWORK_NAME_MANDATORY,NETWORK_NAME_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_264,GIN_NOT_NULL_FOR_CREATION,GIN_NOT_NULL_FOR_CREATION,GIN_NOT_NULL_FOR_CREATION));
		m_lstChamps.add(new RefTableChamp(_REF_265,VALIDITY_PERIODS_OVERLAPPING,VALIDITY_PERIODS_OVERLAPPING,VALIDITY_PERIODS_OVERLAPPING));
		m_lstChamps.add(new RefTableChamp(_REF_266,END_DATE_START_DATE,END_DATE_START_DATE,END_DATE_START_DATE));
		m_lstChamps.add(new RefTableChamp(_REF_267,ENTER_8_DIGITS_FOR_IDENTIFICATION_NUMBER,ENTER_8_DIGITS_FOR_IDENTIFICATION_NUMBER,ENTER_8_DIGITS_FOR_IDENTIFICATION_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_268,INVALID_TRAVEL_POLICY_CODE,INVALID_TRAVEL_POLICY_CODE,INVALID_TRAVEL_POLICY_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_269,SIRET_AND_SIREN_NUMBERS_COHERENCE,SIRET_AND_SIREN_NUMBERS_COHERENCE,SIRET_AND_SIREN_NUMBERS_COHERENCE));
		m_lstChamps.add(new RefTableChamp(_REF_272,INVALID_ALIAS_NAME,INVALID_ALIAS_NAME,INVALID_ALIAS_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_274,INVALID_MIDDLE_NAME,INVALID_MIDDLE_NAME,INVALID_MIDDLE_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_275,INVALID_ALIAS_FIRST_NAME,INVALID_ALIAS_FIRST_NAME,INVALID_ALIAS_FIRST_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_277,VISA_DURATION_EXPIRED,VISA_DURATION_EXPIRED,VISA_DURATION_EXPIRED));
		m_lstChamps.add(new RefTableChamp(_REF_278,INVALID_CITY,INVALID_CITY,INVALID_CITY));
		m_lstChamps.add(new RefTableChamp(_REF_279,STREET_AND_NUMBER_MANDATORY,STREET_AND_NUMBER_MANDATORY,STREET_AND_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_280,INVALID_PROVINCE_DISTRICT_CODE,INVALID_PROVINCE_DISTRICT_CODE,INVALID_PROVINCE_DISTRICT_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_281,INVALID_ZIP_CODE,INVALID_ZIP_CODE,INVALID_ZIP_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_282,INVALID_APPLICATION_CODE,INVALID_APPLICATION_CODE,INVALID_APPLICATION_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_283,ADRESS_LINE_PROBLEM,ADRESS_LINE_PROBLEM,ADRESS_LINE_PROBLEM));
		m_lstChamps.add(new RefTableChamp(_REF_284,ADRESS_LINE_TOO_LONG,ADRESS_LINE_TOO_LONG,ADRESS_LINE_TOO_LONG));
		m_lstChamps.add(new RefTableChamp(_REF_285,INVALID_OR_MISSING_STREET_NUMBER,INVALID_OR_MISSING_STREET_NUMBER,INVALID_OR_MISSING_STREET_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_286,SECOND_ADRESS_FOUND_FOR_SAME_RECORD,SECOND_ADRESS_FOUND_FOR_SAME_RECORD,SECOND_ADRESS_FOUND_FOR_SAME_RECORD));
		m_lstChamps.add(new RefTableChamp(_REF_287,MISSING_NUMBER_FLAT_BUILDING_SUITE_FLOOR,MISSING_NUMBER_FLAT_BUILDING_SUITE_FLOOR,MISSING_NUMBER_FLAT_BUILDING_SUITE_FLOOR));
		m_lstChamps.add(new RefTableChamp(_REF_288,LOCKBOX_BAG_POBOX_RANGE_NOT_FOUND,LOCKBOX_BAG_POBOX_RANGE_NOT_FOUND,LOCKBOX_BAG_POBOX_RANGE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_289,STATE_INCORRECT,STATE_INCORRECT,STATE_INCORRECT));
		m_lstChamps.add(new RefTableChamp(_REF_290,CITY_NOT_FOUND_FOR_THIS_ZIP_CODE,CITY_NOT_FOUND_FOR_THIS_ZIP_CODE,CITY_NOT_FOUND_FOR_THIS_ZIP_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_291,MEDIAPOST_FILES_NOT_FOUND,MEDIAPOST_FILES_NOT_FOUND,MEDIAPOST_FILES_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_299,UPDATED_ADDRESS,UPDATED_ADDRESS,UPDATED_ADDRESS));
		m_lstChamps.add(new RefTableChamp(_REF_300,UNAUTHORIZED_ACCESS,UNAUTHORIZED_ACCESS,UNAUTHORIZED_ACCESS));
		m_lstChamps.add(new RefTableChamp(_REF_301,INVALID_ISO_CITY_CODE,INVALID_ISO_CITY_CODE,INVALID_ISO_CITY_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_302,INVALID_COUNTER_S_LETTER,INVALID_COUNTER_S_LETTER,INVALID_COUNTER_S_LETTER));
		m_lstChamps.add(new RefTableChamp(_REF_303,MOTHER_IATA_NUMBER_MANDATORY,MOTHER_IATA_NUMBER_MANDATORY,MOTHER_IATA_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_304,HEAD_OFFICE_IATA_NUMBER_MANDATORY,HEAD_OFFICE_IATA_NUMBER_MANDATORY,HEAD_OFFICE_IATA_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_305,IDENTIFICATION_NUMBER_MANDATORY,IDENTIFICATION_NUMBER_MANDATORY,IDENTIFICATION_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_306,ATAF_NUMBER_MANDATORY,ATAF_NUMBER_MANDATORY,ATAF_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_307,NETWORK_MANDATORY,NETWORK_MANDATORY,NETWORK_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_308,CATCHMENT_ZONE_MANDATORY,CATCHMENT_ZONE_MANDATORY,CATCHMENT_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_309,DISTRIBUTION_CHANNEL_MANDATORY,DISTRIBUTION_CHANNEL_MANDATORY,DISTRIBUTION_CHANNEL_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_310,SALES_TYPE_MANDATORY,SALES_TYPE_MANDATORY,SALES_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_311,DOOR_TO_DOOR_PROFILE_MANDATORY,DOOR_TO_DOOR_PROFILE_MANDATORY,DOOR_TO_DOOR_PROFILE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_312,FIRM_MANDATORY,FIRM_MANDATORY,FIRM_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_313,INVALID_LEGAL_STATUS,INVALID_LEGAL_STATUS,INVALID_LEGAL_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_314,INVALID_DOCUMENT_CODE,INVALID_DOCUMENT_CODE,INVALID_DOCUMENT_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_315,INVALID_GSA_CODE,INVALID_GSA_CODE,INVALID_GSA_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_316,INVALID_NETWORK_NATURE,INVALID_NETWORK_NATURE,INVALID_NETWORK_NATURE));
		m_lstChamps.add(new RefTableChamp(_REF_317,INVALID_GROUPING_TYPE,INVALID_GROUPING_TYPE,INVALID_GROUPING_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_318,INVALID_CONTRACT_TYPE,INVALID_CONTRACT_TYPE,INVALID_CONTRACT_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_319,TRADE_NAME_MANDATORY,TRADE_NAME_MANDATORY,TRADE_NAME_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_320,COMPANY_MANDATORY,COMPANY_MANDATORY,COMPANY_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_321,MARKET_CHOICE_MANDATORY,MARKET_CHOICE_MANDATORY,MARKET_CHOICE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_322,NO_SEARCH_TYPE_AVAILABLE,NO_SEARCH_TYPE_AVAILABLE,NO_SEARCH_TYPE_AVAILABLE));
		m_lstChamps.add(new RefTableChamp(_REF_323,INVALID_SEARCH_TYPE,INVALID_SEARCH_TYPE,INVALID_SEARCH_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_324,INVALID_LINK_TYPE,INVALID_LINK_TYPE,INVALID_LINK_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_325,INVALID_CURRENCY_CODE,INVALID_CURRENCY_CODE,INVALID_CURRENCY_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_326,INVALID_MARITAL_STATUS,INVALID_MARITAL_STATUS,INVALID_MARITAL_STATUS));
		m_lstChamps.add(new RefTableChamp(_REF_327,INVALID_NATURE_ZONE,INVALID_NATURE_ZONE,INVALID_NATURE_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_328,INVALID_SUB_TYPE_ZONE,INVALID_SUB_TYPE_ZONE,INVALID_SUB_TYPE_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_329,COUNTER_S_LETTER_ALREADY_EXISTS,COUNTER_S_LETTER_ALREADY_EXISTS,COUNTER_S_LETTER_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_330,IATA_NUMBER_ALREADY_USED,IATA_NUMBER_ALREADY_USED,IATA_NUMBER_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_331,ATAF_NUMBER_ALREADY_USED,ATAF_NUMBER_ALREADY_USED,ATAF_NUMBER_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_332,DOCUMENT_TYPE_MANDATORY,DOCUMENT_TYPE_MANDATORY,DOCUMENT_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_333,DOCUMENTATION_NUMBER_MANDATORY,DOCUMENTATION_NUMBER_MANDATORY,DOCUMENTATION_NUMBER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_334,PRIMARY_OR_SECONDARY_ZONE_MANDATORY,PRIMARY_OR_SECONDARY_ZONE_MANDATORY,PRIMARY_OR_SECONDARY_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_335,COUNTER_S_LETTER_MANDATORY,COUNTER_S_LETTER_MANDATORY,COUNTER_S_LETTER_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_337,INVALIDE_DOCUMENT_TYPE,INVALIDE_DOCUMENT_TYPE,INVALIDE_DOCUMENT_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_338,ZONE_LINK_NOT_FOUND,ZONE_LINK_NOT_FOUND,ZONE_LINK_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_339,MORE_THAN_ONE_UNAPPROVED_NUMBERS_VALID,MORE_THAN_ONE_UNAPPROVED_NUMBERS_VALID,MORE_THAN_ONE_UNAPPROVED_NUMBERS_VALID));
		m_lstChamps.add(new RefTableChamp(_REF_340,MORE_THAN_ONE_VALID_IATA_NUMBERS_FOUND,MORE_THAN_ONE_VALID_IATA_NUMBERS_FOUND,MORE_THAN_ONE_VALID_IATA_NUMBERS_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_341,MORE_THAN_ONE_VALID_ATAF_NUMBERS_FOUND,MORE_THAN_ONE_VALID_ATAF_NUMBERS_FOUND,MORE_THAN_ONE_VALID_ATAF_NUMBERS_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_342,MORE_THAN_ONE_ARC_NUMBERS_VALID,MORE_THAN_ONE_ARC_NUMBERS_VALID,MORE_THAN_ONE_ARC_NUMBERS_VALID));
		m_lstChamps.add(new RefTableChamp(_REF_343,MORE_THAN_ONE_VALID_MOTHER_IATA_NUMBERS_FOUND,MORE_THAN_ONE_VALID_MOTHER_IATA_NUMBERS_FOUND,MORE_THAN_ONE_VALID_MOTHER_IATA_NUMBERS_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_344,INCOMPATIBLE_NUMBERS,INCOMPATIBLE_NUMBERS,INCOMPATIBLE_NUMBERS));
		m_lstChamps.add(new RefTableChamp(_REF_345,AGENCY_FIRM_LINK_UPDATE_NOT_ALLOWED,AGENCY_FIRM_LINK_UPDATE_NOT_ALLOWED,AGENCY_FIRM_LINK_UPDATE_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_346,ZONE_NOT_FOUND,ZONE_NOT_FOUND,ZONE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_347,COOPERATING_COMPANY_ALREADY_EXISTS,COOPERATING_COMPANY_ALREADY_EXISTS,COOPERATING_COMPANY_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_348,MARKET_CHOICE_ALREADY_EXISTING,MARKET_CHOICE_ALREADY_EXISTING,MARKET_CHOICE_ALREADY_EXISTING));
		m_lstChamps.add(new RefTableChamp(_REF_349,INCONSISTENT_GA_IMPLANT_AND_INFRASTRUCTURE,INCONSISTENT_GA_IMPLANT_AND_INFRASTRUCTURE,INCONSISTENT_GA_IMPLANT_AND_INFRASTRUCTURE));
		m_lstChamps.add(new RefTableChamp(_REF_350,IMPLANT_NAME_MANDATORY,IMPLANT_NAME_MANDATORY,IMPLANT_NAME_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_351,INVALID_IDENTIFICATION_NUMBER,INVALID_IDENTIFICATION_NUMBER,INVALID_IDENTIFICATION_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_352,INVALID_TRADE_NAME,INVALID_TRADE_NAME,INVALID_TRADE_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_353,INVALID_BUSINESS_NAME,INVALID_BUSINESS_NAME,INVALID_BUSINESS_NAME));
		m_lstChamps.add(new RefTableChamp(_REF_354,AGENCY_ALREADY_CLOSED,AGENCY_ALREADY_CLOSED,AGENCY_ALREADY_CLOSED));
		m_lstChamps.add(new RefTableChamp(_REF_355,AGENCY_ALREADY_EXISTS,AGENCY_ALREADY_EXISTS,AGENCY_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_356,UNAPPROVED_AGENCY,UNAPPROVED_AGENCY,UNAPPROVED_AGENCY));
		m_lstChamps.add(new RefTableChamp(_REF_357,INVALID_STRUCK_OFF_DATE,INVALID_STRUCK_OFF_DATE,INVALID_STRUCK_OFF_DATE));
		m_lstChamps.add(new RefTableChamp(_REF_358,INVALID_GDS_CODE,INVALID_GDS_CODE,INVALID_GDS_CODE));
		m_lstChamps.add(new RefTableChamp(_REF_359,IDENTIFICATION_NUMBER_TOO_LONG,IDENTIFICATION_NUMBER_TOO_LONG,IDENTIFICATION_NUMBER_TOO_LONG));
		m_lstChamps.add(new RefTableChamp(_REF_360,ZONE_TYPE_MANDATORY,ZONE_TYPE_MANDATORY,ZONE_TYPE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_361,DIVERGENT_ADDRESSES,DIVERGENT_ADDRESSES,DIVERGENT_ADDRESSES));
		m_lstChamps.add(new RefTableChamp(_REF_362,FIRM_CANCELLATION,FIRM_CANCELLATION,FIRM_CANCELLATION));
		m_lstChamps.add(new RefTableChamp(_REF_363,LIKELY_MERGED,LIKELY_MERGED,LIKELY_MERGED));
		m_lstChamps.add(new RefTableChamp(_REF_364,INSUFFICIENT_SEARCH_CRITERIA,INSUFFICIENT_SEARCH_CRITERIA,INSUFFICIENT_SEARCH_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_365,MORE_THAN_ONE_ZONE_FILLED,MORE_THAN_ONE_ZONE_FILLED,MORE_THAN_ONE_ZONE_FILLED));
		m_lstChamps.add(new RefTableChamp(_REF_366,IATA_STATUS_MANDATORY,IATA_STATUS_MANDATORY,IATA_STATUS_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_367,SAME_IATA_AND_MOTHER_IATA_NUMBER,SAME_IATA_AND_MOTHER_IATA_NUMBER,SAME_IATA_AND_MOTHER_IATA_NUMBER));
		m_lstChamps.add(new RefTableChamp(_REF_368,INVALID_CATCHMENT_AREA,INVALID_CATCHMENT_AREA,INVALID_CATCHMENT_AREA));
		m_lstChamps.add(new RefTableChamp(_REF_369,INVALID_BILL,INVALID_BILL,INVALID_BILL));
		m_lstChamps.add(new RefTableChamp(_REF_370,INVALID_BILLING_DUTY,INVALID_BILLING_DUTY,INVALID_BILLING_DUTY));
		m_lstChamps.add(new RefTableChamp(_REF_371,START_DATE_LINK_CAN_T_BE_CHANGE,START_DATE_LINK_CAN_T_BE_CHANGE,START_DATE_LINK_CAN_T_BE_CHANGE));
		m_lstChamps.add(new RefTableChamp(_REF_372,AGENCY_FIRM_START_DATE_LINK_AGENCY_START_DATE,AGENCY_FIRM_START_DATE_LINK_AGENCY_START_DATE,AGENCY_FIRM_START_DATE_LINK_AGENCY_START_DATE));
		m_lstChamps.add(new RefTableChamp(_REF_373,INVALID_HIERARCHY,INVALID_HIERARCHY,INVALID_HIERARCHY));
		m_lstChamps.add(new RefTableChamp(_REF_374,CONTACT_TRAVELLER_START_DATE_LINK_AGENCY_START_DATE,CONTACT_TRAVELLER_START_DATE_LINK_AGENCY_START_DATE,CONTACT_TRAVELLER_START_DATE_LINK_AGENCY_START_DATE));
		m_lstChamps.add(new RefTableChamp(_REF_375,ZONE_ALREADY_EXISTS,ZONE_ALREADY_EXISTS,ZONE_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_376,CURRENCY_CODE_MANDATORY,CURRENCY_CODE_MANDATORY,CURRENCY_CODE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_377,MODIFICATION_NOT_ALLOWED,MODIFICATION_NOT_ALLOWED,MODIFICATION_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_378,EXISTING_CONTRACT_FOUND_FOR_SAME_PERIOD,EXISTING_CONTRACT_FOUND_FOR_SAME_PERIOD,EXISTING_CONTRACT_FOUND_FOR_SAME_PERIOD));
		m_lstChamps.add(new RefTableChamp(_REF_379,NO_AGENT_MATCHING_CRITERIA,NO_AGENT_MATCHING_CRITERIA,NO_AGENT_MATCHING_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_380,NO_COMPANY_MATCHING_CRITERIA,NO_COMPANY_MATCHING_CRITERIA,NO_COMPANY_MATCHING_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_381,NO_AGENT_OR_COMPANY_MATCHING_CRITERIA,NO_AGENT_OR_COMPANY_MATCHING_CRITERIA,NO_AGENT_OR_COMPANY_MATCHING_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_382,EMAIL_ALREADY_USED_BY_FLYING_BLUE_MEMBERS,EMAIL_ALREADY_USED_BY_FLYING_BLUE_MEMBERS,EMAIL_ALREADY_USED_BY_FLYING_BLUE_MEMBERS));
		m_lstChamps.add(new RefTableChamp(_REF_383,BAD_ANSWER,BAD_ANSWER,BAD_ANSWER));
		m_lstChamps.add(new RefTableChamp(_REF_384,ACCOUNT_ALREADY_EXIST,ACCOUNT_ALREADY_EXIST,ACCOUNT_ALREADY_EXIST));
		m_lstChamps.add(new RefTableChamp(_REF_385,ACCOUNT_NOT_FOUND,ACCOUNT_NOT_FOUND,ACCOUNT_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_386,ONLY_FLYING_BLUE,ONLY_FLYING_BLUE,ONLY_FLYING_BLUE));
		m_lstChamps.add(new RefTableChamp(_REF_387,ONLY_MYACCOUNT,ONLY_MYACCOUNT,ONLY_MYACCOUNT));
		m_lstChamps.add(new RefTableChamp(_REF_388,NUMBER_ALREADY_USED,NUMBER_ALREADY_USED,NUMBER_ALREADY_USED));
		m_lstChamps.add(new RefTableChamp(_REF_389, "MOT_DE_PASSE_DEJA_INITIALISE", "PASSWORD ALREADY INITIALIZED", "PASSWORD ALREADY INITIALIZED"));
		m_lstChamps.add(new RefTableChamp(_REF_390,PERMISSION_ID_UNKNOWN,PERMISSION_ID_UNKNOWN,PERMISSION_ID_UNKNOWN));
		m_lstChamps.add(new RefTableChamp(_REF_511,ID_MANDATORY,ID_MANDATORY,ID_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_512,ID_NOT_VALID,ID_NOT_VALID,ID_NOT_VALID));
		m_lstChamps.add(new RefTableChamp(_REF_515,ID_EXISTS,ID_EXISTS,ID_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_516,MISMATCH_ERROR_BETWEEN_ID_AND_GIN,MISMATCH_ERROR_BETWEEN_ID_AND_GIN,MISMATCH_ERROR_BETWEEN_ID_AND_GIN));
		m_lstChamps.add(new RefTableChamp(_REF_517,ID_PASSWORD_NOT_ALLOWED,ID_PASSWORD_NOT_ALLOWED,ID_PASSWORD_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_521,PASSWORD_MANDATORY,PASSWORD_MANDATORY,PASSWORD_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_522,INVALID_PASSWORD,INVALID_PASSWORD,INVALID_PASSWORD));
		m_lstChamps.add(new RefTableChamp(_REF_526,MISMATCH_ERROR_BETWEEN_PASSWORD_AND_GIN,MISMATCH_ERROR_BETWEEN_PASSWORD_AND_GIN,MISMATCH_ERROR_BETWEEN_PASSWORD_AND_GIN));
		m_lstChamps.add(new RefTableChamp(_REF_530,BAD_PASSWORD,BAD_PASSWORD,BAD_PASSWORD));
		m_lstChamps.add(new RefTableChamp(_REF_531,SITE_NOT_NORMALIZED,SITE_NOT_NORMALIZED,SITE_NOT_NORMALIZED));
		m_lstChamps.add(new RefTableChamp(_REF_532,SIGNATURE_NOT_NORMALIZED,SIGNATURE_NOT_NORMALIZED,SIGNATURE_NOT_NORMALIZED));
		m_lstChamps.add(new RefTableChamp(_REF_533,WRONG_PASSWORD_2_ATTEMPTS_LEFT,WRONG_PASSWORD_2_ATTEMPTS_LEFT,WRONG_PASSWORD_2_ATTEMPTS_LEFT));
		m_lstChamps.add(new RefTableChamp(_REF_534,WRONG_PASSWORD_ATTEMPT_LEFT,WRONG_PASSWORD_ATTEMPT_LEFT,WRONG_PASSWORD_ATTEMPT_LEFT));
		m_lstChamps.add(new RefTableChamp(_REF_535,WRONG_PASSWORD_ACCESS_LOCKED,WRONG_PASSWORD_ACCESS_LOCKED,WRONG_PASSWORD_ACCESS_LOCKED));
		m_lstChamps.add(new RefTableChamp(_REF_536,ACCESS_LOCKED,ACCESS_LOCKED,ACCESS_LOCKED));
		m_lstChamps.add(new RefTableChamp(_REF_537,"SOCIAL NETWORK ID ALREADY LINKED","SOCIAL NETWORK ID ALREADY LINKED"));
		m_lstChamps.add(new RefTableChamp(_REF_539,UNABLE_TO_CREATE_ALIAS,UNABLE_TO_CREATE_ALIAS, UNABLE_TO_CREATE_ALIAS));
		m_lstChamps.add(new RefTableChamp(_REF_551,"MAXIMUM NUMBER OF SUBSCRIBED NEWLETTER SALES REACHED","MAXIMUM NUMBER OF SUBSCRIBED NEWLETTER SALES REACHED"));
		m_lstChamps.add(new RefTableChamp(_REF_600,ERROR_TESTING_CRITERIA,ERROR_TESTING_CRITERIA,ERROR_TESTING_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_601,FIRM_MODIFICATION_TOO_RECENT,FIRM_MODIFICATION_TOO_RECENT,FIRM_MODIFICATION_TOO_RECENT));
		m_lstChamps.add(new RefTableChamp(_REF_602,FIRM_NOT_LINKED_TO_COMMERCIAL_OR_CANCELLATION_ZONE,FIRM_NOT_LINKED_TO_COMMERCIAL_OR_CANCELLATION_ZONE,FIRM_NOT_LINKED_TO_COMMERCIAL_OR_CANCELLATION_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_603,MORE_THAN_ONE_ZC_FOR_THIS_FIRM,MORE_THAN_ONE_ZC_FOR_THIS_FIRM,MORE_THAN_ONE_ZC_FOR_THIS_FIRM));
		m_lstChamps.add(new RefTableChamp(_REF_604,FIRM_WITHOUT_VALID_ZC,FIRM_WITHOUT_VALID_ZC,FIRM_WITHOUT_VALID_ZC));
		m_lstChamps.add(new RefTableChamp(_REF_605,FIRM_TRANSFERT_TO_WAITING_ZC_TOO_RECENT,FIRM_TRANSFERT_TO_WAITING_ZC_TOO_RECENT,FIRM_TRANSFERT_TO_WAITING_ZC_TOO_RECENT));
		m_lstChamps.add(new RefTableChamp(_REF_606,EXISTING_MEMBERS_PURGE_NOT_ALLOWED,EXISTING_MEMBERS_PURGE_NOT_ALLOWED,EXISTING_MEMBERS_PURGE_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_607,MEMBERS_TOO_RECENT_FOR_TRANSFERT,MEMBERS_TOO_RECENT_FOR_TRANSFERT,MEMBERS_TOO_RECENT_FOR_TRANSFERT));
		m_lstChamps.add(new RefTableChamp(_REF_608,ZC_LINK_TOO_RECENT,ZC_LINK_TOO_RECENT,ZC_LINK_TOO_RECENT));
		m_lstChamps.add(new RefTableChamp(_REF_609,ACTIVE_CONTRACTS,ACTIVE_CONTRACTS,ACTIVE_CONTRACTS));
		m_lstChamps.add(new RefTableChamp(_REF_610,FIDELIO_LINK,FIDELIO_LINK,FIDELIO_LINK));
		m_lstChamps.add(new RefTableChamp(_REF_611,EXISTING_AGENCY_LINK,EXISTING_AGENCY_LINK,EXISTING_AGENCY_LINK));
		m_lstChamps.add(new RefTableChamp(_REF_612,INVALID_FIRM_IN_CANCELLATION_ZONE,INVALID_FIRM_IN_CANCELLATION_ZONE,INVALID_FIRM_IN_CANCELLATION_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_613,MAXIMUM_NUMBER_OF_TELECOMS_REACHED,MAXIMUM_NUMBER_OF_TELECOMS_REACHED,MAXIMUM_NUMBER_OF_TELECOMS_REACHED));
		m_lstChamps.add(new RefTableChamp(_REF_614,FUNCTION_ALREADY_EXISTS,FUNCTION_ALREADY_EXISTS,FUNCTION_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_777,APPLICATION_IDENTIFICATION_FAILURE_unknown_user,APPLICATION_IDENTIFICATION_FAILURE_unknown_user,APPLICATION_IDENTIFICATION_FAILURE_unknown_user));
		m_lstChamps.add(new RefTableChamp(_REF_888,APPLICATION_IDENTIFICATION_FAILURE_access_denied,APPLICATION_IDENTIFICATION_FAILURE_access_denied,APPLICATION_IDENTIFICATION_FAILURE_access_denied));
		m_lstChamps.add(new RefTableChamp(_REF_900,TECHNICAL_ERROR_ORACLE,TECHNICAL_ERROR_ORACLE,TECHNICAL_ERROR_ORACLE));
		m_lstChamps.add(new RefTableChamp(_REF_901,TECHNICAL_ERROR_PERSISTENCE,TECHNICAL_ERROR_PERSISTENCE,TECHNICAL_ERROR_PERSISTENCE));
		m_lstChamps.add(new RefTableChamp(_REF_902,OBJECTS_NOT_FOUND,OBJECTS_NOT_FOUND,OBJECTS_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_903,INVALID_OBJECTS_OCCURRENCES,INVALID_OBJECTS_OCCURRENCES,INVALID_OBJECTS_OCCURRENCES));
		m_lstChamps.add(new RefTableChamp(_REF_904,INVALID_SEQUENCE,INVALID_SEQUENCE,INVALID_SEQUENCE));
		m_lstChamps.add(new RefTableChamp(_REF_905,TECHNICAL_ERROR,TECHNICAL_ERROR,TECHNICAL_ERROR));
		m_lstChamps.add(new RefTableChamp(_REF_906,REQUEST_ALREADY_IN_PROGRESS,REQUEST_ALREADY_IN_PROGRESS,REQUEST_ALREADY_IN_PROGRESS));
		m_lstChamps.add(new RefTableChamp(_REF_907,INVALID_DATA_FILE_LINE,INVALID_DATA_FILE_LINE,INVALID_DATA_FILE_LINE));
		m_lstChamps.add(new RefTableChamp(_REF_910,DATABASE_ACCESS_ERROR,DATABASE_ACCESS_ERROR,DATABASE_ACCESS_ERROR));
		m_lstChamps.add(new RefTableChamp(_REF_911,DATABASE_CLOSURE_ERROR,DATABASE_CLOSURE_ERROR,DATABASE_CLOSURE_ERROR));
		m_lstChamps.add(new RefTableChamp(_REF_912,DATABASE_CONNECTION_ERROR,DATABASE_CONNECTION_ERROR,DATABASE_CONNECTION_ERROR));
		m_lstChamps.add(new RefTableChamp(_REF_913,DATABASE_CONNECTION_DESTROYED,DATABASE_CONNECTION_DESTROYED,DATABASE_CONNECTION_DESTROYED));
		m_lstChamps.add(new RefTableChamp(_REF_914,ID_RANK_COMBINATION_ALREADY_EXISTS,ID_RANK_COMBINATION_ALREADY_EXISTS,ID_RANK_COMBINATION_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_915,WRONG_TYPE,WRONG_TYPE,WRONG_TYPE));
		m_lstChamps.add(new RefTableChamp(_REF_916,PRIMARY_KEY_ALREADY_EXISTING,PRIMARY_KEY_ALREADY_EXISTING,PRIMARY_KEY_ALREADY_EXISTING));
		m_lstChamps.add(new RefTableChamp(_REF_917,OFFICE_ID_ALREADY_EXISTS,OFFICE_ID_ALREADY_EXISTS,OFFICE_ID_ALREADY_EXISTS));
		m_lstChamps.add(new RefTableChamp(_REF_918,NATIONALITY_MANDATORY,NATIONALITY_MANDATORY,NATIONALITY_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_919,AGENCY_GIN_NOT_ALLOWED,AGENCY_GIN_NOT_ALLOWED,AGENCY_GIN_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_920,ENGLISH_COLUMN_NOT_FOUND,ENGLISH_COLUMN_NOT_FOUND,ENGLISH_COLUMN_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_921,PRIMARY_COLUMN_NOT_FOUND,PRIMARY_COLUMN_NOT_FOUND,PRIMARY_COLUMN_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_922,REFERENCE_TABLE_NOT_FOUND,REFERENCE_TABLE_NOT_FOUND,REFERENCE_TABLE_NOT_FOUND));
		m_lstChamps.add(new RefTableChamp(_REF_923,INVALID_CHECK_DIGIT,INVALID_CHECK_DIGIT,INVALID_CHECK_DIGIT));
		m_lstChamps.add(new RefTableChamp(_REF_924,INVALID_SALES_ZONE,INVALID_SALES_ZONE,INVALID_SALES_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_925,SALES_ZONE_MISSING,SALES_ZONE_MISSING,SALES_ZONE_MISSING));
		m_lstChamps.add(new RefTableChamp(_REF_926,SALES_ZONE_MANDATORY,SALES_ZONE_MANDATORY,SALES_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_927,COMMERCIAL_ZONE_MANDATORY,COMMERCIAL_ZONE_MANDATORY,COMMERCIAL_ZONE_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_928,INVALID_COMMERCIAL_ZONE,INVALID_COMMERCIAL_ZONE,INVALID_COMMERCIAL_ZONE));
		m_lstChamps.add(new RefTableChamp(_REF_929,RA2_FLAG_MANDATORY,RA2_FLAG_MANDATORY,RA2_FLAG_MANDATORY));
		m_lstChamps.add(new RefTableChamp(_REF_930,CITY_ZONE_LINK_UNKNOWN,CITY_ZONE_LINK_UNKNOWN,CITY_ZONE_LINK_UNKNOWN));
		m_lstChamps.add(new RefTableChamp(_REF_931,RA2_AGENCY_NOT_ALLOWED,RA2_AGENCY_NOT_ALLOWED,RA2_AGENCY_NOT_ALLOWED));
		m_lstChamps.add(new RefTableChamp(_REF_932,INVALID_PARAMETER,INVALID_PARAMETER,INVALID_PARAMETER));
		m_lstChamps.add(new RefTableChamp(_REF_933,TOO_MANY_FIRMS_FOUND_REFINE_CRITERIA,TOO_MANY_FIRMS_FOUND_REFINE_CRITERIA,TOO_MANY_FIRMS_FOUND_REFINE_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_934,DEFAULT_VALUES_RETURNED,DEFAULT_VALUES_RETURNED,DEFAULT_VALUES_RETURNED));
		m_lstChamps.add(new RefTableChamp(_REF_935,DEFAULT_VALUES_TOO_MANY_FIRMS_FOUND_CHECK_CRITERIA,DEFAULT_VALUES_TOO_MANY_FIRMS_FOUND_CHECK_CRITERIA,DEFAULT_VALUES_TOO_MANY_FIRMS_FOUND_CHECK_CRITERIA));
		m_lstChamps.add(new RefTableChamp(_REF_940,PP_ALREADY_EXIST, PP_ALREADY_EXIST, PP_ALREADY_EXIST));
		m_lstChamps.add(new RefTableChamp(_REF_941,CANNOT_CREATE_LINK_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_CREATE_LINK_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_CREATE_LINK_BETWEEN_AGENCY_AND_R_OR_S));
		m_lstChamps.add(new RefTableChamp(_REF_942,CANNOT_UPDAT_LINKE_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_UPDAT_LINKE_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_UPDAT_LINKE_BETWEEN_AGENCY_AND_R_OR_S));
		m_lstChamps.add(new RefTableChamp(_REF_943,CANNOT_DELETE_LINK_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_DELETE_LINK_BETWEEN_AGENCY_AND_R_OR_S, CANNOT_DELETE_LINK_BETWEEN_AGENCY_AND_R_OR_S));
	}

	public static RefTableREF_ERREUR instance() {
		if (null == m_RefTableREF_ERREUR) {
			m_RefTableREF_ERREUR = new RefTableREF_ERREUR();
		}
		return m_RefTableREF_ERREUR;
	}


}
