bases:
  - ../base

resources:
  - ingress.yaml

nameSuffix: -ite

namespace: repind-ite

commonLabels:
  app.kubernetes.io/name: manage-doctor-attributes
  app.kubernetes.io/instance: manage-doctor-attributes-ite

images:
  - name: harbor-vlb.af-klm.com/cdm/manage-doctor-attributes

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - replica-rollout.yaml
  - deploy-profile.yaml