BEGIN
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_NOMPRE')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_NOMPRE purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_NOMPRE_GIN')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_NOMPRE_GIN purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_EMAIL')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_EMAIL purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_POT_DUPPLICATE')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_POT_DUPPLICATE purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_TELECOM')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_TELECOM purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_IND_EMAIL')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_IND_EMAIL purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_IND_TELECOM')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_IND_TELECOM purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_DUP_TMP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_DUP_TMP purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_DUP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_DUP purge ';
        END LOOP;
-- NEW
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_NOMPRE_EMAIL_GIN')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_NOMPRE_EMAIL_GIN purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_EMAIL_GIN_NO_DUP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_EMAIL_GIN_NO_DUP purge ';
        END LOOP;
    FOR i IN (SELECT NULL
              FROM USER_OBJECTS
              WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_SAME_NOMPRE_TELECOM_GIN')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_SAME_NOMPRE_TELECOM_GIN purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_MGE_TELECOM_GIN_NO_DUP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_MGE_TELECOM_GIN_NO_DUP purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_NOMPRENOM_TELECOM_EMAIL')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_NOMPRENOM_TELECOM_EMAIL purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_NOMPRENOM_TELECOM_EMAIL_TMP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_NOMPRENOM_TELECOM_EMAIL_TMP purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_NOMPRENOM_EMAIL_OR_TEL')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_NOMPRENOM_EMAIL_OR_TEL purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_NP_TELECOM_EMAIL_NODUP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_NP_TELECOM_EMAIL_NODUP purge ';
        END LOOP;
    FOR i IN (SELECT NULL FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE' AND OBJECT_NAME = 'DQ_NOMPRENOM_EMAIL_OR_TEL_TMP')
        LOOP
            EXECUTE IMMEDIATE 'DROP TABLE DQ_NOMPRENOM_EMAIL_OR_TEL_TMP purge ';
        END LOOP;
    COMMIT;
END;