spring:
  datasource:
    tns_admin_env: PROD
    url: jdbc:oracle:thin:@REPIND_PRD.WORLD

vault:
  uri: https://vault-tls.airfranceklm.com
  namespace: repind
  env: prod
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

server:
  servlet:
    context-path: /api-mgr

