
package com.afklm.bird.ws.w000311;

import com.afklm.bird.ws.w000311.data.schema6538.BirdWSStationBusinessFault;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BirdWSStationBusinessFaultElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd")
public class MsgBirdWSStationBusinessFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BirdWSStationBusinessFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MsgBirdWSStationBusinessFault(String message, BirdWSStationBusinessFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public MsgBirdWSStationBusinessFault(String message, BirdWSStationBusinessFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.afklm.bird.ws.w000311.data.schema6538.BirdWSStationBusinessFault
     */
    public BirdWSStationBusinessFault getFaultInfo() {
        return faultInfo;
    }

}
