
package com.afklm.bird.ws.w000311;

import com.afklm.bird.ws.w000311.data.schema6538.StationRequest;
import com.afklm.bird.ws.w000311.data.schema6538.StationResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProvideStationInformation-v1", targetNamespace = "http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.afklm.bird.ws.w000311.data.schema5299.ObjectFactory.class,
    com.afklm.bird.ws.w000311.data.schema6538.ObjectFactory.class,
    com.afklm.bird.ws.w000311.data.schema5297.ObjectFactory.class,
    com.afklm.bird.ws.w000311.data.schema864.ObjectFactory.class
})
public interface ProvideStationInformationV1 {


    /**
     * 
     * @param criteria
     * @return
     *     returns com.afklm.bird.ws.w000311.data.schema6538.StationResponse
     * @throws SystemFault
     * @throws MsgBirdWSStationBusinessFault
     */
    @WebMethod(action = "http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/provideStationInformation")
    @WebResult(name = "StationResponseElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd", partName = "results")
    public StationResponse provideStationInformation(
        @WebParam(name = "StationRequestElement", targetNamespace = "http://www.af-klm.com/services/passenger/geographyOperationData-v1/xsd", partName = "criteria")
        StationRequest criteria)
        throws MsgBirdWSStationBusinessFault, SystemFault
    ;

}
