
package com.afklm.bird.ws.w000311;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProvideStationInformationService-v1", targetNamespace = "http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/wsdl", wsdlLocation = "http://www.af-klm.com/passenger_ProvideStationInformation-v01.wsdl")
public class ProvideStationInformationServiceV1
    extends Service
{

    private final static URL PROVIDESTATIONINFORMATIONSERVICEV1_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.afklm.bird.ws.w000311.ProvideStationInformationServiceV1 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.afklm.bird.ws.w000311.ProvideStationInformationServiceV1 .class.getResource(".");
            url = new URL(baseUrl, "http://www.af-klm.com/passenger_ProvideStationInformation-v01.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.af-klm.com/passenger_ProvideStationInformation-v01.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROVIDESTATIONINFORMATIONSERVICEV1_WSDL_LOCATION = url;
    }

    public ProvideStationInformationServiceV1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvideStationInformationServiceV1() {
        super(PROVIDESTATIONINFORMATIONSERVICEV1_WSDL_LOCATION, new QName("http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/wsdl", "ProvideStationInformationService-v1"));
    }

    /**
     * 
     * @return
     *     returns ProvideStationInformationV1
     */
    @WebEndpoint(name = "ProvideStationInformation-v1-soap11http")
    public ProvideStationInformationV1 getProvideStationInformationV1Soap11Http() {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/wsdl", "ProvideStationInformation-v1-soap11http"), ProvideStationInformationV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvideStationInformationV1
     */
    @WebEndpoint(name = "ProvideStationInformation-v1-soap11http")
    public ProvideStationInformationV1 getProvideStationInformationV1Soap11Http(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.af-klm.com/services/passenger/ProvideStationInformation-v1/wsdl", "ProvideStationInformation-v1-soap11http"), ProvideStationInformationV1.class, features);
    }

}
