set serveroutput on;
set heading off;
set pagesize 0;
set line 130;
set feed off;
set head off;
set trimspool on;
SET NEWPAGE 0;
SET SPACE 0;
SET LINESIZE 500;
SET PAGESIZE 0;
SET ECHO OFF;
SET FEEDBACK OFF;
SET HEADING OFF;
SET ARRAYSIZE 500;


select em.sain ||';'|| em.sgin||';'|| em.semail||';'||em.SSTATUT_MEDIUM||';'||em.scode_medium||';'|| to_char(em.DDATE_MODIFICATION,'DD/MM/YYYY HH24:MI:SS')||';'||em.SSIGNATURE_MODIFICATION
from sic2.emails em where em.sgin is not null and em.sstatut_medium !='X' and (
            em.semail like'%' || CHR(1) || '%'
        or em.semail like '%' || CHR(2)|| '%'
        or em.semail like '%' || CHR(3)|| '%'
        or em.semail like '%' || CHR(4)|| '%'
        or em.semail like '%' || CHR(5)|| '%'
        or em.semail like '%' || CHR(6)|| '%'
        or em.semail like '%' || CHR(7)|| '%'
        or em.semail like '%' || CHR(8)|| '%'
        or em.semail like '%' || CHR(9)|| '%'
        or em.semail like '%' || CHR(10)|| '%'
        or em.semail like '%' || CHR(11)|| '%'
        or em.semail like '%' || CHR(12)|| '%'
        or em.semail like '%' || CHR(13)|| '%'
        or em.semail like '%' || CHR(14)|| '%'
        or em.semail like '%' || CHR(15)|| '%'
        or em.semail like '%' || CHR(16)|| '%'
        or em.semail like '%' || CHR(17)|| '%'
        or em.semail like '%' || CHR(18)|| '%'
        or em.semail like '%' || CHR(19)|| '%'
        or em.semail like '%' || CHR(20)|| '%'
        or em.semail like '%' || CHR(21)|| '%'
        or em.semail like '%' || CHR(22)|| '%'
        or em.semail like '%' || CHR(23)|| '%'
        or em.semail like '%' || CHR(24)|| '%'
        or em.semail like '%' || CHR(25)|| '%'
        or em.semail like '%' || CHR(26)|| '%'
        or em.semail like '%' || CHR(27)|| '%'
        or em.semail like '%' || CHR(28)|| '%'
        or em.semail like '%' || CHR(29)|| '%'
        or em.semail like '%' || CHR(30)|| '%'
        or em.semail like '%' || CHR(31)|| '%'
        or em.semail like '%' || CHR(33)|| '%'
        or em.semail like '%' || CHR(34)|| '%'
        or em.semail like '%' || CHR(35)|| '%'
        or em.semail like '%' || CHR(91)|| '%'
        or em.semail like '%' || CHR(92)|| '%'
        or em.semail like '%' || CHR(93)|| '%'
        or em.semail like '%' || CHR(94)|| '%'
        or em.semail like '%' || CHR(96)|| '%'
        or em.semail like '%' || CHR(123)|| '%'
        or em.semail like '%' || CHR(124)|| '%'
        or em.semail like '%' || CHR(125)|| '%'
        or em.semail like '%' || CHR(126)|| '%'
        or em.semail like '%' || CHR(127)|| '%'
        or em.semail like '%' || CHR(128)|| '%'
        or em.semail like '%' || CHR(129)|| '%'
        or em.semail like '%' || CHR(130)|| '%'
        or em.semail like '%' || CHR(131)|| '%'
        or em.semail like '%' || CHR(132)|| '%'
        or em.semail like '%' || CHR(133)|| '%'
        or em.semail like '%' || CHR(134)|| '%'
        or em.semail like '%' || CHR(135)|| '%'
        or em.semail like '%' || CHR(136)|| '%'
        or em.semail like '%' || CHR(137)|| '%'
        or em.semail like '%' || CHR(138)|| '%'
        or em.semail like '%' || CHR(139)|| '%'
        or em.semail like '%' || CHR(140)|| '%'
        or em.semail like '%' || CHR(141)|| '%'
        or em.semail like '%' || CHR(142)|| '%'
        or em.semail like '%' || CHR(143)|| '%'
        or em.semail like '%' || CHR(144)|| '%'
        or em.semail like '%' || CHR(145)|| '%'
        or em.semail like '%' || CHR(146)|| '%'
        or em.semail like '%' || CHR(147)|| '%'
        or em.semail like '%' || CHR(148)|| '%'
        or em.semail like '%' || CHR(149)|| '%'
        or em.semail like '%' || CHR(150)|| '%'
        or em.semail like '%' || CHR(151)|| '%'
        or em.semail like '%' || CHR(152)|| '%'
        or em.semail like '%' || CHR(153)|| '%'
        or em.semail like '%' || CHR(154)|| '%'
        or em.semail like '%' || CHR(155)|| '%'
        or em.semail like '%' || CHR(156)|| '%'
        or em.semail like '%' || CHR(157)|| '%'
        or em.semail like '%' || CHR(158)|| '%'
        or em.semail like '%' || CHR(159)|| '%'
        or em.semail like '%' || CHR(160)|| '%'
        or em.semail like '%' || CHR(161)|| '%'
        or em.semail like '%' || CHR(162)|| '%'
        or em.semail like '%' || CHR(163)|| '%'
        or em.semail like '%' || CHR(164)|| '%'
        or em.semail like '%' || CHR(165)|| '%'
        or em.semail like '%' || CHR(166)|| '%'
        or em.semail like '%' || CHR(167)|| '%'
        or em.semail like '%' || CHR(168)|| '%'
        or em.semail like '%' || CHR(169)|| '%'
        or em.semail like '%' || CHR(170)|| '%'
        or em.semail like '%' || CHR(171)|| '%'
        or em.semail like '%' || CHR(172)|| '%'
        or em.semail like '%' || CHR(173)|| '%'
        or em.semail like '%' || CHR(174)|| '%'
        or em.semail like '%' || CHR(175)|| '%'
        or em.semail like '%' || CHR(176)|| '%'
        or em.semail like '%' || CHR(177)|| '%'
        or em.semail like '%' || CHR(178)|| '%'
        or em.semail like '%' || CHR(179)|| '%'
        or em.semail like '%' || CHR(180)|| '%'
        or em.semail like '%' || CHR(181)|| '%'
        or em.semail like '%' || CHR(182)|| '%'
        or em.semail like '%' || CHR(183)|| '%'
        or em.semail like '%' || CHR(184)|| '%'
        or em.semail like '%' || CHR(185)|| '%'
        or em.semail like '%' || CHR(186)|| '%'
        or em.semail like '%' || CHR(187)|| '%'
        or em.semail like '%' || CHR(188)|| '%'
        or em.semail like '%' || CHR(189)|| '%'
        or em.semail like '%' || CHR(190)|| '%'
        or em.semail like '%' || CHR(191)|| '%'
        or em.semail like '%' || CHR(198)|| '%'
        or em.semail like '%' || CHR(215)|| '%'
        or em.semail like '%' || CHR(216)|| '%'
        or em.semail like '%' || CHR(222)|| '%'
        or em.semail like '%' || CHR(223)|| '%'
        or em.semail like '%' || CHR(230)|| '%'
        or em.semail like '%' || CHR(240)|| '%'
        or em.semail like '%' || CHR(247)|| '%'
        or em.semail like '%' || CHR(248)|| '%'
        or em.semail like '%' || CHR(254)|| '%'
    );
PROMPT
exit;
/