DROP TABLE IF EXISTS LAST_ACTIVITY;

CREATE TABLE LAST_ACTIVITY
(
    LAST_ACTIVITY_ID  INT AUTO_INCREMENT  PRIMARY KEY ,
    SGIN VARCHAR NOT NULL ,
    DDATE_MODIFICATION DATE NOT NULL ,
    SSIGNATURE_MODIFICATION VARCHAR,
    SSITE_MODIFICATION VARCHAR,
    SSOURCE_MODIFICATION VARCHAR,
    CONSTRAINT LAST_ACTIVITY_PK PRIMARY KEY (LAST_ACTIVITY_ID)
)
