server:
  servlet:
    context-path: /api-mgr

spring:
  neo4j:
    uri: bolt://10.66.10.53//:7687
    authentication:
      username: ${ri_repind_neo4j_username}
      password: ${ri_repind_neo4j_password}


