package com.afklm.repind.v7.createorupdateindividualws.type;

public enum UltimateInputErrorCode {

	DELEGATOR_DOESNT_EXIST,
	DELEGATE_DOESNT_EXIST,
	DELEGATE_IS_NOT_A_ULTIMATE_CUSTOMER,
	DELEGATOR_IS_NOT_A_FLYING_BLUE_CUSTOMER,
	ULTIMATE_DELEGATION_TYPE_NOT_ACCEPTED,
	DELEGATE_IS_NOT_A_FLYING_BLUE_CUSTOMER,
	DELEGATE_DOESNT_HAVE_ACCOUNT_DATA,
	DELEGATOR_IS_ULTIMATE_CUSTOMER_HIMSELF,
	DELEGATOR_DOESNT_HAVE_ACCOUNT_DATA,
	SENDER_MUST_BE_THE_DELEGATE;
}
