package com.afklm.repindpp.paymentpreference.entity;
// Generated 17 ao�t 2018 09:59:28 by Hibernate Tools 5.2.11.Final

import javax.persistence.*;

/**
 * EnvVarPp generated by hbm2java
 */
@Entity
@Table(name = "ENV_VAR_PP", schema = "REPIND_PP")
public class EnvVarPp implements java.io.Serializable {

	private EnvVarPpId id;

	public EnvVarPp() {
	}

	public EnvVarPp(EnvVarPpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "envKeyPp", column = @Column(name = "ENV_KEY_PP", length = 30)),
			@AttributeOverride(name = "envValuePp", column = @Column(name = "ENV_VALUE_PP", length = 30)) })
	public EnvVarPpId getId() {
		return this.id;
	}

	public void setId(EnvVarPpId id) {
		this.id = id;
	}

}
