package com.afklm.repindpp.paymentpreference.entity;
// Generated 17 ao�t 2018 09:59:28 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnvVarPpId generated by hbm2java
 */
@Embeddable
public class EnvVarPpId implements java.io.Serializable {

	private String envKeyPp;
	private String envValuePp;

	public EnvVarPpId() {
	}

	public EnvVarPpId(String envKeyPp, String envValuePp) {
		this.envKeyPp = envKeyPp;
		this.envValuePp = envValuePp;
	}

	@Column(name = "ENV_KEY_PP", length = 30)
	public String getEnvKeyPp() {
		return this.envKeyPp;
	}

	public void setEnvKeyPp(String envKeyPp) {
		this.envKeyPp = envKeyPp;
	}

	@Column(name = "ENV_VALUE_PP", length = 30)
	public String getEnvValuePp() {
		return this.envValuePp;
	}

	public void setEnvValuePp(String envValuePp) {
		this.envValuePp = envValuePp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnvVarPpId))
			return false;
		EnvVarPpId castOther = (EnvVarPpId) other;

		return ((this.getEnvKeyPp() == castOther.getEnvKeyPp()) || (this.getEnvKeyPp() != null
				&& castOther.getEnvKeyPp() != null && this.getEnvKeyPp().equals(castOther.getEnvKeyPp())))
				&& ((this.getEnvValuePp() == castOther.getEnvValuePp())
						|| (this.getEnvValuePp() != null && castOther.getEnvValuePp() != null
								&& this.getEnvValuePp().equals(castOther.getEnvValuePp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEnvKeyPp() == null ? 0 : this.getEnvKeyPp().hashCode());
		result = 37 * result + (getEnvValuePp() == null ? 0 : this.getEnvValuePp().hashCode());
		return result;
	}

}
