CREATE TABLE INDIVIDUS_ALL
   (
    SGIN VARCHAR(12),
    IVERSION NUMBER(12),
    SCIVILITE VARCHAR(4),
    SMOT_DE_PASSE VARCHAR(10),
    SNOM VARCHAR(35),
    SALIAS VARCHAR(35),
    SPRENOM VARCHAR(25),
    SSECOND_PRENOM VARCHAR(25),
    SALIAS_PRENOM VARCHAR(25),
    SSEXE VARCHAR(1),
    SIDENTIFIANT_PERSONNEL VARCHAR(16),
    DDATE_NAISSANCE DATE,
    SSTATUT_INDIVIDU VARCHAR(1),
    SCODE_TITRE VARCHAR(3),
    SNATIONALITE VARCHAR(2),
    SAUTRE_NATIONALITE VARCHAR(2),
    SNON_FUSIONNABLE VARCHAR(1),
    SSITE_CREATION VARCHAR2(10),
    SSIGNATURE_CREATION VARCHAR(16),
    DDATE_CREATION DATE,
    SSITE_MODIFICATION VARCHAR(10),
    SSIGNATURE_MODIFICATION VARCHAR(16),
    DDATE_MODIFICATION DATE,
    SSITE_FRAUDEUR VARCHAR(10),
    SSIGNATURE_FRAUDEUR VARCHAR(16),
    DDATE_MOD_FRAUDEUR DATE,
    SSITE_MOT_PASSE VARCHAR(10),
    SSIGNATURE_MOT_PASSE VARCHAR(16),
    DDATE_MOD_MOT_DE_PASSE DATE,
    SFRAUDEUR_CARTE_BANCAIRE VARCHAR(1),
    STIER_UTILISE_COMME_PIEGE VARCHAR(1),
    SALIAS_NOM1 VARCHAR(35),
    SALIAS_NOM2 VARCHAR(35),
    SALIAS_PRE1 VARCHAR(25),
    SALIAS_PRE2 VARCHAR(25),
    SALIAS_CIV1 VARCHAR(4),
    SALIAS_CIV2 VARCHAR(4),
    SINDICT_NP VARCHAR(40),
    SINDICT_NOM VARCHAR(35),
    SINDCONS VARCHAR(30),
    SGIN_FUSION VARCHAR(12),
    DDATE_FUSION DATE,
    SPROV_AMEX VARCHAR(1),
    SCIE_GEST VARCHAR(3),
    SNOM_TYPO VARCHAR(35),
    SPRENOM_TYPO VARCHAR(25),
    SNOM_TYPO2 VARCHAR(140),
    SPRENOM_TYPO2 VARCHAR(100),
    STYPE VARCHAR(1) DEFAULT 'I'
    );

CREATE TABLE ROLE_CONTRATS
   (
    SRIN VARCHAR(16),
	IVERSION NUMBER(12),
	SNUMERO_CONTRAT VARCHAR(20),
	SGIN VARCHAR(12),
	SETAT VARCHAR(1),
	STYPE_CONTRAT VARCHAR(10),
	SSOUS_TYPE VARCHAR(10),
	STIER VARCHAR(1),
	SCODE_COMPAGNIE VARCHAR(3),
	IVERSION_PRODUIT NUMBER(20),
	DFIN_VALIDITE DATE,
	DDEBUT_VALIDITE DATE,
	SFAMILLE_TRAITEMENT VARCHAR(1),
	SFAMILLE_PRODUIT VARCHAR(3),
	ICLE_ROLE NUMBER(10),
	DDATE_CREATION DATE,
	SSIGNATURE_CREATION VARCHAR(16),
	DDATE_MODIFICATION DATE,
	SSIGNATURE_MODIFICATION VARCHAR(16),
	SSITE_CREATION VARCHAR(10),
	SSITE_MODIFICATION VARCHAR(10),
	SAGENCE_IATA VARCHAR(8),
	IATA VARCHAR(8),
	SSOURCE_ADHESION VARCHAR(4),
	SPERMISSION_PRIME VARCHAR(1),
	ISOLDE_MILES NUMBER(8),
	IMILES_QUALIF NUMBER(8),
	IMILES_QUALIF_PREC NUMBER(8),
	ISEGMENTS_QUALIF NUMBER(4),
	ISEGMENTS_QUALIF_PREC NUMBER(4),
	CUSCO_CREATED VARCHAR(1),
	SMEMBER_TYPE VARCHAR(2)
	);

CREATE TABLE EMAILS
   (
	SAIN VARCHAR(16),
	SGIN VARCHAR(12),
	IVERSION NUMBER(12),
	SCODE_MEDIUM VARCHAR(1),
	SSTATUT_MEDIUM VARCHAR(1),
	SEMAIL VARCHAR(60),
	SDESCRIPTIF_COMPLEMENTAIRE VARCHAR(30),
	SAUTORISATION_MAILING VARCHAR(1),
	SSIGNATURE_MODIFICATION VARCHAR(16),
	SSITE_MODIFICATION VARCHAR(10),
	DDATE_MODIFICATION DATE,
	SSIGNATURE_CREATION VARCHAR(16),
	SSITE_CREATION VARCHAR(10),
	DDATE_CREATION DATE,
	SGIN_PM VARCHAR(12),
	ICLE_ROLE NUMBER(10),
	ICLE_FONCTION NUMBER(10),
	IKEY_TEMP NUMBER(10),
	SEMAIL_NORMALIZED_LOWER VARCHAR(60),
	SEMAIL_NORMALIZED_CHAR VARCHAR(60)
   );

CREATE TABLE COMMUNICATION_PREFERENCES
   (
	COM_PREF_ID NUMBER(12),
	ACCOUNT_IDENTIFIER VARCHAR(8),
	SGIN VARCHAR(12),
	COM_GROUP_TYPE VARCHAR(7),
	COM_TYPE VARCHAR(7),
	SUBSCRIBE VARCHAR(1),
	MEDIA1 VARCHAR(1),
	MEDIA2 VARCHAR(1),
	MEDIA3 VARCHAR(1),
	MEDIA4 VARCHAR(1),
	MEDIA5 VARCHAR(1),
	DOMAIN VARCHAR(7),
	CREATION_DATE TIMESTAMP (6),
	CREATION_SIGNATURE VARCHAR(16),
	CREATION_SITE VARCHAR(10),
	DATE_OPTIN TIMESTAMP (6),
	DATE_OPTIN_PARTNERS TIMESTAMP (6),
	DATE_OF_ENTRY TIMESTAMP (6),
	MODIFICATION_DATE TIMESTAMP (6),
	MODIFICATION_SIGNATURE VARCHAR(16),
	MODIFICATION_SITE VARCHAR(10),
	OPTIN_PARTNERS VARCHAR(1),
	CHANNEL VARCHAR(16)
   );

CREATE TABLE MARKET_LANGUAGE
   (
	MARKET_LANGUAGE_ID NUMBER(12),
	COM_PREF_ID NUMBER(12),
	MEDIA1 VARCHAR(1),
	MEDIA2 VARCHAR(1),
	MEDIA3 VARCHAR(1),
	MEDIA4 VARCHAR(1),
	MEDIA5 VARCHAR(1),
	CREATION_DATE TIMESTAMP (6),
	CREATION_SIGNATURE VARCHAR(16),
	CREATION_SITE VARCHAR(10),
	DATE_OPTIN TIMESTAMP (6),
	LANGUAGE_CODE VARCHAR(2),
	MARKET VARCHAR(3),
	MODIFICATION_DATE TIMESTAMP (6),
	MODIFICATION_SIGNATURE VARCHAR(16),
	MODIFICATION_SITE VARCHAR(10),
	OPTIN VARCHAR(1)
   );

CREATE TABLE LANGUES
   (
	SCODE_LANGUE VARCHAR(2),
	SLIBELLE_LANGUE VARCHAR(20),
	SCODE_IATA VARCHAR(3),
	SLIBELLE_LANGUE_EN VARCHAR(20)
   );

   Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('DI','DIVERS','MIS','MISCELLANEOUS');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('EN','ANGLAIS','ENG','ENGLISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AR','ARABE','ARA','ARAB');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ZH','CHINOIS SIMPLIFIE','CHI','SIMPLIFIED CHINESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('DA','DANOIS','DAN','DANISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ES','ESPAGNOL','SPA','SPANISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FR','FRANCAIS','FRE','FRENCH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('DE','ALLEMAND','GER','GERMAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('EL','GREC','GRE','GREEK');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IT','ITALIEN','ITA','ITALIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KO','COREEN','KOR','KOREAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NO','NORVEGIEN','NOR','NORVEGIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FI','FINNOIS','FIN','FINNISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CT','CHINOIS TRADITIONNEL','CHT','TRADITIONAL CHINESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('PT','PORTUGUAIS','POR','PORTUGESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('RU','RUSSE','RUS','RUSSIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SV','SUEDOIS','SWE','SWEDISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TR','TURC','TUR','TURKISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('JA','JAPONAIS','JAP','JAPANESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NL','NEERLANDAIS','DUT','DUTCH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('RO','ROUMAIN','ROM','ROMANIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AA','AFAR','AAR','AFAR');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AB','ABKHAZE','ABK','ABKHAZIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AE','AVESTIQUE','AVE','AVESTAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AF','AFRIKAANS','AFR','AFRIKAANS');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AK','AKAN','AKA','AKAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AM','AMHARIQUE','AMH','AMHARIC');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AN','ARAGONAIS','ARG','ARAGONESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AS','ASSAMAIS','ASM','ASSAMESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AV','AVAR','AVA','AVARIC');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AY','AYMARA','AYM','AYMARA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('AZ','AZ?RI','AYM','AZERBAIJANI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BA','BACHKIR','BAK','BASHKIR');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BE','BI?LORUSSE','BEL','BELARUSIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BG','BULGARE','BUL','BULGARIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BH','BIHARI','BIH','BIHARI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BI','BICHELAMAR','BIS','BISLAMA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BM','BAMBARA','BAM','BAMBARA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BN','BENGAL?','BEN','BENGALI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BO','TIB?TAIN','BOD','TIBETAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BR','BRETON','BRE','BRETON');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('BS','BOSNIEN','BOS','BOSNIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CA','CATALAN','CAT','CATALAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CE','TCH?TCH?NE','CHE','CHECHEN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CH','CHAMORRO','CHA','CHAMORRO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CO','CORSE','COS','CORSICAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CR','CRI','CES','CREE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CS','TCH?QUE','CES','CZECH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CU','VIEUX SLAVE','CHU','OLD CHURCH SLAVONIC');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CV','TCHOUVACHE','CHV','CHUVASH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('CY','GALLOIS','CYM','WELSH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('DV','DIVEHI','DIV','DIVEHI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('DZ','DZONGKHA','DZO','DZONGKHA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('EE','EWE','EWE','EWE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('EO','ESP?RANTO','EPO','ESPERANTO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ET','ESTONIEN','EST','ESTONIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('EU','BASQUE','EUS','BASQUE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FA','PERSAN','FAS','PERSIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FF','PEUL','FUL','FULAH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FJ','FIDJIEN','FIJ','FIJIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FO','F?RINGIEN','FAO','FAROESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('FY','FRISON','FRY','WESTERN FRISIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GA','IRLANDAIS','GLE','IRISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GD','?COSSAIS','GLA','SCOTTISH GAELIC');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GL','GALICIEN','GLG','GALICIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GN','GUARANI','GRN','GUARANI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GU','GUJAR?T?','GUJ','GUJARATI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('GV','MANNOIS','GLV','MANX');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HA','HAOUSSA','HAU','HAUSA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HE','H?BREU','HEB','HEBREW');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HI','HIND?','HIN','HINDI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HO','HIRI MOTU','HMO','HIRI MOTU');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HR','CROATE','HRV','CROATIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HT','CR?OLE HA?TIEN','HAT','HAITIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HU','HONGROIS','HUN','HUNGARIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HY','ARM?NIEN','HYE','ARMENIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('HZ','HERERO','HER','HERERO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IA','INTERLINGUA','INA','INTERLINGUA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ID','INDON?SIEN','IND','INDONESIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IE','OCCIDENTAL','ILE','INTERLINGUE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IG','IGBO','IBO','IGBO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('II','YI','III','SICHUAN YI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IK','INUPIAQ','IPK','INUPIAQ');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IO','IDO','IDO','IDO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IS','ISLANDAIS','ISL','ICELANDIC');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('IU','INUKTITUT','IKU','INUKTITUT');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('JV','JAVANAIS','JAV','JAVANESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KA','G?ORGIEN','KAT','GEORGIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KG','KIKONGO','KON','KONGO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KI','KIKUYU','KIK','KIKUYU');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KJ','KUANYAMA','KUA','KWANYAMA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KK','KAZAKH','KAZ','KAZAKH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KL','KALAALLISUT','KAL','KALAALLISUT');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KM','KHMER','KHM','KHMER');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KN','KANNARA','KAN','KANNADA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KR','KANOURI','KAU','KANURI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KS','KASHMIRI','KAS','KASHMIRI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KU','KURDE','KUR','KURDISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KV','KOMI','KOM','KOMI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KW','CORNIQUE','COR','CORNISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('KY','KIRGHIZ','KIR','KIRGHIZ');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LA','LATIN','LAT','LATIN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LB','LUXEMBOURGEOIS','LTZ','LUXEMBOURGISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LG','GANDA','LUG','GANDA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LI','LIMBOURGEOIS','LIM','LIMBURGISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LN','LINGALA','LIN','LINGALA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LO','LAO','LAO','LAO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LT','LITUANIEN','LIT','LITHUANIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LU','TCHILUBA','LUB','LUBA-KATANGA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('LV','LETTON','LAV','LATVIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MG','MALGACHE','MLG','MALAGASY');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MH','MARSHALLAIS','MAH','MARSHALLESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MI','MAORINOUVELLEZ?LANDE','MRI','MAORI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MK','MAC?DONIEN','MKD','MACEDONIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ML','MALAYALAM','MAL','MALAYALAM');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MN','MONGOL','MON','MONGOLIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MO','MOLDAVE','MOL','MOLDAVIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MR','MAR?TH?','MAR','MARATHI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MS','MALAIS','MSA','MALAY');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MT','MALTAIS','MLT','MALTESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('MY','BIRMAN','MYA','BURMESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NA','NAURUAN','NAU','NAURU');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NB','NORV?GIEN BOKMAL','NOB','NORWEGIAN BOKMAL');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ND','ND?B?L? DU NORD','NDE','NORTH NDEBELE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NE','N?PALAIS','NEP','NEPALI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NG','NDONGA','NDO','NDONGA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NN','NORV?GIEN NYNORSK','NNO','NORWEGIAN NYNORSK');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NR','ND?B?L? DU SUD','NBL','SOUTH NDEBELE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NV','NAVAJO','NAV','NAVAJO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('NY','CHICHEWA','NYA','CHICHEWA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('OC','OCCITAN','OCI','OCCITAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('OJ','OJIBW?','OJI','OJIBWA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('OM','OROMO','ORM','OROMO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('OR','ORIYA','ORI','ORIYA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('OS','OSS?TE','OSS','OSSETIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('PA','PANJ?B?','PAN','PANJABI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('PI','P?LI','PLI','PALI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('PL','POLONAIS','POL','POLISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('PS','PACHTO','PUS','PASHTO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('QU','QUECHUA','QUE','QUECHUA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('RM','ROMANCHE','ROH','RAETO-ROMANCE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('RN','KIRUNDI','RUN','KIRUNDI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('RW','KINYARWANDA','KIN','KINYARWANDA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SA','SANSKRIT','SAN','SANSKRIT');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SC','SARDE','SRD','SARDINIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SD','SINDHI','SND','SINDHI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SE','SAME DU NORD','SME','NORTHERN SAMI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SG','SANGO','SAG','SANGO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SI','CINGALAIS','SIN','SINHALESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SK','SLOVAQUE','SLK','SLOVAK');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SL','SLOV?NE','SLV','SLOVENE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SM','SAMOAN','SMO','SAMOAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SN','SHONA','SNA','SHONA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SO','SOMALI','SOM','SOMALI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SQ','ALBANAIS','SQI','ALBANIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SR','SERBE','SRP','SERBIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SS','SISWATI','SSW','SWATI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ST','SOTHO DU SUD','SOT','SOTHO');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SU','SOUNDANAIS','SUN','SUNDANESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('SW','SWAHILI','SWA','SWAHILI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TA','TAMOUL','TAM','TAMIL');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TE','T?LOUGOU','TEL','TELUGU');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TG','TADJIK','TGK','TAJIK');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TH','THA?','THA','THAI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TI','TIGRINYA','TIR','TIGRINYA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TK','TURKM?NE','TUK','TURKMEN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TL','TAGALOG','TGL','TAGALOG');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TN','TSWANA','TSN','TSWANA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TO','TONGIEN','TON','TONGA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TS','TSONGA','TSO','TSONGA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TT','TATAR','TAT','TATAR');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TW','TWI','TWI','TWI');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('TY','TAHITIEN','TAH','TAHITIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('UG','OU?GHOUR','UIG','UIGHUR');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('UK','UKRAINIEN','UKR','UKRAINIAN');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('UR','OURDOU','URD','URDU');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('UZ','OUZBEK','UZB','UZBEK');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('VE','VENDA','VEN','VENDA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('VI','VIETNAMIEN','VIE','VIETNAMESE');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('VO','VOLAP?K','VOL','VOLAP?K');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('WA','WALLON','WLN','WALLOON');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('WO','WOLOF','WOL','WOLOF');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('XH','XHOSA','XHO','XHOSA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('YI','YIDDISH','YID','YIDDISH');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('YO','YORUBA','YOR','YORUBA');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ZA','ZHUANG','ZHA','ZHUANG');
Insert into LANGUES (SCODE_LANGUE,SLIBELLE_LANGUE,SCODE_IATA,SLIBELLE_LANGUE_EN) values ('ZU','ZOULOU','ZUL','ZULU');

CREATE TABLE REF_MARKET_COUNTRY_LANGUAGE
   (
	SCODE_MARKET VARCHAR2(5),
	SCODE_LANGUAGE_NO_ISO VARCHAR2(5),
	SCODE_LANGUAGE_ISO VARCHAR2(5),
	SCODE_CONTEXT VARCHAR2(10)
   );

Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('BR','BR','PT','CSM');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('BR','BR','PT','TESTAPP');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('CN','CN','ZH','CSM');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('FR','BR','PT','TESTAPP');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('FR','FR','FR','TESTAPP');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('HK','HK','ZH','CSM');
Insert into REF_MARKET_COUNTRY_LANGUAGE (SCODE_MARKET,SCODE_LANGUAGE_NO_ISO,SCODE_LANGUAGE_ISO,SCODE_CONTEXT) values ('TW','TW','ZH','CSM');

CREATE TABLE PAYS
   (
	SCODE_PAYS VARCHAR(2),
	SLIBELLE_PAYS VARCHAR(30),
	ICODE_IATA NUMBER(3),
	SLIBELLE_PAYS_EN VARCHAR(30),
	CODE_GESTION_CP VARCHAR(1) DEFAULT 'S',
	SCODE_CAPITALE VARCHAR(5),
	NORMALISABLE VARCHAR(1) DEFAULT 'N',
	FORMAT_ADR VARCHAR(2),
	IFORMAT_ADR NUMBER(2),
	SFORCAGE VARCHAR(1) DEFAULT 'O',
	STELECOM_COUNTRY_CODE VARCHAR(4),
	SCODE_ISO3 VARCHAR(3)
   );

Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AD','ANDORRE','11','ANDORRA','N','ALV','N','1',null,'O','376','AND');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AE','EMIRATS ARABES UNIS','855','UNITED ARAB EMIRATES','N','AUH','N','1',null,'O','971','ARE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AF','AFGHANISTAN','10','AFGHANISTAN','N','KBL','N','1',null,'O','93','AFG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AG','ANTIGUA ET BARBUDA','27','ANTIGUA AND BARBUDA','N','ANU','N','1',null,'O','1','ATG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AI','ANGUILLA','26','ANGUILLA','N','AXA','N','1',null,'O','1','AIA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AL','ALBANIE','15','ALBANIA','N','TIA','N','1',null,'O','355','ALB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AM','ARMENIE','33','ARMENIA','N','EVN','N','1',null,'O','374','ARM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AN','ANTILLES NEERLANDAISES','570','NETHERLANDS ANTILLES','N','SXM','N','1',null,'O',null,'ANT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AO','ANGOLA','25','ANGOLA','N','LAD','N','1',null,'O','244','AGO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AQ','ANTARCTIQUE',null,'ANTARCTICA','N','TNM','N','3',null,'O',null,'ATA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AR','ARGENTINE','30','ARGENTINA','S','BUE','N','1',null,'O','54','ARG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AS','SAMOA AMERICAINES','710','AMERICAN SAMOA','N','PPG','N','3',null,'O','1','ASM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AT','AUTRICHE','45','AUSTRIA','S','VIE','O','1',null,'O','43','AUT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AU','AUSTRALIE','40','AUSTRALIA','S','SYD','N','3',null,'O','61','AUS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AW','ARUBA','35','ARUBA','N','AUA','N','1',null,'O','297','ABW');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AZ','AZERBAIDJAN','50','AZERBAIJAN','N','BAK','N','4',null,'O','994','AZE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BA','BOSNIE HERZEGOVINE','86','BOSNIA AND HERZEGOVINA','N','SJJ','N','1',null,'O','387','BIH');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BB','BARBADE','105','BARBADOS','N','BGI','N','1',null,'O','1','BRB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BD','BANGLADESH','70','BANGLADESH','N','DAC','N','2',null,'O','880','BGD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BE','BELGIQUE','75','BELGIUM','S','BRU','O','1',null,'O','32','BEX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BF','BURKINA FASO','890','BURKINA FASO','N','OUA','N','1',null,'O','226','BFA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BG','BULGARIE','120','BULGARIA','N','SOF','N','1',null,'O','359','BGR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BH','BAHREIN','60','BAHRAIN','N','BAH','N','2',null,'O','973','BHR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BI','BURUNDI','130','BURUNDI','N','BJM','N','1',null,'O','257','BDI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BJ','BENIN','245','BENIN','N','COO','N','1',null,'O','229','BEN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BM','BERMUDES','80','BERMUDA','N','BDA','N','2',null,'O','1','BMU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BN','BRUNEI DARUSSALAM','115','BRUNEI DARUSSALAM','N','BWN','N','2',null,'O','673','BRN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BO','BOLIVIE','85','BOLIVIA','N','LPB','N','1',null,'O','591','BOL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BR','BRESIL','90','BRAZIL','N','RIO','O','3',null,'O','55','BRA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BS','BAHAMAS','55','BAHAMAS','N','NAS','N','1',null,'O','1','BHS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BT','BHOUTAN','83','BHUTAN','N','QJC','N','1',null,'O','975','BTN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BW','BOTSWANA','87','BOTSWANA','N','GBE','N','1',null,'O','267','BWA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BY','BELARUS','73','BELARUS','N','MSQ','N','1',null,'O','375','BLR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BZ','BELIZE','100','BELIZE','N','BZE','N','1',null,'O','501','BLZ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CA','CANADA','145','CANADA','S','YMQ','O','3',null,'O','1','CAN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CC','COCOS (KEELING), ILES','193','COCOS (KEELING) ISLANDS','N','CCK','N','3',null,'O','61','CCK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CE','DON T USE---> COMMUNAUTE EUR.',null,'DON T USE---> EUR. COMMUNITY','N',null,'N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CF','CENTRAFRICAINE, REPUBLIQUE','170','CENTRAL AFRICAN REPUBLIC','N','BGF','N','1',null,'O','236','CAF');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CG','CONGO','205','CONGO','N','BZV','N','1',null,'O','242','COG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CH','SUISSE','820','SWITZERLAND','S','GVA','O','1',null,'O','41','CHX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CI','COTE D IVOIRE','425','IVORY COAST','N','ABJ','N','1',null,'O','225','CIV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CK','COOK, ILES','215','COOK ISLANDS','N','RAR','N','2',null,'O','682','COK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CL','CHILI','185','CHILE','N','SCL','N','1',null,'O','56','CHL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CM','CAMEROUN','140','CAMEROON','N','DLA','N','1',null,'O','237','CMR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CN','CHINE','190','CHINA','S','PEK','N','7',null,'O','86','CHN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CO','COLOMBIE','195','COLOMBIA','N','BOG','N','1',null,'O','57','COL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CR','COSTA RICA','220','COSTA RICA','N','SJO','N','1',null,'O','506','CRI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CU','CUBA','225','CUBA','N','HAV','N','1',null,'O','53','CUB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CV','CAP VERT','165','CAPE VERDE','N','SID','N','1',null,'O','238','CPV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CY','CHYPRE','235','CYPRUS','N','LCA','N','1',null,'O','357','CYP');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CZ','TCHEQUE, REPUBLIQUE','240','CZECH REPUBLIC','N','PRG','N','1',null,'O','420','CZE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DE','ALLEMAGNE','320','GERMANY','S','FRA','N','1',null,'O','49','DEX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DJ','DJIBOUTI','750','DJIBOUTI','N','JIB','N','1',null,'O','253','DJI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DK','DANEMARK','250','DENMARK','S','CPH','N','1',null,'O','45','DNK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DM','DOMINIQUE','252','DOMINICA','N','DOM','N','1',null,'O','1','DMA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DO','DOMINICAINE, REPUBLIQUE','255','DOMINICAN REPUBLIC','N','SDQ','N','1',null,'O','1','DOM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('DZ','ALGERIE','20','ALGERIA','N','ALG','N','1',null,'O','213','DZA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('EC','EQUATEUR','260','ECUADOR','N','UIO','N','1',null,'O','593','ECU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('EE','ESTONIE','267','ESTONIA','N','TLL','N','1',null,'O','372','EST');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('EG','EGYPTE','875','EGYPT','N','CAI','N','2',null,'O','20','EGY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ES','ESPAGNE','780','SPAIN','S','MAD','N','6',null,'O','34','ESX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ET','ETHIOPIE','265','ETHIOPIA','N','ADD','N','1',null,'O','251','ETH');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FI','FINLANDE','285','FINLAND','N','HEL','O','4',null,'O','358','FIX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FJ','FIDJI','280','FIJI','N','NAN','N','1',null,'O','679','FJI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FK','FALKLAND, ILES (MALVINAS)','275','FALKLAND ISLANDS (MALVINAS)','N','PSY','N','2',null,'O','500','FLK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FM','MICRONESIE, ETATS FEDERES DE','537','MICRONESIA, FED. STATES OF','N','TKK','N','3',null,'O','691','FSM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FO','FEROE, ILES','277','FAROE ISLANDS','N','FAE','N','1',null,'O','298','FRO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('FR','FRANCE','295','FRANCE','S','PAR','O','1',null,'O','33','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GA','GABON','310','GABON','N','LBV','N','1',null,'O','241','GAB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GB','ROYAUME UNI','880','UNITED KINGDOM','S','LON','O','2',null,'O','44','GBR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GD','GRENADE','342','GRENADA','N','UNI','N','1',null,'O','1','GRD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GE','GEORGIE','317','GEORGIA','N','TBS','N','1',null,'O','995','GEO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GF','GUYANE FRANCAISE','300','FRENCH GUIANA','S','CAY','O','1',null,'O','594','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GH','GHANA','325','GHANA','N','ACC','N','1',null,'O','233','GHA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GI','GIBRALTAR','330','GIBRALTAR','N','GIB','N','2',null,'O','350','GIB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GL','GROENLAND','340','GREENLAND','N','JGO','N','1',null,'O','299','GRL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GM','GAMBIE','315','GAMBIA','N','BJL','N','1',null,'O','220','GMB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GN','GUINEE','360','GUINEA','N','CKY','N','1',null,'O','224','GIN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GP','GUADELOUPE','345','GUADELOUPE','S','PTP','O','1',null,'O','590','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GQ','GUINEE EQUATORIALE','264','EQUATORIAL GUINEA','N','BSG','N','1',null,'O','240','GNQ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GR','GRECE','335','GREECE','N','ATH','N','1',null,'O','30','GRC');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GT','GUATEMALA','355','GUATEMALA','N','GUA','N','1',null,'O','502','GTM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GU','GUAM','350','GUAM','N','GUM','N','3',null,'O','1','GUM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GW','GUINEE BISSAU','670','GUINEA BISSAU','N','BXO','N','1',null,'O','245','GNB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GY','GUYANA','95','GUYANA','N','GEO','N','1',null,'O','592','GUY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HK','HONG KONG','375','HONG KONG','N','HKG','N','1',null,'O','852','HKG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HN','HONDURAS','370','HONDURAS','N','TGU','N','1',null,'O','504','HND');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HR','CROATIE','222','CROATIA','N','ZAG','N','4',null,'O','385','HRV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HT','HAITI','365','HAITI','N','PAP','N','1',null,'O','509','HTI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HU','HONGRIE','380','HUNGARY','N','BUD','N','2',null,'O','36','HUN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ID','INDONESIE','395','INDONESIA','N','JKT','N','2',null,'O','62','IDN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IE','IRLANDE','410','IRELAND','N','DUB','N','2',null,'O','353','IRL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IL','ISRAEL','415','ISRAEL','N','TLV','N','1',null,'O','972','ISR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IN','INDE','390','INDIA','N','DEL','N','2',null,'O','91','IND');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IQ','IRAQ','405','IRAQ','N','BGW','N','2',null,'O','964','IRQ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IR','IRAN, REPUBLIQUE ISLAMIQUE D','400','IRAN, ISLAMIC REPUBLIC OF','N','THR','N','1',null,'O','98','IRN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IS','ISLANDE','385','ICELAND','N','REK','N','1',null,'O','354','ISL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IT','ITALIE','420','ITALY','S','ROM','N','6',null,'O','39','ITA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('JM','JAMAIQUE','430','JAMAICA','N','KIN','N','1',null,'O','1','JAM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('JO','JORDANIE','440','JORDAN','N','AMM','N','2',null,'O','962','JOR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('JP','JAPON','435','JAPAN','S','TYO','N','2',null,'O','81','JPN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KE','KENYA','450','KENYA','N','NBO','N','2',null,'O','254','KEN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KG','KIRGHIZISTAN','457','KYRGYZSTAN','N','FRU','N','1',null,'O','996','KGZ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KH','CAMBODGE','135','CAMBODIA','N','PNH','N','2',null,'O','855','KHM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KI','KIRIBATI','452','KIRIBATI','N','TRW','N','1',null,'O','686','KIR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KM','COMORES','200','COMOROS','N','YVA','N','1',null,'O','269','COM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KN','SAINT KITTS ET NEVIS','697','SAINT KITTS AND NEVIS','N','SKB','N','1',null,'O','1','KNA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KP','COREE, REP. POPULAIRE DEM. DE','610','KOREA, DEM. PEOPLE S REP. OF','N','FNJ','N','2',null,'O','850','PRK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KR','COREE, REPUBLIQUE DE','760','KOREA, REPUBLIC OF','N','SEL','N','2',null,'O','82','KOR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KW','KOWEIT','455','KUWAIT','N','KWI','N','1',null,'O','965','KWT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KY','CAIMANES, ILES','110','CAYMAN ISLANDS','N','GCM','N','2',null,'O','1','CYM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('KZ','KAZAKHSTAN','445','KAZAKHSTAN','N','ALA','N','3',null,'O','7','KAZ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LA','LAO, REP. DEM. POPULAIRE','460','LAO PEOPLE S DEMOCRATIC REP.','N','VTE','N','1',null,'O','856','LAO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LB','LIBAN','465','LEBANON','N','BEY','N','2',null,'O','961','LBN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LC','SAINTE LUCIE','698','SAINT LUCIA','N','SLU','N','1',null,'O','1','LCA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LI','LIECHTENSTEIN','476','LIECHTENSTEIN','N','QVU','N','1',null,'O','423','LIE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LK','SRI LANKA','175','SRI LANKA','N','CMB','N','2',null,'O','94','LKA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LR','LIBERIA','470','LIBERIA','N','MLW','N','1',null,'O','231','LBR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LS','LESOTHO','468','LESOTHO','N','MSU','N','2',null,'O','266','LSO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LT','LITUANIE','477','LITHUANIA','N','VNO','N','4',null,'O','370','LTU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LU','LUXEMBOURG','480','LUXEMBOURG','S','LUX','N','1',null,'O','352','LUX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LV','LETTONIE','463','LATVIA','N','RIX','N','5',null,'O','371','LVA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('LY','LIBYENNE, JAMAHIRIYA ARABE','475','LIBYAN ARAB JAMAHIRIYA','N','TIP','N','1',null,'O','218','LBY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MA','MAROC','550','MOROCCO','N','CAS','N','1',null,'O','212','MAR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MC','MONACO','540','MONACO','S','MCM','O','1',null,'O','377','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MD','MOLDOVA, REPUBLIQUE DE','538','MOLDOVA, REPUBLIC OF','N','KIV','N','4',null,'O','373','MDA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MG','MADAGASCAR','495','MADAGASCAR','N','TNR','N','1',null,'O','261','MDG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MH','MARSHALL, ILES','520','MARSHALL ISLANDS','N','TIC','N','3',null,'O','692','MHL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MK','MACEDOINE, EX REP. YOUGOSLAVE','493','MACEDONIA,FORMER YUGOSLAV REP.','N','SKP','N','1',null,'O','389','MKD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ML','MALI','510','MALI','N','BKO','N','1',null,'O','223','MLI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MM','MYANMAR','125','MYANMAR','N','RGN','N','2',null,'O','95','MMR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MN','MONGOLIE','545','MONGOLIA','N','ULN','N','2',null,'O','976','MNG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MO','MACAO','490','MACAO','N','QMP','N','1',null,'O','853','MAC');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MP','MARIANNES DU NORD, ILES','620','NORTHERN MARIANA ISLANDS','N','SPN','N','3',null,'O','1','MNP');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MQ','MARTINIQUE','521','MARTINIQUE','S','FDF','O','1',null,'O','596','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MR','MAURITANIE','525','MAURITANIA','N','NKC','N','1',null,'O','222','MRT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MS','MONTSERRAT','548','MONTSERRAT','N','MNI','N','1',null,'O','1','MSR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MT','MALTE','515','MALTA','N','MLA','N','2',null,'O','356','MLT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MU','MAURICE','530','MAURITIUS','N','MRU','N','1',null,'O','230','MUS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MV','MALDIVES','507','MALDIVES','N','MLE','N','2',null,'O','960','MDV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MW','MALAWI','500','MALAWI','N','BLZ','N','1',null,'O','265','MWI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MX','MEXIQUE','535','MEXICO','N','MEX','N','6',null,'O','52','MEX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MY','MALAISIE','505','MALAYSIA','N','KUL','N','1',null,'O','60','MYS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MZ','MOZAMBIQUE','555','MOZAMBIQUE','N','MPM','N','1',null,'O','258','MOZ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NA','NAMIBIE','770','NAMIBIA','N','WDH','N','1',null,'O','264','NAM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NC','NOUVELLE CALEDONIE','575','NEW CALEDONIA','S','NOU','O','1',null,'O','687','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NE','NIGER','600','NIGER','N','NIM','N','1',null,'O','227','NER');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NF','NORFOLK, ILE','617','NORFOLK ISLAND','N','NLK','N','3',null,'O','672','NFK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NG','NIGERIA','605','NIGERIA','N','LOS','N','2',null,'O','234','NGA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NI','NICARAGUA','595','NICARAGUA','N','MGA','N','1',null,'O','505','NIC');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NL','PAYS BAS','565','NETHERLANDS','S','AMS','O','1',null,'O','31','NLD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NO','NORVEGE','625','NORWAY','S','OSL','O','1',null,'O','47','NOX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NP','NEPAL','560','NEPAL','N','KTM','N','2',null,'O','977','NPL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NR','NAURU','557','NAURU','N','INU','N','1',null,'O','674','NRU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NU','NIUE','615','NIUE','N','IUE','N','2',null,'O','683','NIU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('NZ','NOUVELLE ZELANDE','590','NEW ZEALAND','N','AKL','N','2',null,'O','64','NZL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('OM','OMAN','630','OMAN','N','MCT','N','1',null,'O','968','OMN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PA','PANAMA','640','PANAMA','N','PTY','N','1',null,'O','507','PAN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PE','PEROU','650','PERU','N','LIM','N','1',null,'O','51','PER');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PF','POLYNESIE FRANCAISE','305','FRENCH POLYNESIA','S','PPT','O','1',null,'O','689','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PG','PAPOUASIE NOUVELLE GUINEE','642','PAPUA NEW GUINEA','N','POM','N','7',null,'O','675','PNG');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PH','PHILIPPINES','655','PHILIPPINES','N','MNL','N','1',null,'O','63','PHL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PK','PAKISTAN','635','PAKISTAN','N','KHI','N','2',null,'O','92','PAK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PL','POLOGNE','660','POLAND','N','WAW','N','1',null,'O','48','POL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PM','SAINT PIERRE ET MIQUELON','700','SAINT PIERRE AND MIQUELON','S','YPM','O','1',null,'O','508','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PR','PORTO RICO','675','PUERTO RICO','N','SJU','N','3',null,'O','1','PRI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PS','PALESTINIEN OCCUPE, TERRITOIRE','638','PALESTINIAN TERRITORY,OCCUPIED','N','GZA','N','1',null,'O','970','PSE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PT','PORTUGAL','665','PORTUGAL','S','LIS','N','1',null,'O','351','PRT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PW','PALAOS','637','PALAU','N','ROR','N','3',null,'O','680','PLW');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PY','PARAGUAY','645','PARAGUAY','N','ASU','N','1',null,'O','595','PRY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('QA','QATAR','680','QATAR','N','DOH','N','1',null,'O','974','QAT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('RE','REUNION','685','REUNION','S','RUN','O','1',null,'O','262','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('RO','ROUMANIE','690','ROMANIA','N','BUH','N','1',null,'O','40','ROU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('RU','RUSSIE, FEDERATION DE','900','RUSSIAN FEDERATION','N','MOW','N','2',null,'O','7','RUS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('RW','RWANDA','695','RWANDA','N','KGL','N','1',null,'O','250','RWA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SA','ARABIE SAOUDITE','720','SAUDI ARABIA','N','JED','N','2',null,'O','966','SAU');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SB','SALOMON, ILES','743','SOLOMON ISLANDS','N','HIR','N','1',null,'O','677','SLB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SC','SEYCHELLES','730','SEYCHELLES','N','SEZ','N','1',null,'O','248','SYC');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SD','SOUDAN','800','SUDAN','N','KRT','N','1',null,'O','249','SDN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SE','SUEDE','815','SWEDEN','N','STO','O','1',null,'O','46','SWX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SG','SINGAPOUR','740','SINGAPORE','S','SIN','N','2',null,'O','65','SGP');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SH','SAINTE HELENE','696','SAINT HELENA','N','ASI','N','2',null,'O','290','SHN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SI','SLOVENIE','742','SLOVENIA','N','LJU','N','4',null,'O','386','SVN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SK','SLOVAQUIE','741','SLOVAKIA','S','BTS','N','1',null,'O','421','SVK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SL','SIERRA LEONE','735','SIERRA LEONE','N','FNA','N','1',null,'O','232','SLE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SM','SAINT MARIN','707','SAN MARINO','N','SAI','N','1',null,'O','378','SMR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SN','SENEGAL','725','SENEGAL','N','DKR','N','1',null,'O','221','SEN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SO','SOMALIE','745','SOMALIA','N','MGQ','N','2',null,'O','252','SOM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SR','SURINAME','805','SURINAME','N','PBM','N','1',null,'O','597','SUR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ST','SAO TOME ET PRINCIPE','715','SAO TOME AND PRINCIPE','N','TMS','N','1',null,'O','239','STP');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SV','EL SALVADOR','262','EL SALVADOR','N','SAL','N','1',null,'O','503','SLV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SY','SYRIENNE, REPUBLIQUE ARABE','825','SYRIAN ARAB REPUBLIC','N','DAM','N','1',null,'O','963','SYR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SZ','SWAZILAND','810','SWAZILAND','N','MTS','N','2',null,'O','268','SWZ');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TC','TURKS ET CAIQUES, ILES','863','TURKS AND CAICOS ISLANDS','N','PLS','N','2',null,'O','1','TCA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TD','TCHAD','180','CHAD','N','NDJ','N','1',null,'O','235','TCD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TG','TOGO','845','TOGO','N','LFW','N','1',null,'O','228','TGO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TH','THAILANDE','835','THAILAND','N','BKK','N','2',null,'O','66','THA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TJ','TADJIKISTAN','830','TAJIKISTAN','N','LBD','N','1',null,'O','992','TJK');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TM','TURKMENISTAN','866','TURKMENISTAN','N','ASB','N','1',null,'O','993','TKM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TN','TUNISIE','860','TUNISIA','N','TUN','N','1',null,'O','216','TUN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TO','TONGA','850','TONGA','N','TBU','N','1',null,'O','676','TON');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TR','TURQUIE','865','TURKEY','N','IST','N','1',null,'O','90','TUR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TT','TRINITE ET TOBAGO','853','TRINIDAD AND TOBAGO','N','TTD','N','1',null,'O','1','TTO');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TV','TUVALU','867','TUVALU','N','TRW','N','1',null,'O','688','TUV');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TW','TAIWAN, PROVINCE DE CHINE','290','TAIWAN, PROVINCE OF CHINA','N','TPE','N','1',null,'O','886','TWN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TZ','TANZANIE, REPUBLIQUE UNIE DE','883','TANZANIA, UNITED REPUBLIC OF','N','DAR','N','1',null,'O','255','TZA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('UA','UKRAINE','872','UKRAINE','N','IEV','N','2',null,'O','380','UKR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('UG','OUGANDA','870','UGANDA','N','EBB','N','1',null,'O','256','UGA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('UM','ILES MINEURES ELOIGNEES DES US','888','US MINOR OUTLYING ISLANDS','N','AWK','N','3',null,'O',null,'UMI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('US','ETATS UNIS','885','UNITED STATES','S','NYC','O','3',null,'O','1','USA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('UY','URUGUAY','895','URUGUAY','N','MVD','N','1',null,'O','598','URY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('UZ','OUZBEKISTAN','903','UZBEKISTAN','N','TAS','N','3',null,'O','998','UZB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VC','SAINT VINCENT ET GRENADINES','705','SAINT VINCENT AND GRENADINES','N','SVD','N','1',null,'O','1','VCT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VE','VENEZUELA','905','VENEZUELA','N','CCS','N','8',null,'O','58','VEN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VG','ILES VIERGES BRITANNIQUES','97','VIRGIN ISLANDS, BRITISH','N','TOV','N','2',null,'O','1','VGB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VI','ILES VIERGES DES ETATS UNIS','910','VIRGIN ISLANDS, U.S.','N','STT','N','3',null,'O','1','VIR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VN','VIET NAM','765','VIET NAM','N','SGN','N','2',null,'O','84','VNM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VU','VANUATU','585','VANUATU','N','VLI','N','1',null,'O','678','VUT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('WF','WALLIS ET FUTUNA','918','WALLIS AND FUTUNA','S','WLS','N','1',null,'O','681','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('WS','SAMOA','920','SAMOA','N','APW','N','1',null,'O','685','WSM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('YE','YEMEN','930','YEMEN','N','SAH','N','1',null,'O','967','YEM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('YT','MAYOTTE','531','MAYOTTE','S','DZA','O','1',null,'O','262','FRX');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('RS','SERBIE',null,'SERBIA','N','BEG','N','1',null,'O','381','SRB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ZA','AFRIQUE DU SUD','755','SOUTH AFRICA','N','JNB','N','2',null,'O','27','ZAF');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ZM','ZAMBIE','938','ZAMBIA','N','LUN','N','1',null,'O','260','ZMB');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ZW','ZIMBABWE','775','ZIMBABWE','N','HRE','N','1',null,'O','263','ZWE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ZZ','DON T USE---> UNKNOWN COUNTRY',null,'DON T USE--->','N',null,'N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CX','CHRISTMAS, ILE','191','CHRISTMAS ISLAND','N','XCH','N','3',null,'O','61','CXR');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CD','CONGO, LA REP. DEMOCRATIQUE DU','210','CONGO, DEMOCRATIC REP. OF THE','N','FIH','N','1',null,'O','243','COD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('XA','DON T USE---> GAZA',null,'DON T USE--->','N','ZDY','N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ME','MONTENEGRO',null,'MONTENEGRO','N','TGD','N','1',null,'O','382','MNE');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('ER','ERYTHREE','266','ERITREA','N','ASM','N','1',null,'O','291','ERI');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('XU','DON T USE---> RUSSIE','901','DON T USE---> RUSSIA','N','IKT','N','2',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TP','TIMOR LESTE','29','TIMOR LESTE','N','KOE','N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('M1','MONDE',null,'WORLD','N',null,'N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TL','TIMOR LESTE','29','TIMOR LESTE','N',null,'N','1',null,'O','670','TLS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CS','NE PAS UTILISER',null,'DO NOT USE','N','BEG','N','1',null,'O',null,null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BV','BOUVET, ILE',null,'BOUVET ISLAND','N',null,'N','1',null,'O',null,'BVT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('EH','SAHARA OCCIDENTAL',null,'WESTERN SAHARA','N',null,'N','1',null,'O','212','ESH');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GS','GEORGIE DU SUD,ILES SANDWICH',null,'SOUTH GEORGIA,SANDWICH ISLANDS','N',null,'N','2',null,'O',null,'SGS');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('HM','HEARD, ILE ET MCDONALD, ILES',null,'HEARD ISLAND, MCDONALD ISLANDS','N',null,'N','1',null,'O',null,'HMD');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IO','OCEAN INDIEN, TER. BRITANNIQUE',null,'BRITISH INDIAN OCEAN TERRITORY','N',null,'N','2',null,'O','246','IOT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('PN','PITCAIRN',null,'PITCAIRN','N',null,'N','2',null,'O',null,'PCN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SJ','SVALBARD ET ILE JAN MAYEN',null,'SVALBARD AND JAN MAYEN','N',null,'N','1',null,'O','47','SJM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TF','TERRES AUSTRALES FRANCAISES',null,'FRENCH SOUTHERN TERRITORIES','N',null,'N','1',null,'O',null,'ATF');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('TK','TOKELAU','847','TOKELAU','N',null,'N','2',null,'O','690','TKL');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('VA','SAINT SIEGE (CITE DU VATICAN)',null,'HOLY SEE (VATICAN CITY STATE)','N',null,'N','1',null,'O','379','VAT');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BL','SAINT BARTHELEMY','652','SAINT BARTHELEMY','N','SBH','N','1',null,'O','590','BLM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('MF','SAINT MARTIN','663','SAINT MARTEEN','N','SXM','N','1',null,'O','590','MAF');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('BQ','BONAIRE, ST EUSTACHE ET SABA','84','BONAIRE, ST EUSTATIUS AND SABA','N','BON','N','1',null,'O','599','BES');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('CW','CURACAO','230','CURACAO','N','CUR','N','1',null,'O','599','CUW');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SX','SAINT MAARTEN','699','SAINT MAARTEN','N','SXM','N','1',null,'O','1','SXM');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('SS','SUD SOUDAN','758','SOUTH SUDAN','N','JUB','N',null,null,'O','211',null);
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('AX','ILES ALAND','995','ALAND ISLANDS','N','MHQ','N',null,null,'O','358','ALA');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('GG','GUERNESEY','996','GUERNSEY','N',null,'N','2',null,'O','44','GGY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('IM','ILE DE MAN','833','ISLE OF MAN','N',null,'N','2',null,'O','44','IMN');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('JE','JERSEY','832','JERSEY','N',null,'N','2',null,'O','44','JEY');
Insert into PAYS (SCODE_PAYS,SLIBELLE_PAYS,ICODE_IATA,SLIBELLE_PAYS_EN,CODE_GESTION_CP,SCODE_CAPITALE,NORMALISABLE,FORMAT_ADR,IFORMAT_ADR,SFORCAGE,STELECOM_COUNTRY_CODE,SCODE_ISO3) values ('XK','KOSOVO',null,'KOSOVO','N',null,'N','1',null,'O','383','XKX');

  CREATE TABLE PROFILS
   (
	IVERSION NUMBER(12),
	SMAILING_AUTORISE VARCHAR(1),
	SRIN VARCHAR(16),
	SSOLVABILITE VARCHAR(1),
	SCODE_PROFESSIONNEL VARCHAR(2),
	SCODE_MARITALE VARCHAR(1),
	SCODE_LANGUE VARCHAR(2),
	SGIN VARCHAR(12),
	SCODE_FONCTION VARCHAR(3),
	INB_ENFANTS NUMBER(12),
	SSEGMENT VARCHAR(10),
	SETUDIANT VARCHAR(1)
	);



  CREATE TABLE ACCOUNT_DATA
   (	ID NUMBER(12,0),
	IVERSION NUMBER,
	ACCOUNT_IDENTIFIER VARCHAR(8),
	SGIN VARCHAR(12),
	FB_IDENTIFIER VARCHAR(16),
	EMAIL_IDENTIFIER VARCHAR(60),
	PERSONALIZED_IDENTIFIER VARCHAR(16),
	STATUS VARCHAR(1),
	PASSWORD VARCHAR(255),
	PASSWORD_TO_CHANGE NUMBER(1,0),
	TEMPORARY_PWD VARCHAR(255),
	TEMPORARY_PWD_END_DATE DATE,
	SECRET_QUESTION_OLD VARCHAR(200),
	SECRET_QUESTION_ANSWER VARCHAR(255),
	NB_FAILURE_AUTHENTIFICATION NUMBER(1,0),
	NB_FAILURE_SECRET_QUESTION_ANS NUMBER(1,0),
	ENROLEMENT_POINT_OF_SELL VARCHAR(3),
	CARRIER VARCHAR(2),
	LAST_CONNECTION_DATE DATE,
	LAST_PWD_RESET_DATE DATE,
	ACCOUNT_DELETION_DATE DATE,
	SSITE_CREATION VARCHAR(10),
	SSIGNATURE_CREATION VARCHAR(16),
	DDATE_CREATION DATE,
	SSITE_MODIFICATION VARCHAR(10),
	SSIGNATURE_MODIFICATION VARCHAR(16),
	DDATE_MODIFICATION DATE,
	IP_ADDRESS VARCHAR(50),
	ACCOUNT_UPGRADE_DATE DATE,
	SECRET_QUESTION RAW(1020),
	ACCOUNT_LOCKED_DATE DATE,
	SECRET_QUESTION_ANSWER_UPPER VARCHAR(255),
	LAST_SECRET_ANSW_MODIFICATION DATE,
	SOCIAL_NETWORK_ID VARCHAR(300),
	LAST_SOCIAL_NETWORK_LOGON_DATE DATE,
	LAST_SOCIAL_NETWORK_USED VARCHAR(255),
	LAST_SOCIAL_NETWORK_ID VARCHAR(255)
	);

	CREATE SEQUENCE  ISEQ_COMM_PREF  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;
	CREATE SEQUENCE  SEQ_MARKET_LANGUAGE  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 ;