replicaCount: 2

# Describes the pdb.Value for this is half of replica count
podDisruptionBudget:
  minAvailable: 1

# claim the user node pool for deployment
nodeSelector:
  kubernetes.azure.com/mode: user


image:
  repository: acrriprd09999808.azurecr.io/customer-adaptor
  pullPolicy: "Always"
  tag: latest


serviceAccount:
  # Specifies whether a service account should be created or not
  create: true

customLabels:
  application_service1: REFERENTIEL_INDIVIDUS_PRD_AZURE

volumes:
  - name: etc
    emptyDir: {}
  - name: config
    emptyDir: {}

volumeMounts:
  - name: etc
    mountPath: /etc
  - name: config
    mountPath: /etc/config

rbac:
  enabled: true
  roles:
    - apiGroups: [""]
      resources: ["pods", "nodes", "configmaps", "endpoints", "namespaces", "services", "events"]
      verbs: ["get", "list", "watch" ]
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: [ "create", "update"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]


isTmpVolumeRequired: true

deployment:
  containerPort: 8080
#  command:
#    - - "/bin/sh"
#    - - "-c"
#    - - "base64 -d /mnt/secrets-store/ri-prd-client-jaas-config > /tmp/client_jaas_repind.conf && base64 -d /mnt/secrets-store/ri-prd-keytab > /tmp/repind_PRD.FRANCE.AIRFRANCE.FR.keytab && ${JAVA_HOME} ${JAVA_TOOL_OPTIONS}"
#

#key vault related configuration
secretProvider:
  keyVaultName: 'kv-ri-pr-8366'
  keyVaultRG: 'rg-ri-spoke-prod-frc-001'
  subscriptionId: '9451007c-eb98-4383-a8e9-3a86406810ee'
  keyVaultTenantId: '9b802d8b-33fa-40fb-acb7-9ffdbd1919eb'
  objects:
    - objectName: vaultRoleId # Key Vault secret name
      objectType: "secret"
    - objectName: vaultSecretId # Key Vault secret name
      objectType: "secret"
    - objectName: ri-prd-client-jaas-config # Key Vault secret name
      objectEncoding: "base64"
      objectType: "secret"
    - objectName: ri-prd-keytab # The name of the secrets in your Key Vault
      objectAlias: repind_PRD.FRANCE.AIRFRANCE.FR.keytab  # The alias we're giving it, also the name of the file mounted in your pod
      objectEncoding: "base64"
      objectType: "secret"
  secretObjects: # Sync as Kubernetes Secret
    - secretName: app-secret-ri-customer-adaptor # Kubernetes Secret
      type: Opaque
      data:
        - objectName: vaultRoleId # Key Vault Secret name
          key: VAULT_CREDENTIALS_ROLE_ID # Secret Key
        - objectName: vaultSecretId # Key Vault Secret name
          key: VAULT_CREDENTIALS_SECRET_ID # Secret Key
        - objectName: ri-prd-client-jaas-config # Key Vault Secret name
          key: JAVA_SECURITY_AUTH_LOGIN_CONFIG # Secret Key


# Describes the Azure Managed AAD Pod Identity
azureIdentity:
  name: "customer-adaptor-prd-azureidentity"
  type: 0
  configmap:
    name: aks-kv-sp-identity
    namespace: prd
    clientid: aks-kv-sp-client-id
    resourceid: aks-kv-sp-resource-id

# Describes the identity binding relationship between an AzureIdentity and a pod with a specific selector as part of its label
azureIdentityBinding:
  name: "customer-adaptor-prd-azureidentitybinding"
  selector: "customer-adaptor-prd-selector"

# Specifies whether autoscaling should be enabled or not
autoscaling:
  enabled: 'true'
  minReplicas: 2
  maxReplicas: 4
  targetAverageUtilization: 80
  targetAverageValue: 40Mi

ingress:
  annotations:
    kubernetes.io/ingress.class: haproxy
  private:
    enabled: 'true'
    annotations:
      kubernetes.io/ingress.class: haproxy
    hosts:
      - host: customer-adaptor-rs.azure.airfranceklm.com
        paths:
          - /api-mgr/customer-adaptor
  tls:
    - hosts:
        - customer-adaptor-rs.azure.airfranceklm.com
      secretName: defaultcert

# resource management for pods
resources:
  limits:
    cpu: 800m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 500Mi

##liveness and readiness probe for container
#probes:
#  livenessProbe:
#    path: /api-mgr/customer-adaptor/infra/healthcheck
#  readinessProbe:
#    path: /api-mgr/customer-adaptor/infra/healthcheck



service:
  type: ClusterIP
  port: 8080

# config Map individual key/value pairs
configMap:
  SPRING_PROFILES_ACTIVE: "LE,prd"
  SPRING_DATASOURCE_TNS_ADMIN_ENV: "PROD"
  SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@SIC_PLE.WORLD"
  VAULT_NAMESPACE: "repind"
  VAULT_ENV: "prod"
  SPRING_APPLICATION_NAME: "CUSTOM_ADAPTOR"
  REPIND_ACRONYME: "prod"
  REPIND_TOPIC: "P.log-APP.REPIND.001"
  REPIND_BOOTSTRAP_SERVERS: "qvipclogkb01.france.airfrance.fr:6668,qvipclogkb02.france.airfrance.fr:6668,qvipclogkb03.france.airfrance.fr:6668,qvipclogkb04.france.airfrance.fr:6668"
  JAVA_HOME: /layers/paketo-buildpacks_adoptium/jre/bin/java
  JAVA_TOOL_OPTIONS: "-Doracle.jdbc.timezoneAsRegion=false -Dspring.profiles.active=azure,kube,LE,prd -Djava.security.krb5.kdc=qvipbkrbrs01.france.airfrance.fr -Djava.security.krb5.realm=PRD.FRANCE.AIRFRANCE.FR -Djava.security.auth.login.config=/mnt/secrets-store/ri-prd-client-jaas-config -Djava.sun.security.krb5.debug=true -Dzookeeper.sasl.client=false --add-opens=java.base/java.lang=ALL-UNNAMED"

# env variables from secretProviderClass
envFrom:
  - secretRef:
      name: app-secret-ri-customer-adaptor
