# Sample pod to be applied manually when desired
# Executes a backup against the DB when tailored to the right endpoint.
# Copies resulting full backup to $BUCKET
apiVersion: v1
kind: Pod
metadata:
  name: neo4j-backup
spec:
  restartPolicy: Never
  containers:
    - name: neo4j-backup
      image: nexusoss-docker.airfrance.fr/repind/neo4j-backup:latest
      env:
      - name: NEO4J_ADDR
        value: "neo4j-db-readreplica-svc"
      - name: BACKUP_NAME
        value: neo4j.db-backup