apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage-individual-identifier
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate