export enum ReferenceDataType {

    CIVILITY = 'REF_CIVILITE',
    INDIVIDUAL_STATUS = 'REF_STATUT_INDIVIDU',
    GENDER = 'REF_SEXE',
    TITLES = 'REF_CODE_TITRE',
    NAT = 'REF_AUTORIS_MAIL',
    BRANCHES = 'DOM_PRO',
    LANGUAGES = 'LANGUES',
    COUNTRY_CODES = 'PAYS',
    PREFERENCE_TYPES = 'REF_PREFERENCE_TYPE',
    PREFERENCE_KEYS = 'REF_PREFERENCE_DATA_KEY',
    STATES_ROLE_CONTRACT = 'REF_ETAT_ROLE_CTR',
    HANDICAP_TYPE = 'REF_HANDICAP_TYPE',
    HANDICAP_CODE = 'REF_HANDICAP_CODE',
    HANDICAP_DATA_KEY = 'REF_HANDICAP_DATA_KEY',
    CONSENT_TYPE = 'REF_CONSENT_TYPE',
    CONSENT_DATA_TYPE = 'REF_CONSENT_DATA_TYPE',
    COMM_PREF_DOMAIN = 'REF_COMPREF_DOMAIN',
    COMM_PREF_GTYPE = 'REF_COMPREF_GTYPE',
    COMM_PREF_MEDIA = 'REF_COMPREF_MEDIA', // Served by the backend, not used yet.
    COMM_PREF_TYPE = 'REF_COMPREF_TYPE',

    BDM_COUNTRIES = 'REF_BDM_COUNTRIES',
    BDM_LANGUAGES = 'REF_BDM_LANGUAGES',
    MEALS = 'REF_MEALS',
    COMFORT = 'REF_COMFORT',
    MEALS_PAID = 'REF_MEALS_PAID',
    READING = 'REF_READING',
    CULTURAL = 'REF_CULTURAL',
    COMFORT_PAID = 'REF_COMFORT_PAID',
    CHANNEL_COMMUNICATION = 'REF_CHANNEL_COMMUNICATION',
    BDM_MEALS = 'REF_BDM_MEALS',
    DRINK_WELCOME = 'REF_DRINK_WELCOME',
    DRINK_BEVERAGES = 'REF_DRINK_BEVERAGES',
    BDM_SEATS = 'REF_BDM_SEATS',
    CHANNEL_CHEKIN = 'REF_CHANNEL_CHEKIN'

}
