spring:
  config:
    activate:
      on-profile: UTE,rct,cae
  datasource:
    tns_admin_env: TEST_ACCEPTANCE
    url: jdbc:oracle:thin:@REPIND_CAE.WORLD

vault:
  uri: https://vault-tls-cae.airfranceklm.com
  namespace: repind
  env: dev
  credentials:
    role_id: ${vault_role_id}
    secret_id: ${vault_secret_id}

ri-search-gin-by-email:
  url: http://search-gin-by-email-cae:8080/