replicaCount: 1

image: 
  repository: acr01rinonprodfrc001.azurecr.io/cati-cs
  pullPolicy: "Always"
  tag: latest


serviceAccount:
  # Specifies whether a service account should be created or not 
  create: true

rbac:
  enabled: true
  roles:
    - apiGroups: [""]
      resources: ["pods", "nodes", "configmaps", "endpoints", "namespaces", "services", "events"]
      verbs: ["get", "list", "watch" ]
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["endpoints"]
      verbs: [ "create", "update"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]

isTmpVolumeRequired: true

#key vault related configuration
secretProvider:
  keyVaultName: 'kv-ri-np-73c0'
  keyVaultRG: 'rg-ri-spoke-nonprod-frc-001'
  subscriptionId: '58b2378a-340e-44be-90d1-85768fdcdf02'
  keyVaultTenantId: '9b802d8b-33fa-40fb-acb7-9ffdbd1919eb'


# Describes the Azure Managed AAD Pod Identity
azureIdentity: 
  name: "repind-cati-cs-cae-azureidentity"
  type: 0
  configmap:
    name: aks-kv-sp-identity
    namespace: cae
    clientid: aks-kv-sp-client-id
    resourceid: aks-kv-sp-resource-id

# Describes the identity binding relationship between an AzureIdentity and a pod with a specific selector as part of its label
azureIdentityBinding:
  name: "repind-cati-cs-cae-azureidentitybinding"
  selector: "repind-cati-cs-cae-selector"

# Specifies whether autoscaling should be enabled or not
autoscaling:
  enabled: false
  minReplicas: 
  maxReplicas: 
  targetAverageUtilization: 
  targetAverageValue: 

ingress:
  annotations:
    kubernetes.io/ingress.class: haproxy
  private: 
    enabled: 'true'
    annotations:
      kubernetes.io/ingress.class: haproxy
    hosts:
      - host: cati-az-rct.airfrance.fr
        paths:
          - /
  tls:
    - hosts:
      - cati-az-rct.airfrance.fr
      secretName: defaultcert

# resource management for pods
resources:
  limits:
    cpu: 800m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 500Mi

deployment:
  containerPort: 8080

service:
  type: ClusterIP
  port: 8080


